### PR TITLE
Change the hover output to not instantiate method generics

### LINKED ISSUE #4150: Hovering on method called on union type shows effective type of method twice
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20%23%20Docs%20for%20A%23foo%0A%20%20sig%20%7Breturns(String)%7D%0A%20%20def%20foo%3B%20''%3B%20end%0Aend%0A%0Aclass%20B%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20%23%20Docs%20for%20B%23foo%0A%20%20sig%20%7Breturns(Integer)%7D%0A%20%20def%20foo%3B%200%3B%20end%0Aend%0A%0Asig%20%7Bparams(x%3A%20T.any(A%2C%20B)).void%7D%0Adef%20example(x)%0A%20%20x.foo%0A%20%20%23%20%5E%20hover%20here%0A%20%20%23%20it%20shows%20the%20method%20def%20twice%0Aend)

```ruby
# typed: true
extend T::Sig

class A
  extend T::Sig

  # Docs for A#foo
  sig {returns(String)}
  def foo; ''; end
end

class B
  extend T::Sig

  # Docs for B#foo
  sig {returns(Integer)}
  def foo; 0; end
end

sig {params(x: T.any(A, B)).void}
def example(x)
  x.foo
  # ^ hover here
  # it shows the method def twice
end
```

#### Observed output

```
No errors! Great job.
```

Screen Shot 2021-04-15 at 6 02 03 PM

#### Expected behavior

It should either:

- show two defs, one for each method, or ideally:
- one `def` with the effective type.

- - -

### LINKED ISSUE #8195: Crash when hovering over union of Array and Hash
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20params%28x%3A%20T.any%28T%3A%3AArray%5BInteger%5D%2C%20T%3A%3AHash%5BString%2C%20Symbol%5D%29%29.void%20%7D%0Adef%20example%28x%29%0A%20%20x.map%20do%20%7Celem%7C%0A%20%20%20%20%23%5E%20hover%3A%20jez%0A%20%20%20%20puts%28elem%29%0A%20%20end%0Aend)

```ruby
# typed: strict
extend T::Sig

sig { params(x: T.any(T::Array[Integer], T::Hash[String, Symbol])).void }
def example(x)
  x.map do |elem|
    #^ hover: jez
    puts(elem)
  end
end
```

#### Observed output

Hovering over the call to `.map` causes a crash:

```
[2024-09-23 22:09:57.776] [fatalFallback] [error] Exception::raise(): Failed to find entry in TypeConstraint::solution for type argument
```

The crash backtrace when reached from the test runner:

```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=1, subcode=0x1012e4b80)
  * frame #0: 0x00000001012e4b84 lsp_test_runner`stopInDebugger() at mac.cc:72:9
    frame #1: 0x0000000100101bc4 lsp_test_runner`bool sorbet::Exception::raise<>(fmt=fmt::v8::format_string<> @ 0x000000016fdf8a60) at Exception.h:79:5
    frame #2: 0x0000000101148564 lsp_test_runner`sorbet::core::TypeConstraint::findSolution(this=0x0000600001303f70, forWhat=(_id = 51)) const at TypeConstraint.cc:233:5
    frame #3: 0x000000010114848c lsp_test_runner`sorbet::core::TypeConstraint::getInstantiation(this=0x0000600001303f70, sym=(_id = 51)) const at TypeConstraint.cc:141:12
    frame #4: 0x00000001011edd2c lsp_test_runner`sorbet::core::TypeVar::_instantiate(this=0x000060000321a1d0, gs=0x0000000153057000, tc=0x0000600001303f70) const at typemaps.cc:45:15
    frame #5: 0x0000000101159c7c lsp_test_runner`decltype(auto) sorbet::core::(anonymous namespace)::CALL_MEMBER_impl__instantiate<sorbet::core::TypeVar const, true>::call<sorbet::core::GlobalState const&, sorbet::core::TypeConstraint const&>(self=0x000060000321a1d0, args=0x0000000153057000, args=0x0000600001303f70) at TypePtr.cc:48:1
    frame #6: 0x0000000101159a0c lsp_test_runner`sorbet::core::TypePtr::_instantiate(this=0x0000600003073790, gs=0x0000000153057000, tc=0x0000600001303f70) const at TypePtr.cc:332:5
    frame #7: 0x00000001011ef4f0 lsp_test_runner`sorbet::core::OrType::_instantiate(this=0x0000600003073780, gs=0x0000000153057000, tc=0x0000600001303f70) const at typemaps.cc:222:30
    frame #8: 0x0000000101159cb8 lsp_test_runner`decltype(auto) sorbet::core::(anonymous namespace)::CALL_MEMBER_impl__instantiate<sorbet::core::OrType const, true>::call<sorbet::core::GlobalState const&, sorbet::core::TypeConstraint const&>(self=0x0000600003073780, args=0x0000000153057000, args=0x0000600001303f70) at TypePtr.cc:48:1
    frame #9: 0x0000000101159a28 lsp_test_runner`sorbet::core::TypePtr::_instantiate(this=0x000060000322c530, gs=0x0000000153057000, tc=0x0000600001303f70) const at TypePtr.cc:332:5
    frame #10: 0x00000001011ee7ac lsp_test_runner`std::__1::optional<std::__1::vector<sorbet::core::TypePtr, std::__1::allocator<sorbet::core::TypePtr>>> sorbet::core::(anonymous namespace)::instantiateElems<sorbet::core::GlobalState, sorbet::core::TypeConstraint>(elems=size=1, methodArgs=0x0000000153057000, methodArgs=0x0000600001303f70) at typemaps.cc:93:20
    frame #11: 0x00000001011efd94 lsp_test_runner`sorbet::core::AppliedType::_instantiate(this=0x0000600003073840, gs=0x0000000153057000, tc=0x0000600001303f70) const at typemaps.cc:306:42
    frame #12: 0x0000000101159da8 lsp_test_runner`decltype(auto) sorbet::core::(anonymous namespace)::CALL_MEMBER_impl__instantiate<sorbet::core::AppliedType const, true>::call<sorbet::core::GlobalState const&, sorbet::core::TypeConstraint const&>(self=0x0000600003073840, args=0x0000000153057000, args=0x0000600001303f70) at TypePtr.cc:48:1
    frame #13: 0x0000000101159a98 lsp_test_runner`sorbet::core::TypePtr::_instantiate(this=0x000000016fdf9820, gs=0x0000000153057000, tc=0x0000600001303f70) const at TypePtr.cc:332:5
    frame #14: 0x00000001011eda80 lsp_test_runner`sorbet::core::Types::instantiate(gs=0x0000000153057000, what=0x000000016fdf9820, tc=0x0000600001303f70) at typemaps.cc:28:19
    frame #15: 0x000000010033d264 lsp_test_runner`sorbet::realmain::lsp::HoverTask::runRequest(this=0x0000600001303c00, typechecker=0x00006000030735e0) at hover.cc:94:27
    frame #16: 0x00000001003da7f8 lsp_test_runner`sorbet::realmain::lsp::LSPRequestTask::run(this=0x0000600001303c00, typechecker=0x00006000030735e0) at LSPTask.cc:222:21
    frame #17: 0x000000010042538c lsp_test_runner`sorbet::realmain::lsp::(anonymous namespace)::TypecheckerTask::run(this=0x0000600001b3f6c8) at LSPTypecheckerCoordinator.cc:58:19
    frame #18: 0x000000010041f070 lsp_test_runner`sorbet::realmain::lsp::LSPTypecheckerCoordinator::asyncRunInternal(this=0x000000015223ca98, task=std::__1::shared_ptr<sorbet::core::lsp::Task>::element_type @ 0x0000600001b3f6c8 strong=2 weak=1) at LSPTypecheckerCoordinator.cc:129:15
    frame #19: 0x000000010041f270 lsp_test_runner`sorbet::realmain::lsp::LSPTypecheckerCoordinator::syncRun(this=0x000000015223ca98, task=nullptr) at LSPTypecheckerCoordinator.cc:137:5
    frame #20: 0x0000000100439fb4 lsp_test_runner`sorbet::realmain::lsp::LSPLoop::runTask(this=0x000000015223ca18, task=nullptr) at LSPLoop.cc:190:26
    frame #21: 0x00000001004397fc lsp_test_runner`sorbet::realmain::lsp::LSPLoop::processRequests(this=0x000000015223ca18, messages=<unavailable>) at LSPLoop.cc:145:13
    frame #22: 0x00000001004433d4 lsp_test_runner`sorbet::realmain::lsp::SingleThreadedLSPWrapper::getLSPResponsesFor(this=0x0000600001e05d00, messages=size=0) at wrapper.cc:69:14
    frame #23: 0x0000000100146db0 lsp_test_runner`sorbet::test::getLSPResponsesFor(wrapper=0x0000600001e05d00, messages=size=0) at lsp.cc:490:27
    frame #24: 0x0000000100143ee4 lsp_test_runner`sorbet::test::getLSPResponsesFor(wrapper=0x0000600001e05d00, message=nullptr) at lsp.cc:530:12
    frame #25: 0x0000000100183360 lsp_test_runner`sorbet::test::HoverAssertion::check(this=0x00006000014087f8, sourceFileContents=0x000000016fdfc2f8, wrapper=0x0000600001e05d00, nextId=0x000000016fdfc214, errorPrefix="") at position_assertions.cc:1329:22
    frame #26: 0x000000010018309c lsp_test_runner`sorbet::test::HoverAssertion::checkAll(assertions=size=1, sourceFileContents=0x000000016fdfc2f8, wrapper=0x0000600001e05d00, nextId=0x000000016fdfc214, errorPrefix="") at position_assertions.cc:1291:30
    frame #27: 0x0000000100011e2c lsp_test_runner`sorbet::test::DOCTEST_ANON_FUNC_58() at lsp_test_runner.cc:850:5
    frame #28: 0x00000001014371c8 lsp_test_runner`doctest::Context::run(this=0x000000016fdfd1f8) at doctest.h:6930:21
    frame #29: 0x0000000100013450 lsp_test_runner`main(argc=2, argv=0x000000016fdfd848) at lsp_test_runner.cc:984:20
    frame #30: 0x000000018e153274 dyld`start + 2840
```

#### Expected behavior

- - -

### PR DESCRIPTION
**Pull request by jez**
### Motivation

Fixes #8195
Fixes #4150

At first, I was about to fix the problem in #8195 by way of making Sorbet do the
"right" thing--the problem on master is that Sorbet uses a `TypeConstraint` to
`instantiate` a `TypePtr` but that `TypeConstraint` only makes sense for the
type in one of the components of the `DispatchResult`, not the `returnType` of
the whole `DispatchResult`.

But as I got further along, I started to think that showing the instantiated
types in the hover result is not actually that useful. It causes problems like
#4150 where the hover results are confusing, and also makes it hard to figure
out whether/how to change a call to a generic method (because you can't see
which parameters are concrete and which parameters are type vars that have
simply been instantiated for this call).

I went down a rabbit hole trying to solve all problems with `DispatchResults` in this PR but ran out of time on my timebox. I've opened issues for most of the problems I'm punting on.

### Commit summary

- **prework: Add a test** (e9d37568fe)

  This case was not covered (I noticed that one of my tests did not break 
  CI).

- **Don't instantiate the resultType** (2a16177e1d)

- **Stop replacing T.self_type and T.type_parameter** (bcff297f9a)

- **no-op: Remove now-unused constraint from getResultType** (471e5f51e5)

- **no-op: Formatting** (6e98ea2b38)

- **no-op: Also remove it from prettyTypeForMethod** (8543ce5247)

- **no-op: Formatting** (7631f378c8)

- **Always use the resultType from the MethodRef** (8df52eff4d)

  ... never uses the resultType from a DispatchResult. The one on the 
  DispatchResult might have certain generics instantiated (e.g., if the 
  call to the method was generic and the method does not take a block, 
  then it will have had its generics instantiated).

- **no-op: Remove now-unused retType from prettyTypeForMethod** (7417f492a4)

- **Update the tests that change** (8a6d0a5b17)

- **Add a test for T.self_type; tweak printing** (323296d7ef)

- **Add `# result type:` comment on hover for sends** (70f54a2a8a)

- **Show full method name in comment above each def** (8bfb1026d0)

  Makes it easier to see how union types are inferred.

- **Put SolveConstraint result into shared DispatchResult** (b78f4ff078)

- **Update the tests that change** (0f309aa8a9)

- **Add a test** (744b7d0b79)

  This test previously crashed because we would look for one of the type 
  parameters in the constraint for the wrong `DispatchComponent`.

  By not using the constraints in the hover results anymore, we sidestep 
  this problem entirely.

  Fixes #8195

- **Add some more tests** (99571fab5b)

### Test plan

- [x] Update tests
- [x] Write new tests for uncovered things
- [x] Write tests for any issues you think this fixes
- [x] Figure out what to do about the case when `returnType` is not solved,
  because we're waiting to see the `SolveConstraint` node after handling the
  block.

### CODE REVIEW

File: test/testdata/lsp/genericMethods.rb [hunk 1]
```diff
@@ -15,24 +15,44 @@ def self.id(a)
...
+  #        ^ hover: sig { params(a: T.type_parameter(:A)).returns(T.type_parameter(:A)) }
+  #        ^ usage: staticid
   v4 = Foo.id("1")
 # ^ hover: String
-         # ^ hover: sig { params(a: String).returns(String) }
-         # ^ usage: staticid
+  #        ^ hover: sig { params(a: T.type_parameter(:A)).returns(T.type_parameter(:A)) }
+  #        ^ usage: staticid
+
+  v5 = Foo.block_id do
```
Comment (elliottt) [inline test/testdata/lsp/genericMethods.rb:48]: Is it worth adding a hover for `v5` as well here?

File: test/testdata/lsp/hover.rb [hunk 2]
```diff
@@ -146,10 +146,26 @@ def main
       # ^^^^^^ hover: The docs for BigFoo
 
   foo = BigFoo.new
-  #            ^^^ hover: sig { returns(BigFoo) }
+  #            ^^^ hover: sig { void }
```
Comment (elliottt) [inline test/testdata/lsp/hover.rb:149]: It's a little unfortunate to see the type here turn to `void`, but it is indeed the correct type for `initialize`.

**Review by elliottt — APPROVED** [review]
This all looks good to me, and I really appreciate the internal simplifications. Seeing the generic type of the method when you hover on it is pretty reasonable I think (and also what rust-analyzer does). The only thing I think is a little unfortunate is that `new` shows the signature for `initialize`, but in a way it's more correct now :)

File: test/testdata/lsp/hover.rb (hunk 2 above)
Comment (jez) [reply test/testdata/lsp/hover.rb:149]: Not pictured in this `hover` assertion is that on the line below in the true hover result there will be a `# result type:` line that has the type being `BigFoo`. The full hover result will be

````
```ruby
# BigFoo#initialize
sig { void }
private def initialize; end

# result type:
BigFoo
```
````

So users will be able to see the type that the expression evaluates to independently of the way that the signature is defined.

Comment (jez) [reply test/testdata/lsp/hover.rb:149]: I think that arguably, this is a better experience for those new to Ruby, to drive home the fact that the relevant method to look at for a call to `new` might be `initialize`—Sorbet will only show the signature here when the class did not have a custom `def self.new` override, so in the case where that method *has* been defined, Sorbet will be able to call attention to it.

File: test/testdata/lsp/genericMethods.rb (hunk 1 above)
Comment (jez) [reply test/testdata/lsp/genericMethods.rb:48]: I don't think so. I think the result of the variable is already covered by other code paths.
