### PR TITLE
Account for `RestArg`'s in `Initializer.cc`

### LINKED ISSUE #2756: **kwargs type is not T::Hash[Symbol, T] but T (same for *rest)
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20do%0A%20%20%20%20params(rest%3A%20String%2C%20kwargs%3A%20String).void%0A%20%20end%0A%20%20def%20initialize(*rest%2C%20**kwargs)%0A%20%20%20%20%23%20This%20fixes%20the%20issue%3A%0A%20%20%20%20%23%20%40args%20%3D%20T.let(kwargs%2C%20T%3A%3AHash%5BSymbol%2C%20String%5D)%20%3B%20%40rest%20%3D%20T.let(rest%2C%20T%3A%3AArray%5BString%5D)%0A%0A%20%20%20%20%23%20this%20fails%3A%0A%20%20%20%20%40args%20%3D%20kwargs%20%3B%20%40rest%20%3D%20rest%0A%20%20end%0A%0A%20%20sig%20do%0A%20%20%20%20params(arg_name%3A%20Symbol).returns(T.nilable(String))%0A%20%20end%0A%20%20def%20retrieve_field(arg_name)%0A%20%20%20%20%40args%5Barg_name%5D%0A%20%20end%0A%0A%20%20sig%20do%0A%20%20%20%20params(index%3A%20Integer).returns(T.nilable(String))%0A%20%20end%0A%20%20def%20retrieve_nth(index)%0A%20%20%20%20%40rest%5Bindex%5D%0A%20%20end%0Aend%0A%0Adef%20main%0A%20%20a%20%3D%20A.new(%22hi%22%2C%20bar%3A%20%22baz%22%2C%20oink%3A%20%22hi%22)%0A%20%20puts%20a.retrieve_field(%3Abar)%0A%20%20puts%20a.retrieve_nth(0)%0Aend)

```ruby
# typed: true
class A
  extend T::Sig
  sig do
    params(rest: String, kwargs: String).void
  end
  def initialize(*rest, **kwargs)
    # This fixes the issue:
    # @args = T.let(kwargs, T::Hash[Symbol, String]) ; @rest = T.let(rest, T::Array[String])

    # this fails:
    @args = kwargs ; @rest = rest
  end

  sig do
    params(arg_name: Symbol).returns(T.nilable(String))
  end
  def retrieve_field(arg_name)
    @args[arg_name]
  end

  sig do
    params(index: Integer).returns(T.nilable(String))
  end
  def retrieve_nth(index)
    @rest[index]
  end
end

def main
  a = A.new("hi", bar: "baz", oink: "hi")
  puts a.retrieve_field(:bar)
  puts a.retrieve_nth(0)
end
```

#### Observed output

```
editor.rb:12: Argument does not have asserted type String https://srb.help/7007
    12 |    @args = kwargs ; @rest = rest
                    ^^^^^^
  Got T::Hash[Symbol, String] originating from:
    editor.rb:7:
     7 |  def initialize(*rest, **kwargs)
                                ^^^^^^^^

editor.rb:12: Argument does not have asserted type String https://srb.help/7007
    12 |    @args = kwargs ; @rest = rest
                                     ^^^^
  Got T::Array[String] originating from:
    editor.rb:7:
     7 |  def initialize(*rest, **kwargs)
                          ^^^^

editor.rb:19: Expected T.any(T::Range[Integer], Regexp) but found Symbol for argument arg0 https://srb.help/7002
    19 |    @args[arg_name]
            ^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/string.rbi#L264: Method String#[] (overload.1) has specified arg0 as T.any(T::Range[Integer], Regexp)
     264 |        arg0: T.any(T::Range[Integer], Regexp),
                  ^^^^
  Got Symbol originating from:
    editor.rb:18:
    18 |  def retrieve_field(arg_name)
                             ^^^^^^^^
Errors: 3
```

#### Expected behavior

I was expecting the `kwargs`'s and `rest`'s type to specify the type of the elements, not the literal type; that also is what the docs seem to suggest (:

- - -

### PR DESCRIPTION
**Pull request by jez**
### Motivation

Fixes #2756

### Test plan

See included automated tests.

### CODE REVIEW

File: rewriter/Initializer.cc [hunk 1]
```diff
@@ -156,14 +185,26 @@ void Initializer::run(core::MutableContext ctx, ast::MethodDef *methodDef, ast::
...
 
+    UnorderedMap<core::NameRef, ArgKind> argKindMap;
+    for (const auto &arg : methodDef->args) {
+        const auto *restArg = ast::cast_tree<ast::RestArg>(arg);
+        if (restArg == nullptr) {
+            argKindMap[ast::MK::arg2Name(arg)] = ArgKind::Plain;
+        } else if (const auto *kwRestArg = ast::cast_tree<ast::KeywordArg>(restArg->expr)) {
+            argKindMap[ast::MK::arg2Name(arg)] = ArgKind::KeywordRestArg;
+        } else {
+            argKindMap[ast::MK::arg2Name(arg)] = ArgKind::RestArg;
```
Comment (froydnj) [inline rewriter/Initializer.cc:196]: Add an `ENFORCE` here for `restArg->expr` being a plain local (or similar)?

**Review by froydnj — APPROVED** [review]
