### PR TITLE
fix crash in namer when redefining modules as static fields

### LINKED ISSUE #3175: Crash in namer (squashNames)
Here's the stack trace from LLDB:

```
(lldb) thread backtrace
* thread #3, name = 'typecheck', stop reason = EXC_BAD_ACCESS (code=1, address=0x28)
  * frame #0: 0x00000001005660d4 sorbet`sorbet::core::File::isStdlib() const + 4
    frame #1: 0x00000001002d4a26 sorbet`sorbet::definition_validator::ValidateWalk::preTransformMethodDef(sorbet::core::Context, sorbet::ast::TreePtr) + 150
    frame #2: 0x00000001002d2c6b sorbet`sorbet::ast::ShallowMapper<sorbet::definition_validator::ValidateWalk, sorbet::core::Context>::mapMethodDef(sorbet::ast::TreePtr, sorbet::core::Context) + 75
    frame #3: 0x00000001002d2278 sorbet`sorbet::ast::ShallowMapper<sorbet::definition_validator::ValidateWalk, sorbet::core::Context>::mapIt(sorbet::ast::TreePtr, sorbet::core::Context) + 696
    frame #4: 0x00000001002d349b sorbet`sorbet::ast::ShallowMapper<sorbet::definition_validator::ValidateWalk, sorbet::core::Context>::mapClassDef(sorbet::ast::TreePtr, sorbet::core::Context) + 347
    frame #5: 0x00000001002d237c sorbet`sorbet::ast::ShallowMapper<sorbet::definition_validator::ValidateWalk, sorbet::core::Context>::mapIt(sorbet::ast::TreePtr, sorbet::core::Context) + 956
    frame #6: 0x00000001002d2f46 sorbet`sorbet::ast::ShallowMapper<sorbet::definition_validator::ValidateWalk, sorbet::core::Context>::mapInsSeq(sorbet::ast::TreePtr, sorbet::core::Context) + 182
    frame #7: 0x00000001002d22d0 sorbet`sorbet::ast::ShallowMapper<sorbet::definition_validator::ValidateWalk, sorbet::core::Context>::mapIt(sorbet::ast::TreePtr, sorbet::core::Context) + 784
    frame #8: 0x00000001002d349b sorbet`sorbet::ast::ShallowMapper<sorbet::definition_validator::ValidateWalk, sorbet::core::Context>::mapClassDef(sorbet::ast::TreePtr, sorbet::core::Context) + 347
    frame #9: 0x00000001002d237c sorbet`sorbet::ast::ShallowMapper<sorbet::definition_validator::ValidateWalk, sorbet::core::Context>::mapIt(sorbet::ast::TreePtr, sorbet::core::Context) + 956
    frame #10: 0x00000001002d2f46 sorbet`sorbet::ast::ShallowMapper<sorbet::definition_validator::ValidateWalk, sorbet::core::Context>::mapInsSeq(sorbet::ast::TreePtr, sorbet::core::Context) + 182
    frame #11: 0x00000001002d22d0 sorbet`sorbet::ast::ShallowMapper<sorbet::definition_validator::ValidateWalk, sorbet::core::Context>::mapIt(sorbet::ast::TreePtr, sorbet::core::Context) + 784
    frame #12: 0x00000001002d164c sorbet`sorbet::ast::TreePtr sorbet::ast::ShallowMap::apply<sorbet::core::Context, sorbet::definition_validator::ValidateWalk>(sorbet::core::Context, sorbet::definition_validator::ValidateWalk&, sorbet::ast::TreePtr) + 76
    frame #13: 0x00000001002d141b sorbet`sorbet::definition_validator::runOne(sorbet::core::Context, sorbet::ast::ParsedFile) + 155
    frame #14: 0x0000000100147239 sorbet`sorbet::realmain::pipeline::typecheckOne(sorbet::core::Context, sorbet::ast::ParsedFile, sorbet::realmain::options::Options const&) + 169
    frame #15: 0x000000010015de8b sorbet`std::__1::__function::__func<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&, bool, std::__1::optional<std::__1::shared_ptr<sorbet::core::lsp::PreemptionTaskManager> >)::$_4, std::__1::allocator<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&, bool, std::__1::optional<std::__1::shared_ptr<sorbet::core::lsp::PreemptionTaskManager> >)::$_4>, void ()>::operator()() + 443
    frame #16: 0x00000001005e8b85 sorbet`std::__1::__function::__func<sorbet::WorkerPoolImpl::multiplexJob(std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::function<void ()>)::$_2, std::__1::allocator<sorbet::WorkerPoolImpl::multiplexJob(std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::function<void ()>)::$_2>, bool ()>::operator()() + 37
    frame #17: 0x00000001005e815a sorbet`std::__1::__function::__func<sorbet::WorkerPoolImpl::WorkerPoolImpl(int, spdlog::logger&)::$_0, std::__1::allocator<sorbet::WorkerPoolImpl::WorkerPoolImpl(int, spdlog::logger&)::$_0>, void ()>::operator()() + 314
    frame #18: 0x00000001005e9954 sorbet`Joinable::trampoline(void*) + 68
    frame #19: 0x00007fff6d97a109 libsystem_pthread.dylib`_pthread_start + 148
    frame #20: 0x00007fff6d975b8b libsystem_pthread.dylib`thread_start + 15
```

### PR DESCRIPTION
**Pull request by froydnj**
In the example test cases, we would enter `A::B` into the symbol table as a static field.  But the name lookup during the symbol definition phase would find that static field when it was expecting to find a class/module, and problems would ensue.

Instead of indiscriminately looking for a matching symbol, we need to consider the context in which `squashNames` is being called, looking up classes or (dealiased) static fields as appropriate.

### Motivation

Fixes #3175.

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by froydnj** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_IHv9fKQicAsL6v

File: test/testdata/namer/constant_redefinition/nested_module_then_nonexistent_name.rb [hunk 1]
```diff
@@ -0,0 +1,9 @@
+# typed: true
+
+module A::B::C
+  def foo; end
+end
+
+  A::B = A::D
+# ^^^^^^^^^^^ error: Redefining constant `B`
+       # ^^^^ error: Unable to resolve constant `D`
```
Comment (jez) [inline test/testdata/namer/constant_redefinition/nested_module_then_nonexistent_name.rb:9]: What do you think about adding something to the output of `ast::ConstantLit::showRaw` to add a field like `symbol-kind` to pretty print the symbol's kind?

Because I believe that this change also fixes the bug where we were symbolizing the trees wrong, and it'd be nice to not regress on that.

**Review by jez — APPROVED** [review]
One suggestion for how we can better test the other thing that's fixed in this PR.

**Comment by froydnj** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_IHvoGICnJ9A1fz

File: test/testdata/namer/constant_redefinition/nested_module_then_nonexistent_name.rb (hunk 1 above)
Comment (froydnj) [reply test/testdata/namer/constant_redefinition/nested_module_then_nonexistent_name.rb:9]: Discussion elsewhere says we can delay this for a followup.
