### PR TITLE
Fix a crash with duplicate keyword arguments

### LINKED ISSUE #7969: Crash if field is defined twice from duplicate parameter
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7B%20params%28x%3A%20Integer%2C%20x%3A%20String%29.void%20%7D%0A%20%20def%20initialize%28x%3A%2C%20x%3A%20nil%29%0A%20%20%20%20%40x%20%3D%20T.let%28x%2C%20T.nilable%28String%29%29%0A%20%20%20%20%40x%20%3D%20T.let%28x%2C%20T.nilable%28String%29%29%0A%20%20end%0Aend%0A)

```ruby
# typed: strict

class A
  extend T::Sig
  sig { params(x: Integer, x: String).void }
  def initialize(x:, x: nil)
    @x = T.let(x, T.nilable(String))
    @x = T.let(x, T.nilable(String))
  end
end

```

#### Observed output

```
msg="Bad core::Types::equiv in resolveField" path="-e" priorField="<no-field-or-static-field>" resultTypeNull="true" castTypeNull="false"
source="# typed: strict\n\nclass A\n  extend T::Sig\n  sig { params(x: Integer, x: String).void }\n  def initialize(x:, x: nil)\n    @x = T.let(x, T.nilable(String))\n    @x = T.let(x, T.nilable(String))\n  end\nend\n\n"
Exception::raise(): isSubTypeUnderConstraint(, ClassType): unreachable

???: Exception resolving (backtrace is above) https://srb.help/1001

editor.rb:6: duplicate argument name x https://srb.help/2001
     6 |  def initialize(x:, x: nil)
                             ^^^^^^

editor.rb:5: Hash key x is duplicated https://srb.help/3011
     5 |  sig { params(x: Integer, x: String).void }
                                   ^
    editor.rb:5: First occurrence of x hash key
     5 |  sig { params(x: Integer, x: String).void }
                       ^
Errors: 3
```

#### Expected behavior

Sorbet should not crash.

- - -

While this example seems contrived, it comes up somewhat naturally if you accidentally define a prop twice in a `T::Struct`:

```ruby
# typed: strict

class A < T::Struct
  const :foo, Integer
  const :foo, T.nilable(String)
end
```

### LINKED ISSUE #8194: Crash with duplicate keyword arg, once required, once optional
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Adef%20foo%28x%3A%2C%20x%3A%200%29%0Aend)

```ruby
# typed: strict

def foo(x:, x: 0)
end
```

#### Observed output

This fails with an exception in release builds:

```
Exception::raise(): method has no locs! ctx.file="-e" method="<no-method>"

Exception typing file: -e (backtrace is above)
editor.rb:3: Failed to process tree (backtrace is above) https://srb.help/1001
     3 |def foo(x:, x: 0)
     4 |end

editor.rb:3: duplicate argument name x https://srb.help/2001
     3 |def foo(x:, x: 0)
                    ^^^^
Errors: 2
```

It fails with an `ENFORCE` failure earlier than that in debug builds:

```
❯ sorbet crash.rb
Exception::raise(): namer/namer.cc:1058 enforced condition ctx.state.lookupMethodSymbolWithHash(owner, method.name, method.arityHash).exists() has failed: (no message provided)

Backtrace:
0x00000001046bd090 (in sorbet)
0x00000001050c7c9c (in sorbet)
0x00000001050c38cc (in sorbet)
0x00000001050a4a30 (in sorbet)
0x000000010507b500 (in sorbet)
0x000000010507a8b0 (in sorbet)
0x000000010507ba34 (in sorbet)
0x0000000104adf5ac (in sorbet)
0x00000001046b7dcc (in sorbet)
0x00000001046b1b4c (in sorbet)
start (in dyld) + 2840

???: Exception naming (backtrace is above) https://srb.help/1001
```

```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=1, subcode=0x10129f3dc)
  * frame #0: 0x000000010129f3e0 sorbet`stopInDebugger() at mac.cc:72:9
    frame #1: 0x0000000100a17bd0 sorbet`sorbet::namer::(anonymous namespace)::SymbolDefiner::defineMethod(this=0x000000016fdf8d28, ctx=MutableContext @ 0x000000016fdf8968, method=0x0000600000477f00) at namer.cc:1058:9
    frame #2: 0x0000000100a138cc sorbet`sorbet::namer::(anonymous namespace)::SymbolDefiner::insertMethod(this=0x000000016fdf8d28, ctx=MutableContext @ 0x000000016fdf8ad8, method=0x0000600000477f00) at namer.cc:1063:23
    frame #3: 0x00000001009f4a30 sorbet`sorbet::namer::(anonymous namespace)::SymbolDefiner::enterNewDefinitions(this=0x000000016fdf8d28, ctx=MutableContext @ 0x000000016fdf8d18, state=0x0000600000477e20) at namer.cc:1728:13
    frame #4: 0x00000001009cb500 sorbet`sorbet::namer::(anonymous namespace)::defineSymbols(gs=0x0000000143813200, allFoundDefinitions=size=1, workers=0x0000600003250d20, oldFoundHashesForFiles=0x000000016fdf9348, foundHashesOut=0x0000000000000000) at namer.cc:2353:23
    frame #5: 0x00000001009ca8b0 sorbet`sorbet::namer::Namer::runInternal(gs=0x0000000143813200, trees=Span<sorbet::ast::ParsedFile> @ 0x000000016fdf92d8, workers=0x0000600003250d20, oldFoundHashesForFiles=0x000000016fdf9348, foundHashesOut=0x0000000000000000) at namer.cc:2408:5
    frame #6: 0x00000001009cba34 sorbet`sorbet::namer::Namer::run(gs=0x0000000143813200, trees=Span<sorbet::ast::ParsedFile> @ 0x000000016fdf9380, workers=0x0000600003250d20, foundHashesOut=0x0000000000000000) at namer.cc:2421:12
    frame #7: 0x000000010042f5ac sorbet`sorbet::realmain::pipeline::name(gs=0x0000000143813200, what=Span<sorbet::ast::ParsedFile> @ 0x000000016fdf95b8, opts=0x000000016fdfc210, workers=0x0000600003250d20, foundHashes=0x0000000000000000) at pipeline.cc:782:20
    frame #8: 0x0000000100007dcc sorbet`sorbet::realmain::realmain(argc=2, argv=0x000000016fdfd8b0) at realmain.cc:775:17
    frame #9: 0x0000000100001b4c sorbet`main(argc=2, argv=0x000000016fdfd8b0) at main.cc:6:16
    frame #10: 0x000000018e153274 dyld`start + 2840
```

#### Expected behavior

- - -

### PR DESCRIPTION
**Pull request by elliottt**
Instead of mangling duplicated keyword arguments in the namer, which introduces
the possibility that the argument hash will differ later on, eagerly mangle
duplicate keyword args in the parser. This gives us a more consistent tree for
the rest of the pipeline, avoiding the situation where the argument hashes can
get out of sync.

### Motivation
Fixes #8194
Fixes #7969

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
> Fixes #7969

For my own peace of mind: can you add the test case from this issue as well?

File: parser/Builder.cc [hunk 1]
```diff
@@ -1742,7 +1742,10 @@ class Builder::Impl {
     }
 
     void checkDuplicateArgs(sorbet::parser::NodeVec &args, UnorderedMap<core::NameRef, core::LocOffsets> &map) {
+        int pos = -1;
         for (auto &this_arg : args) {
+            ++pos;
```
Comment (jez) [inline parser/Builder.cc:1747]: This is the real reason why I want the ranges library.

File: parser/Builder.cc [hunk 2]
```diff
@@ -1752,9 +1755,13 @@ class Builder::Impl {
             } else if (auto *blockarg = parser::cast_node<Blockarg>(this_arg.get())) {
                 checkDuplicateArg(blockarg->name, blockarg->loc, map);
             } else if (auto *kwarg = parser::cast_node<Kwarg>(this_arg.get())) {
-                checkDuplicateArg(kwarg->name, kwarg->loc, map);
+                if (checkDuplicateArg(kwarg->name, kwarg->loc, map)) {
+                    kwarg->name = gs_.freshNameUnique(core::UniqueNameKind::MangledKeywordArg, kwarg->name, pos);
+                }
```
Comment (jez) [inline parser/Builder.cc:1760]: What do you think about assigning the `checkDuplicateArg` result into a variable so that we can name it?

Right now, `if (checkDuplicateArg)` is kind of ambiguous ("I checked it, and it checks out, so return true" vs "I checked it and it produced an error, so return true").
```suggestion
                auto foundDuplicate = checkDuplicateArg(kwarg->name, kwarg->loc, map);
                if (foundDuplicate) {
                    kwarg->name = gs_.freshNameUnique(core::UniqueNameKind::MangledKeywordArg, kwarg->name, pos);
                }
```

File: parser/Builder.cc [hunk 3]
```diff
@@ -1752,9 +1755,13 @@ class Builder::Impl {
...
             } else if (auto *kwoptarg = parser::cast_node<Kwoptarg>(this_arg.get())) {
-                checkDuplicateArg(kwoptarg->name, kwoptarg->loc, map);
+                if (checkDuplicateArg(kwoptarg->name, kwoptarg->loc, map)) {
+                    kwoptarg->name = gs_.freshNameUnique(core::UniqueNameKind::MangledKeywordArg, kwoptarg->name, pos);
+                }
```
Comment (jez) [inline parser/Builder.cc:1764]:
```suggestion
                auto foundDuplicate = checkDuplicateArg(kwoptarg->name, kwoptarg->loc, map);
                if (foundDuplicate) {
                    kwoptarg->name = gs_.freshNameUnique(core::UniqueNameKind::MangledKeywordArg, kwoptarg->name, pos);
                }
```

File: parser/Builder.cc [hunk 4]
```diff
@@ -1765,18 +1772,22 @@ class Builder::Impl {
...
 
         if (that_arg_loc_it == map.end()) {
             map[this_name] = this_loc;
-            return;
+            return false;
         }
 
-        if (argNameCollides(this_name)) {
+        // Only report an error if this name doesn't start with an `_`, but still report it as being a duplicate of
+        // another argument, for the purpose of mangling.
```
Comment (jez) [inline parser/Builder.cc:1785]:
```suggestion
        // Only report an error if this name doesn't start with an `_`, but still report it as being a duplicate of
        // another argument, for the purpose of mangling. The Ruby VM silences these errors.
```

**Review by jez — APPROVED** [review]

File: parser/Builder.cc (hunk 1 above)
Comment (elliottt) [reply parser/Builder.cc:1747]: Oh me too, `ranges::enumerate` would be so much nicer here.

File: parser/Builder.cc (hunk 2 above)
Comment (elliottt) [reply parser/Builder.cc:1760]: Yeah, that's reasonable. Though, what do you think about renaming it to `hasDuplicateArg` instead?
