### PR TITLE
Fix "missing let" disappearing in LSP

### LINKED ISSUE #1511: Fast path: constants without type annotation errors disappear
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0A%23%20modify%20the%20string%20below%20to%20see%20the%20error%20disappear%0AFoo%20%3D%20%5B%22bar%22%5D%0A)

```ruby
# typed: strict

# modify the string below to see the error disappear
Foo = ["bar"]
```

#### Observed output

error goes away :(

(along with the autocorrects)

#### Expected behavior

error should stay

cc @jvilk-stripe

### PR DESCRIPTION
**Pull request by aisamanra**
### Motivation
Fixes #1511; we would skip reporting certain errors if we had already resolved certain constants, which means we wouldn't report the relevant error in the fast path. This always calls the error-reporting function even in the fast path but doesn't allow it to change state. The changes (which are small) are accompanied by relevant comments.

### Test plan

See included automated tests. Added a relevant test case.

### CODE REVIEW

File: resolver/resolver.cc [hunk 1]
```diff
@@ -1502,6 +1507,10 @@ class ResolveSignaturesWalk {
                                            core::Names::suggestType(), move(rhs));
                 data->resultType = core::Types::untyped(ctx, sym);
             }
+        } else {
+            // we might have already resolved this constant but we want to make sure to still report some errors if
```
Comment (DarkDimius) [inline resolver/resolver.cc]: can we just remove the `&& data->resultType == nullptr` instead?

File: resolver/resolver.cc [hunk 2]
```diff
@@ -1377,6 +1377,11 @@ class ResolveSignaturesWalk {
                         return;
                     }
                 }
+                if (ast::isa_tree<ast::UnresolvedConstantLit>(expr) || ast::isa_tree<ast::ConstantLit>(expr)) {
+                    // we don't want to report an error here because constants that are aliases for other constants can
```
Comment (DarkDimius) [inline resolver/resolver.cc]: I didn't understand this special case.

File: resolver/resolver.cc [hunk 3]
```diff
@@ -1377,6 +1377,11 @@ class ResolveSignaturesWalk {
                         return;
                     }
                 }
+                if (ast::isa_tree<ast::UnresolvedConstantLit>(expr) || ast::isa_tree<ast::ConstantLit>(expr)) {
```
Comment (aisamanra) [inline resolver/resolver.cc]: This makes sure that we don't report the error below for constructs of the form
```
C1 = C2
```
which otherwise would get caught by this case. We previously would not have run this function in such a way that this error would have ever been reported, but because we run this now even if the `resultType` of the constant has already been resolved, we need this check.

Comment (DarkDimius) [reply resolver/resolver.cc]: This is a proper error that we should report reliably instead of silently failing.

Comment (DarkDimius) [reply resolver/resolver.cc]: Said otherwise, we shouldn't do cross-constant resolution as it's order dependent.

File: resolver/resolver.cc (hunk 2 above)
Comment (aisamanra) [reply resolver/resolver.cc]: I was actually in the process of writing an explanation as you were looking at this: https://github.com/sorbet/sorbet/pull/1572#discussion_r313622027

File: resolver/resolver.cc (hunk 1 above)
Comment (aisamanra) [reply resolver/resolver.cc]: That ends up causing other problems, and in particular it "un-does" work that was already done on this constant, possibly setting `data->resultType` to be `T.untyped` when we had determined that it was already something else. This runs in the `postTransformAssign` in the resolve signatures walk, which means that plenty of work has already been done: we don't want to undo that work, but we do want to perform this (largely syntactic) error check.

**Comment by aisamanra** [comment]
The solution here is better, and it solves half the problem but not the other half: specifically, we persist the error after edits, but we don't persist the suggestion at all in the incremental resolver. That appears to a very different part of the code—is it worth splitting it into a different issue?

File: resolver/resolver.cc [hunk 4]
```diff
@@ -1493,14 +1493,18 @@ class ResolveSignaturesWalk {
...
-                data->resultType = core::Types::untyped(ctx, sym);
+                data->resultType = resolveConstantType(ctx, asgn->rhs, sym);
+                if (data->resultType == nullptr) {
+                    auto rhs = move(asgn->rhs);
+                    auto loc = rhs->loc;
+                    asgn->rhs = ast::MK::Send1(loc, ast::MK::Constant(loc, core::Symbols::Magic()),
+                                               core::Names::suggestType(), move(rhs));
+                    data->resultType = core::Types::untyped(ctx, sym);
+                }
+            } else if (!core::isa_type<core::AliasType>(&*data->resultType)) {
```
Comment (DarkDimius) [inline resolver/resolver.cc]:
```suggestion
            } else if (!core::isa_type<core::AliasType>(data->resultType.get())) {
```

Can we leave a comment explaining this branch? It's not intuitive for me

**Comment by DarkDimius** [comment]
This may need modifications to pay-server and opensource. We'll need to communicate with open-source folks about it.

**Comment by aisamanra** [comment]
This didn't introduce any problems with pay-server and open-source has been given a heads-up.
