### PR TITLE
Flow-sensitivity for `Module#<=`

### LINKED ISSUE #2380: Incorrect flow sensitivity behavior when inverting result of Module#<
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20T.class_of(Integer)).void%7D%0A%20%20def%20foo(x)%0A%20%20%20%20T.reveal_type(x)%20unless%20x%20%3C%20Integer%0A%20%20end%0Aend)

```ruby
# typed: true
class A
  extend T::Sig

  sig {params(x: T.class_of(Integer)).void}
  def foo(x)
    T.reveal_type(x) unless x < Integer
  end
end
```

#### Observed output

```
editor.rb:7: This code is unreachable https://srb.help/7006
     7 |    T.reveal_type(x) unless x < Integer
            ^
Errors: 1
```

#### Expected behavior

Revealed type should be `T.class_of(Integer)`, since the code is reachable if `x` is `Integer` (and not a subclass).

### PR DESCRIPTION
**Pull request by jez**
### Motivation

This is a two bird with one stone kind of PR:

- Fixes #2380
- Adds support for `Module#<=` (previously, we only supported `Module#<`)

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_JqVXIaiE9V2Iwc
→ https://go/builds/bui_JqVXtteAo5R1q1

**Review by elliottt — APPROVED** [review]
Nice!

File: test/testdata/infer/is_a_variable.rb [hunk 1]
```diff
@@ -0,0 +1,34 @@
+# typed: true
+extend T::Sig
+
+# At time of writing, this test captures buggy behavior, and is just meant to
+# alert the author if their changes affect this behavior.
+# https://github.com/sorbet/sorbet/issues/4358
```
Comment (jez) [inline test/testdata/infer/is_a_variable.rb:6]: Heads up @elliottt I added some tests to capture the existing behavior and filed a ticket.
