### PR TITLE
Ensure consistency after constant resolution

### LINKED ISSUE #1081: (From Fuzzer) resolver/resolver.cc:1544 enforced condition ResolveConstantsWalk::isAlreadyResolved(ctx, *original) has failed
#### Input

[→ View on sorbet.run](https://sorbet.run/#B%3DT.type_alias)

```ruby
B=T.type_alias
```

#### Observed output

```
Exception::raise(): resolver/resolver.cc:1544 enforced condition ResolveConstantsWalk::isAlreadyResolved(ctx, *original) has failed: (no message provided)

Backtrace:
sorbet::Exception::enforce_handler(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int) (in librealmain.so) (Exception.h:47)
sorbet::resolver::(anonymous namespace)::ResolveSanityCheckWalk::postTransformConstantLit(sorbet::core::MutableContext, std::__1::unique_ptr<sorbet::ast::ConstantLit, std::__1::default_delete<sorbet::ast::ConstantLit> >) (in libresolver.so) (resolver.cc:1544)
sorbet::ast::PostPonePostTransform_ConstantLit<sorbet::resolver::(anonymous namespace)::ResolveSanityCheckWalk, sorbet::core::MutableContext, true>::call(sorbet::core::MutableContext, std::__1::unique_ptr<sorbet::ast::ConstantLit, std::__1::default_delete<sorbet::ast::ConstantLit> >, sorbet::resolver::(anonymous namespace)::ResolveSanityCheckWalk&) (in libresolver.so) (treemap.h:240)
sorbet::ast::TreeMapper<sorbet::resolver::(anonymous namespace)::ResolveSanityCheckWalk, sorbet::core::MutableContext>::mapConstantLit(std::__1::unique_ptr<sorbet::ast::ConstantLit, std::__1::default_delete<sorbet::ast::ConstantLit> >, sorbet::core::MutableContext) (in libresolver.so) (treemap.h:564)
sorbet::ast::TreeMapper<sorbet::resolver::(anonymous namespace)::ResolveSanityCheckWalk, sorbet::core::MutableContext>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::MutableContext) (in libresolver.so) (treemap.h:655)
sorbet::ast::TreeMapper<sorbet::resolver::(anonymous namespace)::ResolveSanityCheckWalk, sorbet::core::MutableContext>::mapAssign(std::__1::unique_ptr<sorbet::ast::Assign, std::__1::default_delete<sorbet::ast::Assign> >, sorbet::core::MutableContext) (in libresolver.so) (treemap.h:474)
sorbet::ast::TreeMapper<sorbet::resolver::(anonymous namespace)::ResolveSanityCheckWalk, sorbet::core::MutableContext>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::MutableContext) (in libresolver.so) (treemap.h:690)
sorbet::ast::TreeMapper<sorbet::resolver::(anonymous namespace)::ResolveSanityCheckWalk, sorbet::core::MutableContext>::mapClassDef(std::__1::unique_ptr<sorbet::ast::ClassDef, std::__1::default_delete<sorbet::ast::ClassDef> >, sorbet::core::MutableContext) (in libresolver.so) (treemap.h:281)
sorbet::ast::TreeMapper<sorbet::resolver::(anonymous namespace)::ResolveSanityCheckWalk, sorbet::core::MutableContext>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::MutableContext) (in libresolver.so) (treemap.h:672)
std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> > sorbet::ast::TreeMap::apply<sorbet::core::MutableContext, sorbet::resolver::(anonymous namespace)::ResolveSanityCheckWalk>(sorbet::core::MutableContext, sorbet::resolver::(anonymous namespace)::ResolveSanityCheckWalk&, std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >) (in libresolver.so) (treemap.h:712)
sorbet::resolver::Resolver::sanityCheck(sorbet::core::MutableContext, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >&) (in libresolver.so) (resolver.cc:1585)
sorbet::resolver::Resolver::run(sorbet::core::MutableContext, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::WorkerPool&) (in libresolver.so) (resolver.cc:1556)
sorbet::realmain::pipeline::resolve(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&, bool) (in libpipeline.so) (pipeline.cc:859)
sorbet::realmain::realmain(int, char**) (in librealmain.so) (realmain.cc:426)
main (in sorbet) (main.cc:7)
start (in libdyld.dylib) + 1

fuzz_crashers/min/crash-3aca069bc1c8b102a3a7baf60642777b16b78a72.done:1: Failed to process tree (backtrace is above) https://srb.help/1001
     1 |B=T.type_alias
        ^

???: Exception resolving (backtrace is above) https://srb.help/1001
Errors: 2
```

#### Expected behavior

Exception does not occur.

### PR DESCRIPTION
**Pull request by aisamanra**
### Motivation
Fixes #1081; treats a no-argument `type_alias` differently by synthesizing a fake `T.untyped` as argument and reporting the invalid use of `type_alias` immediately, which avoids issues we had before where our sanity checks would fail post-constant-resolution. This changes some error messages slightly, but in what I think is a clearer way.

### Test plan
See included automated tests. Fuzzed test from #1081 was added, as well.

### CODE REVIEW

File: resolver/resolver.cc [hunk 1]
```diff
@@ -527,7 +527,20 @@ class ResolveConstantsWalk {
         }
 
         auto *send = ast::cast_tree<ast::Send>(asgn->rhs.get());
-        if (send != nullptr && send->fun == core::Names::typeAlias() && send->args.size() == 1) {
+        if (send != nullptr && send->fun == core::Names::typeAlias()) {
+            if (send->args.size() == 0) {
```
Comment (elliottt) [inline resolver/resolver.cc]: It looks like this case is a problem too:
```
B = T.type_alias(String,Integer)
```
Should you check for `size() != 1` instead?

Comment (aisamanra) [reply resolver/resolver.cc]: I think that's a question of what the behavior and error messages should look like. With the way this PR is currently written, that case is handled mostly fine, albeit with slightly different semantics and error messages. In particular, regardless of the `size()` of the arg list, it'll use the first argument to `type_alias` as the actual type alias for the purposes of constant resolution, which means in the above case it'll treat it as though we wrote `B = T.type_alias(String)`. Later on—during inference—we'll raise an error because `T.type_alias(String, Integer)` doesn't match the expected arity. So running my branch on that program currently produces the non-`ENFORCE`-ey output
```
/Users/gdritter/stripe/sorbet/samp.rb:2: Too many arguments provided for method T.type_alias. Expected: 1, got: 2 https://srb.help/7004
     2 |B = T.type_alias(Integer, String)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/sorbet/t.rbi#L58: type_alias defined here
    58 |  def self.type_alias(type);
```
However, I can imagine an argument that I should check for `size() != 1` and in that case clear out the arguments to `T.type_alias` before producing a synthetic `untyped`. In that case, we'd be treating `T.type_alias(T1, T2, ...)` as though the user wrote `T.type_alias(T.untyped)` and then we could emit a custom error message here in the resolver that's not just the usual mismatched-arity message. I can see arguments both ways! Do you have a feeling one way or another?

Comment (elliottt) [reply resolver/resolver.cc]: On master, the example with multiple arguments was raising an exception, so if it's producing an error now that's much better. I also like that it's just giving an error about the arity of `T.type_alias` now. Thanks!
