### PR TITLE
Fix fuzz bug with `exists()`

### LINKED ISSUE #1389: (From Fuzzer) Exception::raise(): core/Symbols.cc:119 enforced condition this->exists() has failed
#### Input

[→ View on sorbet.run](https://sorbet.run/#abstract%21%0A%20describe%20e%20do%0Aend)

```ruby
abstract!
 describe e do
end
```

#### Observed output

```
Exception::raise(): core/Symbols.cc:119 enforced condition this->exists() has failed: (no message provided)

Backtrace:
sorbet::Exception::enforce_handler(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int) (in librealmain.so) + 106
sorbet::core::SymbolRef::data(sorbet::core::GlobalState const&) const (in libcore.so) (Symbols.cc:119)
sorbet::definition_validator::ValidateWalk::getAbstractMethods(sorbet::core::GlobalState const&, sorbet::core::SymbolRef) (in libdefinition_validator.so) (validator.cc:293)
sorbet::definition_validator::ValidateWalk::getAbstractMethods(sorbet::core::GlobalState const&, sorbet::core::SymbolRef) (in libdefinition_validator.so) (validator.cc:278)
sorbet::definition_validator::ValidateWalk::validateAbstract(sorbet::core::GlobalState const&, sorbet::core::SymbolRef) (in libdefinition_validator.so) (validator.cc:331)
sorbet::definition_validator::ValidateWalk::preTransformClassDef(sorbet::core::Context, std::__1::unique_ptr<sorbet::ast::ClassDef, std::__1::default_delete<sorbet::ast::ClassDef> >) (in libdefinition_validator.so) (validator.cc:357)
sorbet::ast::PostPonePreTransform_ClassDef<sorbet::definition_validator::ValidateWalk, sorbet::core::Context, true>::call(sorbet::core::Context, std::__1::unique_ptr<sorbet::ast::ClassDef, std::__1::default_delete<sorbet::ast::ClassDef> >, sorbet::definition_validator::ValidateWalk&) (in libdefinition_validator.so) (treemap.h:203)
sorbet::ast::TreeMapper<sorbet::definition_validator::ValidateWalk, sorbet::core::Context>::mapClassDef(std::__1::unique_ptr<sorbet::ast::ClassDef, std::__1::default_delete<sorbet::ast::ClassDef> >, sorbet::core::Context) (in libdefinition_validator.so) (treemap.h:274)
sorbet::ast::TreeMapper<sorbet::definition_validator::ValidateWalk, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in libdefinition_validator.so) (treemap.h:672)
sorbet::ast::TreeMapper<sorbet::definition_validator::ValidateWalk, sorbet::core::Context>::mapInsSeq(std::__1::unique_ptr<sorbet::ast::InsSeq, std::__1::default_delete<sorbet::ast::InsSeq> >, sorbet::core::Context) (in libdefinition_validator.so) (treemap.h:601)
sorbet::ast::TreeMapper<sorbet::definition_validator::ValidateWalk, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in libdefinition_validator.so) (treemap.h:668)
sorbet::ast::TreeMapper<sorbet::definition_validator::ValidateWalk, sorbet::core::Context>::mapClassDef(std::__1::unique_ptr<sorbet::ast::ClassDef, std::__1::default_delete<sorbet::ast::ClassDef> >, sorbet::core::Context) (in libdefinition_validator.so) (treemap.h:281)
sorbet::ast::TreeMapper<sorbet::definition_validator::ValidateWalk, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in libdefinition_validator.so) (treemap.h:672)
std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> > sorbet::ast::TreeMap::apply<sorbet::core::Context, sorbet::definition_validator::ValidateWalk>(sorbet::core::Context, sorbet::definition_validator::ValidateWalk&, std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >) (in libdefinition_validator.so) (treemap.h:712)
sorbet::definition_validator::runOne(sorbet::core::Context, sorbet::ast::ParsedFile) (in libdefinition_validator.so) (validator.cc:385)
sorbet::realmain::pipeline::typecheckOne(sorbet::core::Context, sorbet::ast::ParsedFile, sorbet::realmain::options::Options const&) (in libpipeline.so) (pipeline.cc:677)
sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3::operator()() const (in libpipeline.so) (pipeline.cc:949)
decltype(std::__1::forward<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&>(fp)()) std::__1::__invoke<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&>(sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&&&) (in libpipeline.so) (type_traits:4353)
std::__1::__function::__value_func<void ()>::operator()() const (in libconcurrency.so) + 53
std::__1::function<void ()>::operator()() const (in libconcurrency.so) + 21
sorbet::WorkerPoolImpl::multiplexJob(std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::function<void ()>) (in libconcurrency.so) + 275
sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&) (in libpipeline.so) (pipeline.cc:938)
sorbet::realmain::realmain(int, char**) (in librealmain.so) + 8004
main (in sorbet) (main.cc:7)
start (in libdyld.dylib) + 1
0x00000003 (in sorbet)

Exception typing file: /Users/jvilk/stripe/sorbet/fuzz_crashers/min/crash-4e06d7894226699d294de9a1ae25b790223e1838.done (backtrace is above)
/Users/jvilk/stripe/sorbet/fuzz_crashers/min/crash-4e06d7894226699d294de9a1ae25b790223e1838.done:2: Failed to process tree (backtrace is above) https://srb.help/1001
     2 | describe e do
     3 |end
Errors: 1
```

#### Expected behavior

Exception does not occur.

### PR DESCRIPTION
**Pull request by azdavis**
Close #1389, cc @jvilk-stripe.

In this PR, we:
1. Clean up some misc things (save some lines, etc).
2. Fix a fuzzer bug where we weren't checking for `exists()`.
3. Fix a bug unearthed by fixing that bug where we weren't checking for `std::string::npos`.

For more context on 3:

When a user says `final!` (or other special methods in `T::Helpers`), but they haven't first said `extend T::Helpers`, we create an autocorrect suggestion to first `extend T::Helpers`. To do that, we have to calculate where to put that `extend`. 

It turns out in the edge case where `final!` is the last thing in the file, a call to `find_first_not_of` returns `std::string::npos`, which is `(size_t) -1`. This is a very large number. Because we weren't checking for `npos`, we tried to allocate a very large string of spaces on [this line][1].

[1]: https://github.com/sorbet/sorbet/blob/c298e55573985c42e85270c0be8255e518bb1a4c/core/types/calls.cc#L411

### Motivation
To fix bugs.

### Test plan
No tests yet, but we should be able to copy over the tests from the linked issue.

We also might like to get the `extend T::Helpers` suggestion working a bit better, and add a test to that effect. Right now, if you say `final!` at the top level as in the examples linked in the issue, the `extend T::Helpers` line is put after you and the indentation isn't good.

### CODE REVIEW

File: core/Loc.cc [hunk 1]
```diff
@@ -211,7 +211,10 @@ pair<Loc, u4> Loc::findStartOfLine(const GlobalState &gs) const {
     u4 lineStart = Loc::pos2Offset(this->file().data(gs), {startDetail.line, 1});
     std::string_view lineView = this->file().data(gs).source().substr(lineStart);
 
-    u4 padding = lineView.find_first_not_of(" \t");
+    size_t padding = lineView.find_first_not_of(" \t");
+    if (padding == string::npos) {
+        padding = 0;
```
Comment (DarkDimius) [inline core/Loc.cc]: could you leave a comment on why `0` is the right choice here?
alternatively, If there is no start of the line, maybe this method should return `std::nullopt`?

Comment (azdavis) [reply core/Loc.cc]: I think it makes sense to just set `padding = 0` here (and not return `std::nullopt`). I left a comment.
