### PR TITLE
[static] Check `override` in prop DSL

### LINKED ISSUE #1694: Interface type checking does not work with T::Struct
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Amodule%20MyInterface%0A%20%20include%20Kernel%0A%20%20extend%20T%3A%3AHelpers%0A%20%20extend%20T%3A%3ASig%0A%20%20interface!%20%20%0A%0A%20%20sig%20%7Babstract.returns(String)%7D%0A%20%20def%20fun%3B%20end%0Aend%0A%0Aclass%20A%20<%20T%3A%3AStruct%0A%20%20include%20MyInterface%0A%0A%20%20prop%20%3Afun%2C%20T%3A%3ABoolean%20%23%20should%20not%20type%20check!%0Aend%0A)

```ruby
# typed: strict

module MyInterface
  include Kernel
  extend T::Helpers
  extend T::Sig
  interface!  

  sig {abstract.returns(String)}
  def fun; end
end

class A < T::Struct
  include MyInterface

  prop :fun, T::Boolean # should not type check!
end

```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

It should print

```
Return type T::Boolean does not match return type of abstract method MyInterface#fun
```

- - -

Right now, interface and override checking will ignore DSL-generated methods because otherwise they would produce a number of errors that would make them unusable in practice. (For example, if you can't explicitly write a `sig` on a DSL-generated method, then you also can't explicitly write an `implementation` in that sig, but we demand that `implementation` appear explicitly in the types of things which implement abstract methods!) That however also means we miss out on useful error messages, like the one desired above.

### PR DESCRIPTION
**Pull request by CT075**
### Motivation

This primarily fixes #1694 by unmarking prop-generated methods as rewriter-synthesized, as well as expanding the `override` DSL to allow selective overrides of reader and writer.

### Test plan

See included automated tests.

### CODE REVIEW

File: core/errors/rewriter.h [hunk 1]
```diff
@@ -30,6 +30,7 @@ constexpr ErrorClass RBSMultilineMisformatted{3555, StrictLevel::False};
 constexpr ErrorClass RBSIncorrectParameterKind{3556, StrictLevel::False};
 constexpr ErrorClass RBSMultipleGenericSignatures{3557, StrictLevel::False};
 constexpr ErrorClass RBSAbstractMethodNoRaises{3558, StrictLevel::False};
+constexpr ErrorClass PropBadOverride{3559, StrictLevel::False};
```
Comment (jez) [inline core/errors/rewriter.h]: The comment above mentions that we wanted to reserve these error codes for RBS-related errors.

Let's number this 3516 and move it earlier in the file.

File: rewriter/util/Util.cc
Comment (jez) [inline rewriter/util/Util.cc:1]: 🎉

**Comment by CT075** [comment]
(Marking as draft because I just realized that the autocorrect doesn't even come close to working)

File: rewriter/Prop.cc [hunk 2]
```diff
@@ -103,6 +107,66 @@ struct NodesAndPropInfo {
     PropInfo propInfo;
 };
 
+void emitBadOverride(core::MutableContext ctx, const core::LocOffsets loc) {
+    if (auto e = ctx.beginIndexerError(loc, core::errors::Rewriter::PropBadOverride)) {
+        e.setHeader("Bad prop override");
```
Comment (jez) [inline rewriter/Prop.cc]: Minor stylistic things about error messages:

- I try to have at least one interpolated string in the error message
- It's nice to mention things that jog the users memory of the problem when they see the error message. If they've got a file with 20 props, showing the prop name will make it easier for them to know where the problem is
- Stylistically, we might want to model this like other type syntax errors. Most of the errors in `type_syntax.cc` use `Malformed sig: ...` as the pattern. Maybe we could use ``Malformed `{}` for prop `{}`:`` or something like "Unexpected expression passed to override in prop" or something. (Even though the errorNote has more details, most users in the IDE only see the header. For example, we sometimes recommend people use the Error Lens VS Code extension (like in this screenshot https://sorbet.org/docs/highlight-untyped) and for that use case, it's better if the header is information-dense.)

File: website/docs/tstruct.md
Comment (jez) [inline website/docs/tstruct.md:1]: Nice find.

We'll probably also need to document the full syntax with a new prop-specific section of override-checking.md

File: rewriter/Prop.cc [hunk 3]
```diff
@@ -335,23 +448,60 @@ optional<PropInfo> parseProp(core::MutableContext ctx, const ast::Send *send) {
     return ret;
 }
 
-vector<ast::ExpressionPtr> processProp(core::MutableContext ctx, PropInfo &ret, PropContext propContext) {
+// cwong: Should we move this to `Helpers.h`?
+ast::ExpressionPtr insertOverride(ast::Send &oldSig, OverrideKind cfg) {
+    auto &oldBody = oldSig.block()->body;
+    auto loc = oldSig.loc;
```
Comment (jez) [inline rewriter/Prop.cc]: We're going to want to think about better locs to use here.

Ideally, each individual node that we have gets a loc that is as close as possible to the piece of syntax in the `prop` definition. e.g., the `override` send is the same as the `override:` keyword, the `allowIncompatible` keyword, the `:visible` Symbol, etc., etc.

One strategy here might be that instead of tracking an `enum class`, we eagerly build up the Expression and store either a `nullptr` or an `ExpressionPtr` on both of `prop.getterOverride` and `prop.setterOverride`. If you then inserted this at the front of the sig, instead of at the end:

```ruby
override(allow_incompatible: true).(...)

# vs

(...).override(allow_incompatible: true)
```

this would allow the ExpressionPtr to be self-contained, and thus just need to be `std::move`'d into the receiver of the existing `sig`.

^ we should probably take that strategy anyways—the current approach essentially re-allocates the sig that we just created, which is a lot of extra allocations to have to immediately throw away.

Comment (jez) [reply rewriter/Prop.cc]: You can look at `test/testdata/lsp/jump_to_def_override.rb` to try to get the locs working. It should be that as long as the locs for the `override` keyword are correct that jump to def on the override will work, at least for the `override: :reader` case (the `override: true` case might also work, but it might show two definitions, instead of one).

While you're writing LSP tests, you might want to write some `# ^ hover ...` tests at various points to see what the hover result is.

Typically, when using `loc` instead of something like `loc.copyWithZeroLength`, that causes problems because the user will be trying to get some piece of information, but the actual LSP query will match in some unrelated, synthetic node. LSP is designed to ignore zero-length locs for the purpose of matching queries.

Basically, for every loc, we want to think about what the actual loc should be.

**Review by jez — COMMENTED** [review]
Sorry I started a review before you converted to draft. Leaving comments.

I think at a high level this looks great, very exciting.

I think you mentioned that building an autocorrect for this was going to be tricky, right? Can't remember.

File: rewriter/Prop.cc (hunk 3 above)
Comment (CT075) [reply rewriter/Prop.cc]: > One strategy here might be that instead of tracking an enum class, we eagerly build up the Expression and store either a nullptr or an ExpressionPtr on both of prop.getterOverride and prop.setterOverride.

This is quite irritating to work with using the `ast::MK` interface. While that's not a complete deal-breaker, I think it might be better to adjust `ast::MK::Sig` to take override params.

Tangential, my original approach used `setBlock` to try to reuse the original allocation but that kept falling afoul of the sanity checker for reasons I couldn't quite pin down.

**Comment by CT075** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_SizBuFsXxwLMNB
→ https://go/builds/bui_SizBDP2QocfnaQ
→ https://go/builds/bui_SizBNhK7NXsh8A

File: rewriter/Prop.cc [hunk 4]
```diff
@@ -335,23 +449,24 @@ optional<PropInfo> parseProp(core::MutableContext ctx, const ast::Send *send) {
...
-    const auto computedByMethodName = ret.computedByMethodName;
-    const auto computedByMethodNameLoc = ret.computedByMethodNameLoc;
+    const auto computedByMethodName = prop.computedByMethodName;
+    const auto computedByMethodNameLoc = prop.computedByMethodNameLoc;
     const auto computedByMethodNameLocZero = computedByMethodNameLoc.copyWithZeroLength();
 
     auto ivarName = name.addAt(ctx);
 
-    nodes.emplace_back(ast::MK::Sig0(loc, ASTUtil::dupType(getType)));
+    auto readerSig = ast::MK::Sig0(loc, ASTUtil::dupType(getType), std::exchange(prop.getterOverride, nullopt));
```
Comment (jez) [inline rewriter/Prop.cc]: What is this `std::exchange` doing? It looks out of place.

File: rewriter/Prop.cc [hunk 5]
```diff
@@ -86,6 +86,8 @@ struct PropContext {
 struct PropInfo {
     core::LocOffsets loc;
     bool isImmutable = false;
+    optional<ast::ExpressionPtr> getterOverride;
+    optional<ast::ExpressionPtr> setterOverride;
```
Comment (jez) [inline rewriter/Prop.cc]: optional pointer is redundant. You can leave these as `ast::ExpressionPtr` and use `nullptr` as the "none" value, which is how all of the other `ast::ExpressionPtr` fields in this `PropInfo` struct work

File: ast/Helpers.h [hunk 6]
```diff
@@ -375,8 +381,32 @@ class MK {
...
+        args.push_back(Symbol(loc, core::Names::allowIncompatible()));
+        args.push_back(True(loc));
+        return Override(loc, std::move(args));
+    }
+
+    static ExpressionPtr OverrideAllowIncompatibleVisibility(core::LocOffsets loc) {
+        Send::ARGS_store args;
+        args.push_back(Symbol(loc, core::Names::allowIncompatible()));
+        args.push_back(Symbol(loc, core::Names::visibility()));
+        return Override(loc, std::move(args));
```
Comment (jez) [inline ast/Helpers.h]: What do you think about coallescing these into a single helper that takes the ExpressionPtr to use for the value?

That way, the `true` or `:visibility` arg could have the same loc as the call site (because the caller would create it). It could even `deepCopy` the value from the caller, instead of needing to create a new one with helpers.

You might want to consider doing the same thing for the loc of the `allow_incompatible:` keyword, or at least take a loc from the call site.

File: rewriter/Prop.cc [hunk 7]
```diff
@@ -326,6 +387,59 @@ optional<PropInfo> parseProp(core::MutableContext ctx, const ast::Send *send) {
...
+                            ret.getterOverride = ast::MK::OverrideAllowIncompatibleTrue(overrideLoc);
+                            ret.setterOverride = ast::MK::OverrideAllowIncompatibleTrue(overrideLoc);
+                        } else if (lit->isFalse(ctx)) {
+                            ret.getterOverride = ast::MK::OverrideStrict(overrideLoc);
+                            ret.setterOverride = ast::MK::OverrideStrict(overrideLoc);
+                        } else if (lit->isSymbol() && lit->asSymbol() == core::Names::visibility()) {
+                            ret.getterOverride = ast::MK::OverrideAllowIncompatibleVisibility(overrideLoc);
+                            ret.setterOverride = ast::MK::OverrideAllowIncompatibleVisibility(overrideLoc);
+                        } else if (auto e = ctx.beginIndexerError(lit->loc, core::errors::Rewriter::PropBadOverride)) {
+                            e.setHeader("Malformed `{}`", "override.allow_incompatible");
```
Comment (jez) [inline rewriter/Prop.cc]:
```suggestion
                            e.setHeader("Malformed `{}`", "allow_incompatible");
```

The user didn't write the string `override.allow_incompatible` so we shouldn't show that in an error message (at the risk of confusing them—maybe they think that the error is because they've typed that somewhere)

File: rewriter/Prop.cc [hunk 8]
```diff
@@ -326,6 +387,59 @@ optional<PropInfo> parseProp(core::MutableContext ctx, const ast::Send *send) {
...
+                            e.addErrorNote("should be `{}` or `{}`", "true", ":visibility");
```
Comment (jez) [inline rewriter/Prop.cc]: Can we put this in the error header, instead of in an error note?

File: rewriter/Prop.cc [hunk 9]
```diff
@@ -326,6 +387,59 @@ optional<PropInfo> parseProp(core::MutableContext ctx, const ast::Send *send) {
...
+                        }
+                    } else if (auto e = ctx.beginIndexerError(allowIncompatArg.loc(),
+                                                              core::errors::Rewriter::PropBadOverride)) {
+                        e.setHeader("Malformed `{}`", "override.allow_incompatible");
+                        e.addErrorNote("should be `{}` or `{}`", "true", ":visibility");
```
Comment (jez) [inline rewriter/Prop.cc]: Ditto

File: rewriter/Prop.cc [hunk 10]
```diff
@@ -103,6 +105,67 @@ struct NodesAndPropInfo {
...
+optional<ast::ExpressionPtr> elaborateOverride(core::MutableContext ctx, core::LocOffsets overrideLoc, ast::Hash &opts,
+                                               core::NameRef key, std::string rendered) {
+    auto [_key, arg] = ASTUtil::extractHashValue(ctx, opts, key);
+    if (auto lit = ast::cast_tree<ast::Literal>(arg)) {
+        if (lit->isTrue(ctx)) {
+            return ast::MK::OverrideStrict(overrideLoc);
+        } else if (lit->isFalse(ctx)) {
+            return nullopt;
+        } else if (auto e = ctx.beginIndexerError(lit->loc, core::errors::Rewriter::PropBadOverride)) {
+            e.setHeader("Malformed `{}`", fmt::format("override.{}", rendered));
```
Comment (jez) [inline rewriter/Prop.cc]: ditto other message about not showing things in the error message that the user didn't write. You could consider something like

```
Malformed override: reader key expects ...
```

or something along those lines

File: rewriter/Prop.cc [hunk 11]
```diff
@@ -103,6 +105,67 @@ struct NodesAndPropInfo {
...
+            e.addErrorNote("should be `{}`, `{}` or `{}`", "true", "{allow_incompatible: :visibility}",
+                           "{allow_incompatible: true}");
```
Comment (jez) [inline rewriter/Prop.cc]: Ditto about not hiding things in errorNotes.

Error notes are usually for long-winded explanations of what's going wrong. For syntactic things like this, we usually put the context directly in the header.

File: website/docs/override-checking.md [hunk 12]
```diff
@@ -299,6 +299,98 @@ end
 
 Compared to `override(allow_incompatible: true)`, this version will still check things like when the parent and child methods have mismatched arities or types—it only silences visibility-related mismatches.
 
+### Overrides and the `prop` DSL
+
+It is possible for a method defined via `prop` or `const` to override a method from a parent module or class. In such cases, pass the `override:` keyword argument:
```
Comment (jez) [inline website/docs/override-checking.md]:
```suggestion
Methods defined via `prop` or `const` (from [`T::Struct`](tstruct.md)) must also declare if they override (or implement) another method. The syntax is special, because `prop` and `const` are not annotated with [`sig`](sigs.md). Use the `override:` keyword argument on a `prop` or `const` definition:
```

File: website/docs/override-checking.md [hunk 13]
```diff
@@ -299,6 +299,98 @@ end
...
+
+```ruby
+module Common
```
Comment (jez) [inline website/docs/override-checking.md]:
```suggestion
module HasFoo
```

I'd love to change the name, the `Common` name in the `tstruct.md` chooses the name `Common` for the interface so that it has the same name as the module that actually contains `prop` definitions common to both structs.

Choosing a name other than `Common` is more like what we would expect people to do when designing an interface.

File: website/docs/override-checking.md [hunk 14]
```diff
@@ -299,6 +299,98 @@ end
...
+
+  prop :foo, String, override: {reader: {allow_incompatible: true}, writer: true}
+end
+```
+
+Note that the previous values we've seen are aliases for the fully-expanded version:
+
+- `true` expands to `{reader: true, writer: true}`.
+- `:reader` and `:writer` expand to `{reader: true}` and `{writer: true}`, respectively.
+- `{allow_incompatible: x}` expands to `{reader: {allow_incompatible: x}, writer: {allow_incompatible: x}}`.
```
Comment (jez) [inline website/docs/override-checking.md]:
```suggestion
| Shorthand                             | is equivalent to:                                                                  |
| ---                                   | ---                                                                                |
| `override: true`                      | `override: {reader: true, writer: true}`                                           |
| `override: :reader`                   | `override: {reader: true}`                                                         |
| `override: :writer`                   | `override: {writer: true}`                                                         |
| `override: {allow_incompatible: ...}` | `override: {reader: {allow_incompatible: ...}, writer: {allow_incompatible: ...}}` |
```

File: website/docs/override-checking.md [hunk 15]
```diff
@@ -299,6 +299,98 @@ end
...
+  interface!
+  sig { abstract.returns(Integer) }
+  def foo; end
+end
+
+class Child < T::Struct
+  include ReaderOnly
+  prop :foo, Integer, override: :reader
+end
+```
```
Comment (jez) [inline website/docs/override-checking.md]: I appreciate that each one of these has a full code block, but I also worry that makes it harder to discover what's available, because there is so much repeated stuff in common, vs the ~few characters that are different between each example. It's hard to skim.

I wonder if we could do any of:

- cut down on the boilerplate, by having the code snippets not repeat the full, standalone example (vs just the relevant parts)
  - possibly requiring the user to click a link like "View full example on sorbet.run" to see a complete standalone example
- tersely describe all the options in a list, table, or single code snippet section, and provide full documentation below.
  - e.g., a single code snippet could have _only_ the `prop` lines, and not the class/abstract method definitions.

File: website/docs/tstruct.md [hunk 16]
```diff
@@ -210,6 +210,65 @@ Unfortunately, this process left warts in the publicly-accessible `T::Struct` AP
...
+  def foo=(arg0); @foo = arg0; end
+
+  sig { params(foo: String).void }
+  def initialize(foo)
+    @foo = foo
+  end
+end
+```
+
+If `foo` or `foo=` overrides an `overridable` or `abstract` method, however (such as in the interface method above), it is necessary to also annotate the generated sigs with `override`. To accomplish this with `prop`, you can pass the `override` keyword argument. In the simplest cases, this will be one of:
```
Comment (jez) [inline website/docs/tstruct.md]: This feels out of place for a section on overrides. I think we could skip straight to something like this:


```suggestion
Methods defined with `prop` or `const` must also annotate the methods they override (just like if the reader and writer methods had been defined as normal `def` methods). Use the `override` keyword argument on a `prop` or `const` to declare the override. In the simplest cases, this will be one of:
```

File: website/docs/tstruct.md [hunk 17]
```diff
@@ -210,6 +210,65 @@ Unfortunately, this process left warts in the publicly-accessible `T::Struct` AP
...
+
+- `override: :reader` (overrides `foo` only)
+- `override: :writer` (overrides `foo=` only)
+- `override: true` (overrides both `foo` and `foo=`).
```
Comment (jez) [inline website/docs/tstruct.md]:
```suggestion
- `..., override: :reader` (only overrides `foo`, the reader method)
- `..., override: :writer` (only overrides `foo=`, the writer method)
- `..., override: true` (overrides both `foo` and `foo=`).
```

File: website/docs/tstruct.md [hunk 18]
```diff
@@ -210,6 +210,65 @@ Unfortunately, this process left warts in the publicly-accessible `T::Struct` AP
...
+
+If more fine-grained control is needed (for example, because the override is [incompatible](https://sorbet.org/docs/override-checking#use-overrideallow_incompatible-true)), `override` also accepts a Hash containing the keys `reader` and `writer`. For example:
```
Comment (jez) [inline website/docs/tstruct.md]:
```suggestion
The `override` keyword also accepts a `Hash` to declare more fine-grained overrides (for example, if an override [incompatibly overrides](https://sorbet.org/docs/override-checking#use-overrideallow_incompatible-true) another method). Use the `reader` and `writer` keys:
```

File: website/docs/tstruct.md [hunk 19]
```diff
@@ -210,6 +210,65 @@ Unfortunately, this process left warts in the publicly-accessible `T::Struct` AP
 
 The remainder of this documentation is presented for completeness. Use the APIs below at your own discretion. Our goal here is simply to outline the potential pitfalls that arise when using them.
 
+## Fine-grained inheritance control with `override`
```
Comment (jez) [inline website/docs/tstruct.md]:
```suggestion
## Fine-grained inheritance control with `override:`
```

File: rewriter/Prop.cc (hunk 4 above)
Comment (CT075) [reply rewriter/Prop.cc]: `Sig0` takes ownership of the node, so we need to move it out of the `propInfo`. I think it's technically safe not to, but I think it's more clear to explicitly replace the reference.

File: test/testdata/rewriter/prop_override.rb
Comment (jez) [inline test/testdata/rewriter/prop_override.rb:1]: Can we commit the `*.autocorrects.exp` file for this test, just to see what (if any) the autocorrects are right now, and be alerted if any passing change happens to make the autocorrects different?

**Comment by CT075** [comment]
@jez Can you take another look? I think I've addressed everything.

File: rewriter/Prop.cc [hunk 20]
```diff
@@ -335,23 +463,24 @@ optional<PropInfo> parseProp(core::MutableContext ctx, const ast::Send *send) {
...
-    const auto computedByMethodName = ret.computedByMethodName;
-    const auto computedByMethodNameLoc = ret.computedByMethodNameLoc;
+    const auto computedByMethodName = prop.computedByMethodName;
+    const auto computedByMethodNameLoc = prop.computedByMethodNameLoc;
     const auto computedByMethodNameLocZero = computedByMethodNameLoc.copyWithZeroLength();
 
     auto ivarName = name.addAt(ctx);
 
-    nodes.emplace_back(ast::MK::Sig0(loc, ASTUtil::dupType(getType)));
+    auto readerSig = ast::MK::Sig0(loc, ASTUtil::dupType(getType), std::exchange(prop.getterOverride, nullptr));
```
Comment (jez) [inline rewriter/Prop.cc]:
```suggestion
    auto readerSig = ast::MK::Sig0(loc, ASTUtil::dupType(getType), move(prop.getterOverride));
```

File: rewriter/Prop.cc [hunk 21]
```diff
@@ -390,14 +519,17 @@ vector<ast::ExpressionPtr> processProp(core::MutableContext ctx, PropInfo &ret,
...
+    if (!prop.isImmutable) {
+        auto setType = ASTUtil::dupType(prop.type);
         ast::Send::ARGS_store sigArgs;
         sigArgs.emplace_back(ast::MK::Symbol(nameLoc, core::Names::arg0()));
         sigArgs.emplace_back(ASTUtil::dupType(setType));
-        nodes.emplace_back(ast::MK::Sig(loc, std::move(sigArgs), ASTUtil::dupType(setType)));
 
-        if (ret.enum_ == nullptr) {
+        auto writerSig = ast::MK::Sig(loc, std::move(sigArgs), ASTUtil::dupType(setType),
+                                      std::exchange(prop.setterOverride, nullptr));
```
Comment (jez) [inline rewriter/Prop.cc]:
```suggestion
        auto writerSig = ast::MK::Sig(loc, std::move(sigArgs), ASTUtil::dupType(setType), move(prop.setterOverride));
```

File: rewriter/Prop.cc [hunk 22]
```diff
@@ -103,6 +105,68 @@ struct NodesAndPropInfo {
...
 
+void emitBadOverride(core::MutableContext ctx, const core::LocOffsets loc, core::NameRef name) {
+    if (auto e = ctx.beginIndexerError(loc, core::errors::Rewriter::PropBadOverride)) {
+        e.setHeader("Malformed `{}` in prop `{}`: valid values are `{}`, `{}`, `{}`, or a hash literal", "override",
+                    name.show(ctx), "true", ":reader", ":writer");
+    }
+}
+
+ast::ExpressionPtr elaborateOverride(core::MutableContext ctx, core::LocOffsets overrideLoc, ast::Hash &opts,
+                                     core::NameRef propName, core::NameRef key, std::string rendered) {
```
Comment (jez) [inline rewriter/Prop.cc]:
```suggestion
                                     core::NameRef propName, core::NameRef key, string_view rendered) {
```

- No need to use `std::` prefix here (stylistic nit)
- We should take by `string_view` to avoid copying by value

File: rewriter/Prop.cc [hunk 23]
```diff
@@ -103,6 +105,68 @@ struct NodesAndPropInfo {
...
+        } else if (auto e = ctx.beginIndexerError(rOpts->loc, core::errors::Rewriter::PropBadOverride)) {
+            e.setHeader("Malformed `{}` in override for prop `{}`: expected `{}`, `{}` or `{}`", rendered,
+                        propName.show(ctx), "true", "{allow_incompatible: :visibility}", "{allow_incompatible: true}");
+        }
+    } else if (arg != nullptr) {
+        if (auto e = ctx.beginIndexerError(arg.loc(), core::errors::Rewriter::PropBadOverride)) {
+            e.setHeader("Malformed `{}` in override for prop `{}`: expected `{}`, `{}` or `{}`", rendered,
+                        propName.show(ctx), "true", "{allow_incompatible: :visibility}", "{allow_incompatible: true}");
+        }
+    }
```
Comment (jez) [inline rewriter/Prop.cc:169]: What cases are in the (omitted) `else` case here? Is it just `arg == nullptr`?

I wonder if it would be better to early exit at the top, next to the `extractHashValue` call if `arg == nullptr`, so that we could add a comment like "key was not present" when we return, and then the current `else if (arg != nullptr)` would just become the catch-all `else`.

This is just an optional suggestion for clarity.

File: rewriter/Prop.cc [hunk 24]
```diff
@@ -326,6 +388,72 @@ optional<PropInfo> parseProp(core::MutableContext ctx, const ast::Send *send) {
...
+                    emitBadOverride(ctx, lit->loc, ret.name);
+                }
+            } else if (auto opts = ast::cast_tree<ast::Hash>(overrideArg)) {
+                auto [allowIncompatKey, allowIncompatArg] =
+                    ASTUtil::extractHashValue(ctx, *opts, core::Names::allowIncompatible());
+                if (allowIncompatArg != nullptr) {
+                    auto allowIncompatLoc = allowIncompatKey.loc();
+                    if (auto lit = ast::cast_tree<ast::Literal>(allowIncompatArg)) {
+                        if (lit->isTrue(ctx)) {
+                            // XXX cwong: Can we share these/are they interned somehow?
```
Comment (jez) [inline rewriter/Prop.cc]: We cannot


```suggestion
```

File: website/docs/override-checking.md
Comment (jez) [inline website/docs/override-checking.md:1]: All of my `website/` comments are marked "resolved" but were not applied.

For suggestions/comments that are resolved but not applied, I would appreciate reasoning why you've decided not to accept them.

**Comment by jez** [comment]
@CT075 This mostly looks good, but I have one suggestion (please remove `exchange`) and would like clarity why some comments were resolved but not accepted.

The implementation itself is fine.

**Comment by CT075** [comment]
> would like clarity why some comments were resolved but not accepted.

gonna be honest, i could have sworn that I clicked accept. best guess is that I went over these at 8am and clicked resolve instead of accept by accident

File: rewriter/Prop.cc (hunk 20 above)
Comment (CT075) [reply rewriter/Prop.cc]: I still don't like using `move` here. It's *probably* safe since we don't use `getterOverride` for anything else, but it leaves `prop` (a reference) in an invalid state (because we've just moved one of its fields). Using `exchange` at least makes it explicit that `prop` no longer owns the node.

File: rewriter/Prop.cc (hunk 23 above)
Comment (CT075) [reply rewriter/Prop.cc:169]: That's definitely better.

**Comment by CT075** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_Sthp7kS0TxPIpx
→ https://go/builds/bui_SthqwsAVEAjw2n
→ https://go/builds/bui_SthqNgWjy6jZYM
