### PR TITLE
Fix fuzzer bug

### LINKED ISSUE #1532: resolver/resolver.cc:856 enforced condition parentType != nullptr has failed
#### Input

```ruby
# typed: true

class Parent
  extend T::Generic
  Elem = 3
end

class Child < Parent
  extend T::Generic
  Elem = type_member
end

```

#### Observed output

enforce

#### Expected behavior

no enforce

### PR DESCRIPTION
**Pull request by azdavis**
Close #1532.

### Motivation
Fix bugs.

### Test plan
See included automated tests.

### CODE REVIEW

File: resolver/resolver.cc [hunk 1]
```diff
@@ -852,8 +852,16 @@ class ResolveTypeParamsWalk {
             core::LambdaParam *parentType = nullptr;
             auto parentMember = data->owner.data(ctx)->superClass().data(ctx)->findMember(ctx, data->name);
             if (parentMember.exists()) {
-                parentType = core::cast_type<core::LambdaParam>(parentMember.data(ctx)->resultType.get());
-                ENFORCE(parentType != nullptr);
+                if (parentMember.data(ctx)->isTypeMember()) {
+                    parentType = core::cast_type<core::LambdaParam>(parentMember.data(ctx)->resultType.get());
+                    ENFORCE(parentType != nullptr);
+                } else {
+                    if (auto e = ctx.state.beginError(send->loc, core::errors::Resolver::InvalidTypeMemberBounds)) {
```
Comment (elliottt) [inline resolver/resolver.cc]: Maybe `ParentTypeBoundsMismatch` instead?

Comment (azdavis) [reply resolver/resolver.cc]: ack, wasn't sure which error to use (probably not worth creating a new error).
