### PR TITLE
Handle sealed classes with one element in Module.===

### LINKED ISSUE #4114: Be smarter about case statements (===) on sealed modules with one element
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20IFoo%0A%20%20extend%20T%3A%3AHelpers%0A%20%20sealed!%0A%0A%20%20class%20A%20%3C%20T%3A%3AStruct%0A%20%20%20%20include%20IFoo%0A%20%20end%0Aend%0A%0Ax%20%3D%20T.let(IFoo%3A%3AA.new%2C%20IFoo)%0A%23%20Sorbet%20has%20enough%20information%20to%20know%20this%20is%20always%20%60TrueClass%60%0AT.reveal_type(IFoo%3A%3AA%20%3D%3D%3D%20x)%0A%0Asig%20%7Bparams(foo%3A%20IFoo).returns(Integer)%7D%0Adef%20foo!(foo)%0A%20%20%23%20This%20case%20is%20exhaustive%0A%20%20res%20%3D%20case%20foo%0A%20%20when%20IFoo%3A%3AA%20then%200%0A%20%20end%0A%0A%20%20res%0Aend)

```ruby
# typed: true
extend T::Sig

module IFoo
  extend T::Helpers
  sealed!

  class A < T::Struct
    include IFoo
  end
end

x = T.let(IFoo::A.new, IFoo)
# Sorbet has enough information to know this is always `TrueClass`
T.reveal_type(IFoo::A === x)

sig {params(foo: IFoo).returns(Integer)}
def foo!(foo)
  # This case is exhaustive
  res = case foo
  when IFoo::A then 0
  end

  res
end
```

#### Observed output

```
editor.rb:24: Expected Integer but found T.nilable(Integer) for method result type https://srb.help/7005
    24 |  res
          ^^^
  Expected Integer for result type of method foo!:
    editor.rb:18:
    18 |def foo!(foo)
        ^^^^^^^^^^^^^
  Got T.nilable(Integer) originating from:
    editor.rb:21:
    21 |  when IFoo::A then 0
                            ^
    editor.rb:18: Possibly uninitialized (NilClass) in:
    18 |def foo!(foo)
        ^^^^^^^^^^^^^

editor.rb:15: Revealed type: T::Boolean https://srb.help/7014
    15 |T.reveal_type(IFoo::A === x)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got T::Boolean originating from:
    editor.rb:15:
    15 |T.reveal_type(IFoo::A === x)
                      ^^^^^^^^^^^^^
Errors: 2
```

#### Expected behavior

The revealed type should be `TrueClass`, and the `T.nilable` error for the method return should not exist.

- - -

If there are two things in the enum, it works, because after the first comparison, we correctly convert the sealed module to a union of subclasses, and drop the type-tested element out of it for all future comparisons:

```ruby
# typed: true
extend T::Sig

module IBar
  extend T::Helpers
  sealed!

  class A < T::Struct
    include IBar
  end
  class B < T::Struct
    include IBar
  end
end

sig {params(x: IBar).void}
def bar!(x)
  case x
  when IBar::A
  else
    T.reveal_type(IBar::B === x) # error: Revealed type: `TrueClass`
  end
end
```

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20IBar%0A%20%20extend%20T%3A%3AHelpers%0A%20%20sealed!%0A%0A%20%20class%20A%20%3C%20T%3A%3AStruct%0A%20%20%20%20include%20IBar%0A%20%20end%0A%20%20class%20B%20%3C%20T%3A%3AStruct%0A%20%20%20%20include%20IBar%0A%20%20end%0Aend%0A%0Asig%20%7Bparams(x%3A%20IBar).void%7D%0Adef%20bar!(x)%0A%20%20case%20x%0A%20%20when%20IBar%3A%3AA%0A%20%20else%0A%20%20%20%20T.reveal_type(IBar%3A%3AB%20%3D%3D%3D%20x)%0A%20%20end%0Aend)

Another weird thing is that you can trick it to convert `IFoo` into `IFoo::A` by doing a comparison with literally anything else, even if it’s _for sure_ not in the type (note the `NilClass` line below):

```ruby
# typed: true
extend T::Sig

module IFoo
  extend T::Helpers
  sealed!

  class A < T::Struct
    include IFoo
  end
end

x = T.let(IFoo::A.new, IFoo)
# Sorbet has enough information to know this is always `TrueClass`
T.reveal_type(IFoo::A === x)

sig {params(foo: IFoo).returns(Integer)}
def foo!(foo)
  # This case is exhaustive
  res = case foo
  when NilClass then raise "never"
  when IFoo::A then 0
  end

  res
end
```

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20IFoo%0A%20%20extend%20T%3A%3AHelpers%0A%20%20sealed!%0A%0A%20%20class%20A%20%3C%20T%3A%3AStruct%0A%20%20%20%20include%20IFoo%0A%20%20end%0Aend%0A%0Ax%20%3D%20T.let(IFoo%3A%3AA.new%2C%20IFoo)%0A%23%20Sorbet%20has%20enough%20information%20to%20know%20this%20is%20always%20%60TrueClass%60%0AT.reveal_type(IFoo%3A%3AA%20%3D%3D%3D%20x)%0A%0Asig%20%7Bparams(foo%3A%20IFoo).returns(Integer)%7D%0Adef%20foo!(foo)%0A%20%20%23%20This%20case%20is%20exhaustive%0A%20%20res%20%3D%20case%20foo%0A%20%20when%20NilClass%20then%20raise%20%22never%22%0A%20%20when%20IFoo%3A%3AA%20then%200%0A%20%20end%0A%0A%20%20res%0Aend)

### PR DESCRIPTION
**Pull request by elliottt**
### Motivation

Fixes #4114

### Test plan

See included automated tests.

### CODE REVIEW

File: core/types/calls.cc [hunk 1]
```diff
@@ -3052,6 +3052,19 @@ class Module_tripleEq : public IntrinsicMethod {
...
+
+        auto rhsSym = Symbols::noClassOrModule();
+        if (isa_type<ClassType>(rhs)) {
+            rhsSym = cast_type_nonnull<ClassType>(rhs).symbol;
+        } else if (auto *app = cast_type<AppliedType>(rhs)) {
+            rhsSym = app->klass;
+        }
+
+        if (rhsSym.exists() && rhsSym.data(gs)->isClassOrModuleSealed() &&
+            rhsSym.data(gs)->sealedLocs(gs).size() == 1) {
```
Comment (jez) [inline core/types/calls.cc:3064]: Is this guaranteed to have the same number of elements as there are sealed subclasses? What if the code is generated by a DSL pass and the locals are not unique? (Idk if this currently happens but it could). I can’t remember whether there’s not a better way to find this size.

Comment (elliottt) [reply core/types/calls.cc]: It was not returning the locations of the subclasses, but instead the locations where it's allowable to subclass the sealed class. I added a helper that answers this question explicitly instead, and a comment on `sealedLocs`.

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_JrKjSsJPkw07TL
→ https://go/builds/bui_JrKj8T9Hlxei3V

File: core/Symbols.cc [hunk 2]
```diff
@@ -1472,6 +1472,7 @@ void Symbol::recordSealedSubclass(MutableContext ctx, ClassOrModuleRef subclass)
     }
 }
 
+// Returns the locations that are allowed to subclass the sealed class.
```
Comment (jez) [inline core/Symbols.cc:1475]: Not sure how much this matters to you, but clangd will show documentation like this on hover if it's in the header instead of the implementation.

File: core/Symbols.cc [hunk 3]
```diff
@@ -1516,6 +1517,27 @@ TypePtr Symbol::sealedSubclassesToUnion(const GlobalState &gs) const {
...
 
+bool Symbol::hasSingleSealedSubclass(const GlobalState &gs) const {
+    ENFORCE(this->isClassOrModuleSealed(), "Class is not marked sealed: {}", ref(gs).show(gs));
+
+    auto sealedSubclasses = this->lookupSingletonClass(gs).data(gs)->findMember(gs, core::Names::sealedSubclasses());
+
+    // When the sealed type is a class, it must also be abstract for there to be a single subclass.
+    if (this->isClassOrModuleClass() && !this->isClassOrModuleAbstract()) {
+        return false;
+    }
```
Comment (jez) [inline core/Symbols.cc:1528]: I think you actually want "either `module` or `abstract!` `class`".

https://github.com/Morriar/sorbet/blob/a76aae203375ff538a9d51e4fa03be587b1316b2/core/types/types.cc#L195-L199

^ Here is the condition we use elsewhere.

Comment (jez) [reply core/Symbols.cc:1528]: (You might want to add a test for this.)

File: core/types/calls.cc [hunk 4]
```diff
@@ -3052,6 +3052,19 @@ class Module_tripleEq : public IntrinsicMethod {
...
         }
+
+        auto rhsSym = Symbols::noClassOrModule();
+        if (isa_type<ClassType>(rhs)) {
+            rhsSym = cast_type_nonnull<ClassType>(rhs).symbol;
+        } else if (auto *app = cast_type<AppliedType>(rhs)) {
+            rhsSym = app->klass;
+        }
+
+        if (rhsSym.exists() && rhsSym.data(gs)->isClassOrModuleSealed() &&
```
Comment (jez) [inline core/types/calls.cc:3063]:
```suggestion
        // If at any point we ever change isSubType to transparently convert between sealed classes and a
        // union of subclasses, this code can go away. It's written like this now to limit the blast
        // radius of allocating large union types.
        if (rhsSym.exists() && rhsSym.data(gs)->isClassOrModuleSealed() &&
```

File: core/Symbols.cc (hunk 3 above)
Comment (jez) [reply core/Symbols.cc:1528]: Ah I see, i misread the condition. I think that the condition in this PR and the condition in the linked snippet are the same, but De Morgan'd

**Review by jez — APPROVED** [review]
Great, thanks!

File: core/Symbols.cc (hunk 2 above)
Comment (elliottt) [reply core/Symbols.cc:1475]: Good point, I'll move it over there.

**Comment by elliottt** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_JrLicosJipZcRG
→ https://go/builds/bui_JrLiUVfuWEXGcD

**Comment by elliottt** [comment]
> We have a policy of testing changes to Sorbet against Stripe's codebase before
> merging them. I've kicked off a test run for the current PR. When the build
> finishes, I'll share with you whether or how it failed. Thanks!
> 
> Stripe employees can see the build results here:
> 
> → https://go/builds/bui_JrLicosJipZcRG
> → https://go/builds/bui_JrLiUVfuWEXGcD

This found a few instances of cases on singleton enums that had `else` branches.

**Comment by elliottt** [comment]
Successful Stripe build: https://go/builds/bui_JreLeflBCep3j5
