### PR TITLE
Fix `Array#flatten` argument handling ENFORCE

### LINKED ISSUE #1128: (From Fuzzer) core/types/calls.cc:1787 enforced condition args.args.empty() has failed: Array#flatten passed too many args: 2
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%20%20%0A%0Axs%20%3D%20T.let(%0A%20%20%5B1%5D%2C%0A%20T%3A%3AArray%5BInp%5D%2C%0A)%0Axs.flatten(trutten%2C%5B%5D)%0Aptthn)

```ruby
# typed: true
  

xs = T.let(
  [1],
 T::Array[Inp],
)
xs.flatten(trutten,[])
ptthn
```

#### Observed output

```
min_crashers/crash-1f4ae1be0742efdd2620a20a8efa37fad2cbcfa6.done:6: Unable to resolve constant Inp https://srb.help/5002
     6 | T::Array[Inp],
                  ^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/io.rbi#L3: Did you mean: IO?
     3 |class IO < Object
        ^^^^^^^^^^^^^^^^^
Exception::raise(): core/types/calls.cc:1787 enforced condition args.args.empty() has failed: Array#flatten passed too many args: 2

Backtrace:
sorbet::core::(anonymous namespace)::Array_flatten::apply(sorbet::core::Context, sorbet::core::DispatchArgs, sorbet::core::Type const*) const (in libcore.so) (calls.cc:1787)
sorbet::core::dispatchCallSymbol(sorbet::core::Context, sorbet::core::DispatchArgs, sorbet::core::Type const*, sorbet::core::SymbolRef, std::__1::vector<sorbet::core::TypePtr, std::__1::allocator<sorbet::core::TypePtr> >&) (in libcore.so) (calls.cc:763)
sorbet::core::AppliedType::dispatchCall(sorbet::core::Context, sorbet::core::DispatchArgs) (in libcore.so) (calls.cc:820)
sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_12::operator()(sorbet::cfg::Send*) const (in libinfer.so) (environment.cc:769)
sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&) (in libinfer.so) (environment.cc:745)
sorbet::infer::Inference::run(sorbet::core::Context, std::__1::unique_ptr<sorbet::cfg::CFG, std::__1::default_delete<sorbet::cfg::CFG> >) (in libinfer.so) (inference.cc:162)
sorbet::realmain::pipeline::CFGCollectorAndTyper::preTransformMethodDef(sorbet::core::Context, std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >) (in libpipeline.so) (pipeline.cc:54)
sorbet::ast::PostPonePreTransform_MethodDef<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context, true>::call(sorbet::core::Context, std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >, sorbet::realmain::pipeline::CFGCollectorAndTyper&) (in libpipeline.so) (treemap.h:204)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapMethodDef(std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:293)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:666)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapClassDef(std::__1::unique_ptr<sorbet::ast::ClassDef, std::__1::default_delete<sorbet::ast::ClassDef> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:281)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:672)
std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> > sorbet::ast::TreeMap::apply<sorbet::core::Context, sorbet::realmain::pipeline::CFGCollectorAndTyper>(sorbet::core::Context, sorbet::realmain::pipeline::CFGCollectorAndTyper&, std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >) (in libpipeline.so) (treemap.h:712)
sorbet::realmain::pipeline::typecheckOne(sorbet::core::Context, sorbet::ast::ParsedFile, sorbet::realmain::options::Options const&) (in libpipeline.so) (pipeline.cc:693)
sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3::operator()() const (in libpipeline.so) (pipeline.cc:938)
decltype(std::__1::forward<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&>(fp)()) std::__1::__invoke<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&>(sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&&&) (in libpipeline.so) (type_traits:4353)
sorbet::WorkerPoolImpl::multiplexJob(std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::function<void ()>) (in libconcurrency.so) (WorkerPoolImpl.cc:0)
sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&) (in libpipeline.so) (pipeline.cc:927)
sorbet::realmain::realmain(int, char**) (in librealmain.so) (realmain.cc:430)
main (in sorbet) (main.cc:7)
start (in libdyld.dylib) + 1
0x00000002 (in sorbet)


min_crashers/crash-1f4ae1be0742efdd2620a20a8efa37fad2cbcfa6.done:8: Failed to type (backtrace is above) https://srb.help/1001
     8 |xs.flatten(trutten,[])
        ^^^^^^^^^^^^^^^^^^^^^^

min_crashers/crash-1f4ae1be0742efdd2620a20a8efa37fad2cbcfa6.done:4: Failed to process tree (backtrace is above) https://srb.help/1001
     4 |xs = T.let(
     5 |  [1],
     6 | T::Array[Inp],
     7 |)
     8 |xs.flatten(trutten,[])
     9 |ptthn

min_crashers/crash-1f4ae1be0742efdd2620a20a8efa37fad2cbcfa6.done:8: Method trutten does not exist on T.class_of(<root>) https://srb.help/7003
     8 |xs.flatten(trutten,[])
                   ^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/kernel.rbi#L422: Did you mean: Kernel#trust?
     422 |  def trust(); end
            ^^^^^^^^^^^

min_crashers/crash-1f4ae1be0742efdd2620a20a8efa37fad2cbcfa6.done: Exception in cfg+infer: min_crashers/crash-1f4ae1be0742efdd2620a20a8efa37fad2cbcfa6.done (backtrace is above) https://srb.help/1001
Errors: 5
```

#### Expected behavior

Exception does not occur.

### PR DESCRIPTION
**Pull request by aisamanra**
### Motivation
Fixes #1128: we tried to `ENFORCE` something that wasn't an invariant. Specifically, it's totally possible for `IntrinsicMethod::apply` implementations to be passed arguments of an arity and/or type that they don't expect, and they should deal with that gracefully (e.g. [this example from `revealType`](https://github.com/sorbet/sorbet/blob/master/core/types/calls.cc#L982-L984).) The fix is simple—just remove the enforce and exit early; we already have a sig for `Array#flatten` that we can use to raise an error about its arity.

### Test plan

See included automated tests. Added a test case that exercises this.

### CODE REVIEW

File: core/types/calls.cc [hunk 1]
```diff
@@ -1804,7 +1804,7 @@ class Array_flatten : public IntrinsicMethod {
                 depth = INT64_MAX;
             }
         } else {
-            ENFORCE(args.args.empty(), "Array#flatten passed too many args: {}", args.args.size());
```
Comment (DarkDimius) [inline core/types/calls.cc]: lets leave a comment here indicating that `calls.cc` is supposed to handle it
