### PR TITLE
Avoid duplicating existing constants

### LINKED ISSUE #1129: (From Fuzzer) Incremental resolver: infer/SigSuggestion.cc:337 enforced condition enclosingClass->isClassLinearizationComputed() has failed: Should have been linearized by resolver
#### Input

<a href="https://sorbet.run/#%23%3A%20Integer).r%23%20typed%3A%20strict%0A%3CM%20%3CU%20slice%3E%20%241%3EA%20%3D%20Stransind%0A%20%20%20%20B%20%3D%20T.let(Foo%3A%3AStruct.new%2C%20Foo%3A%3AStruct)%0A%20%20%20%20va%20c%20%20%20%20%20tDesuga%20%20%20class%20A%20%3C%20Struct%0A%20%20%20def%20bar%3D(arg0)%3B%20arg0%3B%20end%0A%20%20%20%20%20%20%20%20%20ansi%0Aend%0A">→ View on sorbet.run</a>

```ruby
#: Integer).r# typed: strict
<M <U slice> $1>A = Stransind
    B = T.let(Foo::Struct.new, Foo::Struct)
    va c     tDesuga   class A < Struct
   def bar=(arg0); arg0; end
         ansi
end

```

#### Observed output

With `--stress-incremental-resolver`:

```
min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:2: Parse Error: unexpected token: syntax error https://srb.help/2001
     2 |<M <U slice> $1>A = Stransind
        ^

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:2: Parse Error: unexpected token: syntax error https://srb.help/2001
     2 |<M <U slice> $1>A = Stransind
              ^^^^^

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:4: Redefining constant A https://srb.help/4012
     4 |    va c     tDesuga   class A < Struct
     5 |   def bar=(arg0); arg0; end
     6 |         ansi
     7 |end
    min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:2: Previous definition
     2 |<M <U slice> $1>A = Stransind
                        ^

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:2: Unable to resolve constant Stransind https://srb.help/5002
     2 |<M <U slice> $1>A = Stransind
                            ^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/string.rbi#L3: Did you mean: String?
     3 |class String < Object
        ^^^^^^^^^^^^^^^^^^^^^

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:3: Unable to resolve constant Foo https://srb.help/5002
     3 |    B = T.let(Foo::Struct.new, Foo::Struct)
                      ^^^

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:3: Unable to resolve constant Foo https://srb.help/5002
     3 |    B = T.let(Foo::Struct.new, Foo::Struct)
                                       ^^^

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:4: Type Elem declared by parent Struct must be re-declared in A https://srb.help/5036
     4 |    va c     tDesuga   class A < Struct
                               ^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/struct.rbi#L7: Elem declared in parent here
     7 |  Elem = type_member(:out, fixed: T.untyped)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:2: Constants must have type annotations with T.let() when specifying '# typed: strict' https://srb.help/5028
     2 |<M <U slice> $1>A = Stransind
                            ^^^^^^^^^

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:205: Parse Error: unexpected token: syntax error https://srb.help/2001
     205 |<M <U slice> $1>A = Stransind
          ^

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:205: Parse Error: unexpected token: syntax error https://srb.help/2001
     205 |<M <U slice> $1>A = Stransind
                ^^^^^

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:205: Redefining constant A https://srb.help/4012
     205 |<M <U slice> $1>A = Stransind
                          ^^^^^^^^^^^^^
    min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:127: Previous definition
     127 |
     128 |
     129 |
     130 |
     131 |
         |...
     139 |
     140 |
     141 |
     142 |
     143 |

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:207: Redefining constant A https://srb.help/4012
     207 |    va c     tDesuga   class A < Struct
     208 |   def bar=(arg0); arg0; end
     209 |         ansi
     210 |end
    min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:205: Previous definition
     205 |<M <U slice> $1>A = Stransind
                          ^
Exception::raise(): infer/SigSuggestion.cc:337 enforced condition enclosingClass->isClassLinearizationComputed() has failed: Should have been linearized by resolver

Backtrace:
sorbet::infer::(anonymous namespace)::closestOverridenMethod(sorbet::core::Context, sorbet::core::SymbolRef, sorbet::core::NameRef) (in libinfer.so) (SigSuggestion.cc:337)
sorbet::infer::SigSuggestion::maybeSuggestSig(sorbet::core::Context, sorbet::core::ErrorBuilder&, std::__1::unique_ptr<sorbet::cfg::CFG, std::__1::default_delete<sorbet::cfg::CFG> >&, sorbet::core::TypePtr const&, sorbet::core::TypeConstraint&) (in libinfer.so) (SigSuggestion.cc:448)
sorbet::infer::Inference::run(sorbet::core::Context, std::__1::unique_ptr<sorbet::cfg::CFG, std::__1::default_delete<sorbet::cfg::CFG> >) (in libinfer.so) (inference.cc:216)
sorbet::realmain::pipeline::CFGCollectorAndTyper::preTransformMethodDef(sorbet::core::Context, std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >) (in libpipeline.so) (pipeline.cc:54)
sorbet::ast::PostPonePreTransform_MethodDef<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context, true>::call(sorbet::core::Context, std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >, sorbet::realmain::pipeline::CFGCollectorAndTyper&) (in libpipeline.so) (treemap.h:204)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapMethodDef(std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:293)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:666)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapClassDef(std::__1::unique_ptr<sorbet::ast::ClassDef, std::__1::default_delete<sorbet::ast::ClassDef> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:281)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:672)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapInsSeq(std::__1::unique_ptr<sorbet::ast::InsSeq, std::__1::default_delete<sorbet::ast::InsSeq> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:598)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:668)
std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> > sorbet::ast::TreeMap::apply<sorbet::core::Context, sorbet::realmain::pipeline::CFGCollectorAndTyper>(sorbet::core::Context, sorbet::realmain::pipeline::CFGCollectorAndTyper&, std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >) (in libpipeline.so) (treemap.h:712)
sorbet::realmain::pipeline::typecheckOne(sorbet::core::Context, sorbet::ast::ParsedFile, sorbet::realmain::options::Options const&) (in libpipeline.so) (pipeline.cc:693)
sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3::operator()() const (in libpipeline.so) (pipeline.cc:938)
decltype(std::__1::forward<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&>(fp)()) std::__1::__invoke<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&>(sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&&&) (in libpipeline.so) (type_traits:4353)
sorbet::WorkerPoolImpl::multiplexJob(std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::function<void ()>) (in libconcurrency.so) (WorkerPoolImpl.cc:0)
sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&) (in libpipeline.so) (pipeline.cc:927)
sorbet::realmain::realmain(int, char**) (in librealmain.so) (realmain.cc:430)
main (in sorbet) (main.cc:7)
start (in libdyld.dylib) + 1


min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:208: Failed to process tree (backtrace is above) https://srb.help/1001
     208 |   def bar=(arg0); arg0; end
             ^^^^^^^^^^^^^^^^^^^^^^^^^

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:205: Unable to resolve constant Stransind https://srb.help/5002
     205 |<M <U slice> $1>A = Stransind
                              ^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/string.rbi#L3: Did you mean: String?
     3 |class String < Object
        ^^^^^^^^^^^^^^^^^^^^^

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:206: Unable to resolve constant Foo https://srb.help/5002
     206 |    B = T.let(Foo::Struct.new, Foo::Struct)
                        ^^^

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:206: Unable to resolve constant Foo https://srb.help/5002
     206 |    B = T.let(Foo::Struct.new, Foo::Struct)
                                         ^^^

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:205: Constants must have type annotations with T.let() when specifying '# typed: strict' https://srb.help/5028
     205 |<M <U slice> $1>A = Stransind
                              ^^^^^^^^^

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:205: Method slice does not exist on T.class_of(<root>) https://srb.help/7003
     205 |<M <U slice> $1>A = Stransind
                ^^^^^

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:207: Method tDesuga does not exist on T.class_of(<root>) https://srb.help/7003
     207 |    va c     tDesuga   class A < Struct
     208 |   def bar=(arg0); arg0; end
     209 |         ansi
     210 |end

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:207: Method c does not exist on T.class_of(<root>) https://srb.help/7003
     207 |    va c     tDesuga   class A < Struct
     208 |   def bar=(arg0); arg0; end
     209 |         ansi
     210 |end

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:207: Method va does not exist on T.class_of(<root>) https://srb.help/7003
     207 |    va c     tDesuga   class A < Struct
     208 |   def bar=(arg0); arg0; end
     209 |         ansi
     210 |end

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done:208: This function does not have a `sig` https://srb.help/7017
     208 |   def bar=(arg0); arg0; end
             ^^^^^^^^^^^^^^

min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done: Exception in cfg+infer: min_crashers/crash-3846dda28015eedbdbb8f7d87ee61853fc4bf3e8.done (backtrace is above) https://srb.help/1001
Errors: 23
```

#### Expected behavior

Exception does not occur.

### PR DESCRIPTION
**Pull request by aisamanra**
Fixes #1129 among others: this adds logic so that we can look up symbols by type, finding redefinitions if they exist, and plumbs this logic through the namer. These new functions live in `GlobalState` and can be thought of as companion functions to the `enterSymbol` functions that look up existing symbols.

### Test plan

See included automated tests. Fuzzed test included in PR.

### CODE REVIEW

File: core/GlobalState.cc [hunk 1]
```diff
@@ -938,7 +965,7 @@ NameRef GlobalState::getNameUnique(UniqueNameKind uniqueNameKind, NameRef origin
         bucketId = (bucketId + probeCount) & mask;
         probeCount++;
     }
-    Exception::raise("should never happen");
```
Comment (aisamanra) [inline core/GlobalState.cc]: This changed because we now want to speculatively find a mangled name if one has been created for the purposes of `lookupSymbolWithFlags`: we might need to walk through all mangled names to find the relevant one, which means we can use this function to find the next mangled name if it exists.

File: main/pipeline/pipeline.cc [hunk 2]
```diff
@@ -869,6 +870,8 @@ vector<ast::ParsedFile> resolve(unique_ptr<core::GlobalState> &gs, vector<ast::P
                 ENFORCE(reresolved.size() == 1);
                 f = checkNoDefinitionsInsideProhibitedLines(*gs, move(reresolved[0]), 0, prohibitedLines);
             }
+            ENFORCE(symbolsBefore == gs->symbolsUsed(),
```
Comment (aisamanra) [inline main/pipeline/pipeline.cc]: This could be a more intensive test that checks for full equality of the symbol table, and not just whether it's the same size, but this is a cheap test that should still be true.

File: test/testdata/namer/fuzz_shared_singletons.rb [hunk 3]
```diff
@@ -2,4 +2,4 @@
 # disable-fast-path: true
 A=class A; end # error: Redefining constant
 
-class A; end # error: Redefining constant
+class A; end
```
Comment (aisamanra) [inline test/testdata/namer/fuzz_shared_singletons.rb]: The reason this error changed is because we've already created a `class A` and we can reopen that class within the same file, so this simply finds the already-created `class A` from above.

File: core/GlobalState.cc (hunk 1 above)
Comment (DarkDimius) [reply core/GlobalState.cc]: let's rename it to `lookup`. `get` stands for `fail if you can't` while `lookup` mail return `not found`.

File: core/GlobalState.cc [hunk 4]
```diff
@@ -938,7 +964,7 @@ NameRef GlobalState::getNameUnique(UniqueNameKind uniqueNameKind, NameRef origin
...
+    return core::Names::empty();
```
Comment (DarkDimius) [inline core/GlobalState.cc]: empty is emtry string https://github.com/sorbet/sorbet/blob/master/core/tools/generate_names.cc#L285
cound this use https://github.com/sorbet/sorbet/blob/master/core/NameRef.h#L82 instead? which is the name that `!nameRef.exists()`

File: core/GlobalState.cc [hunk 5]
```diff
@@ -581,6 +581,32 @@ void GlobalState::reserveMemory(u4 kb) {
...
+// flags match. If no sych symbol exists, then it will return noSymbol.
+SymbolRef GlobalState::lookupSymbolWithFlags(SymbolRef owner, NameRef name, u4 flags) const {
+    ENFORCE(owner.exists(), "looking up symbol from non-existing owner");
+    ENFORCE(name.exists(), "looking up symbol with non-existing name");
+    SymbolData ownerScope = owner.dataAllowingNone(*this);
+    histogramInc("symbol_lookup_by_name", ownerScope->members().size());
+
+    NameRef lookupName = name;
+    u2 unique = 1;
+    auto bareName = ownerScope->members().find(lookupName);
```
Comment (DarkDimius) [inline core/GlobalState.cc]: is this actually a name? isn't this a symbol?

File: core/GlobalState.cc [hunk 6]
```diff
@@ -581,6 +581,32 @@ void GlobalState::reserveMemory(u4 kb) {
...
+    auto res = bareName;
+    while (res != ownerScope->members().end() && res->second.exists()) {
```
Comment (DarkDimius) [inline core/GlobalState.cc]: > res->second.exists()

do we ever store NoSymbol into symbol table?
could this be an ENFORCE instead?

File: test/testdata/namer/fuzz_shared_singletons.rb (hunk 3 above)
Comment (DarkDimius) [reply test/testdata/namer/fuzz_shared_singletons.rb]: after processing this file, what is `A`?
is it class or symbol?
Which one "wins"?

File: main/pipeline/pipeline.cc (hunk 2 above)
Comment (DarkDimius) [reply main/pipeline/pipeline.cc]: nice

File: core/GlobalState.cc (hunk 5 above)
Comment (aisamanra) [reply core/GlobalState.cc]: This was a bad variable name for "the symbol associated with the bare name". I'll make it clearer.

File: test/testdata/namer/fuzz_shared_singletons.rb (hunk 3 above)
Comment (aisamanra) [reply test/testdata/namer/fuzz_shared_singletons.rb]: In this case, the constant `A` wins, because the first `class A; end` introduces `A`, then the constant `A` gets initialized and renames the existing `A` to `A$1`, then the second `class A; end` gets treated as reopening `A$1` but doesn't do any mangling. Should we prefer a different semantics?

Comment (DarkDimius) [reply test/testdata/namer/fuzz_shared_singletons.rb]: > Should we prefer a different semantics?

There are downsides & upsides to both.
I think this PR introduces a subtle change and thus it's worth giving it more tests and writing a lot of text for it.
