### PR TITLE
Take slow path on parse errors

### LINKED ISSUE #1554: documentSymbols many wrong symbols with syntax error
## input

```rb
# typed: true
class C
  @@foo = T.let(3, Integer)

  def bar
    @@quz
  end
end
```

1. Start with this file
1. Delete `quz` but not the leading `@@` (this produces a syntax error)
1. Put cursor directly after `@@foo`
1. Type `d`

## Expected symbols

Either replace the `@@foo` symbol with `@@food`, resulting in

- `C`
- `@@food`

Or don't change anything, resulting in

- `C`
- `@@foo`

Since there's a syntax error later in the file, it's arguable that we don't want
to both trying to figure out the symbols for this file.

## Actual symbols

- `C`
- `@@foo`
- `@@food`

---

Note that for every `d` press, we keep adding a new symbol.

### PR DESCRIPTION
**Pull request by aisamanra**
### Motivation
Fixes #1554; we were incorrectly taking the fast path on syntax error when we should have been taking the slow path.

### Test plan

See included automated tests. Added two LSP test traces: one with no syntax error, one with.

### CODE REVIEW

**Comment by DarkDimius** [comment]
@jvilk-stripe I don't think I'll have time to properly review this. Please take over!

File: main/lsp/updates.cc [hunk 1]
```diff
@@ -265,6 +265,9 @@ bool LSPLoop::canTakeFastPath(const FileUpdates &updates, const vector<core::Fil
             } else {
                 auto &oldHash = globalStateHashes[fref.id()];
                 ENFORCE(oldHash.definitions.hierarchyHash != core::GlobalStateHash::HASH_STATE_NOT_COMPUTED);
+                if (hashes[i].definitions.hierarchyHash == core::GlobalStateHash::HASH_STATE_INVALID) {
+                    return false;
+                }
                 if (hashes[i].definitions.hierarchyHash != core::GlobalStateHash::HASH_STATE_INVALID &&
```
Comment (jvilk-stripe) [inline main/lsp/updates.cc]: I think you can just change this line to `==`.

Comment (jvilk-stripe) [reply main/lsp/updates.cc]: Or remove the first conditional here and just have two separate checks and two separate logger messages, e.g.

```c++
if (HASH_STATE_INVALID) {
  logger->debug("Taking slow path because {} has a syntax error");
} else if (new != old) {
  // ...
}
```

File: test/testdata/lsp/field_edits.1.rbupdate.document-symbols.exp [hunk 2]
```diff
@@ -0,0 +1 @@
+{"jsonrpc":"2.0","id":1,"requestMethod":"textDocument/documentSymbol","result":[{"name":"C","detail":"","kind":5,"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":7}},"selectionRange":{"start":{"line":1,"character":0},"end":{"line":1,"character":7}},"children":[{"name":"@@foo","detail":"","kind":14,"range":{"start":{"line":2,"character":2},"end":{"line":2,"character":7}},"selectionRange":{"start":{"line":2,"character":2},"end":{"line":2,"character":7}},"children":[]},{"name":"bar","detail":"sig {returns(T.untyped)}","kind":6,"range":{"start":{"line":4,"character":2},"end":{"line":4,"character":9}},"selectionRange":{"start":{"line":4,"character":2},"end":{"line":4,"character":9}},"children":[]}]}]}
```
Comment (jvilk-stripe) [inline test/testdata/lsp/field_edits.1.rbupdate.document-symbols.exp]: The new `update_exp_files` should pretty print this.

File: test/testdata/lsp/field_edits.2.rbupdate.document-symbols.exp [hunk 3]
```diff
@@ -0,0 +1 @@
+{"jsonrpc":"2.0","id":1,"requestMethod":"textDocument/documentSymbol","result":[{"name":"C","detail":"","kind":5,"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":7}},"selectionRange":{"start":{"line":1,"character":0},"end":{"line":1,"character":7}},"children":[{"name":"@@food","detail":"","kind":14,"range":{"start":{"line":2,"character":2},"end":{"line":2,"character":8}},"selectionRange":{"start":{"line":2,"character":2},"end":{"line":2,"character":8}},"children":[]},{"name":"bar","detail":"sig {returns(T.untyped)}","kind":6,"range":{"start":{"line":4,"character":2},"end":{"line":4,"character":9}},"selectionRange":{"start":{"line":4,"character":2},"end":{"line":4,"character":9}},"children":[]}]}]}
```
Comment (jvilk-stripe) [inline test/testdata/lsp/field_edits.2.rbupdate.document-symbols.exp]: (ditto)

File: test/testdata/lsp/field_edits.2.rbupdate [hunk 4]
```diff
@@ -0,0 +1,8 @@
+# typed: true
```
Comment (jvilk-stripe) [inline test/testdata/lsp/field_edits.2.rbupdate]: Do you want to assert that this takes the slow path? Because you can.

https://github.com/sorbet/sorbet#testing-incremental-typechecking

File: test/testdata/lsp/good_field_edits.1.rbupdate [hunk 5]
```diff
@@ -0,0 +1,8 @@
+# typed: true
```
Comment (jvilk-stripe) [inline test/testdata/lsp/good_field_edits.1.rbupdate]: Ditto -- you could also assert that this takes the slow path.
