### PR TITLE
Fix handling of `overridable` and `abstract` in attr_* chains

### LINKED ISSUE #4456: Rewriter doesn't parse sigs with override/overridable
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Amodule%20IFoo%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20abstract!%0A%0A%20%20sig%20%7Babstract.returns(T.nilable(Integer))%7D%0A%20%20def%20good_method%3B%20end%0A%0A%20%20sig%20%7Babstract.params(arg0%3A%20T.nilable(Integer)).returns(T.nilable(Integer))%7D%0A%20%20def%20good_method%3D(arg0)%3B%20end%0A%0A%20%20sig%20%7Babstract.returns(T.nilable(Integer))%7D%0A%20%20def%20bad_method%3B%20end%0Aend%0A%0Aclass%20Foo%0A%20%20include%20IFoo%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Boverride.returns(T.nilable(Integer))%7D%0A%20%20attr_accessor%20%3Agood_method%0A%0A%20%20sig%20%7Breturns(T.nilable(Integer)).override%7D%0A%20%20attr_accessor%20%3Abad_method%0Aend)

```ruby
# typed: strict

module IFoo
  extend T::Sig
  extend T::Helpers
  abstract!

  sig {abstract.returns(T.nilable(Integer))}
  def good_method; end

  sig {abstract.params(arg0: T.nilable(Integer)).returns(T.nilable(Integer))}
  def good_method=(arg0); end

  sig {abstract.returns(T.nilable(Integer))}
  def bad_method; end
end

class Foo
  include IFoo
  extend T::Sig

  sig {override.returns(T.nilable(Integer))}
  attr_accessor :good_method

  sig {returns(T.nilable(Integer)).override}
  attr_accessor :bad_method
end
```

#### Observed output

```
editor.rb:26: Use of undeclared variable @bad_method https://srb.help/6002
    26 |  attr_accessor :bad_method
                         ^^^^^^^^^^

editor.rb:26: Use of undeclared variable @bad_method https://srb.help/6002
    26 |  attr_accessor :bad_method
                         ^^^^^^^^^^

editor.rb:26: This function does not have a sig https://srb.help/7017
    26 |  attr_accessor :bad_method
          ^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 3
```

#### Expected behavior

The `good_method` and `bad_method` case should behave identically. The only difference is the placement of the `.override` in the sig builder.

- - -

This is very similar to https://github.com/sorbet/sorbet/pull/3159, which might serve as an inspiration for a potential implementation.

### PR DESCRIPTION
**Pull request by jwinr**
Added conditions in `Util.cc` to explicitly identify `overridable` and `abstract` modifiers, as well as additional tests to verify proper functionality.

### Motivation
PR https://github.com/sorbet/sorbet/pull/8308 only partially fixed the issue. It did not account for the `overridable` or `abstract` modifiers. See: https://github.com/sorbet/sorbet/pull/8308#issuecomment-2492067279

Fixes #4456: "Rewriter doesn't parse sigs with override"

### Test plan

See included automated tests.

### CODE REVIEW

File: test/testdata/rewriter/attr_override.rb [hunk 1]
```diff
@@ -26,4 +28,19 @@ def initialize
 
   sig {returns(T.nilable(Integer)).override.checked(:always)}
   attr_accessor :method4
+
+  sig {returns(T.nilable(Integer)).overridable}
+  attr_accessor :method5
+
+  sig {returns(T.nilable(Integer)).abstract}
+  def method6; end
```
Comment (jez) [inline test/testdata/rewriter/attr_override.rb:36]: This doesn't actually exercise the `castSig` code. `castSig` is a partial reimplementation of some code in `resolver/type_syntax/type_syntax.cc`, where full-fledged `sig` parsing happens. This `castSig` helper duplicates just enough of that logic to power certain rewrite passes, e.g. the `attr_accessor` one.

That means that to see the "bug," we'd need to do something like `attr_accessor :method6` here, instead of `def method6`, where it would then be observable that Sorbet treats a leading `abstract` differently from a trailing `abstract`, but it's not even clear that that's a proper "bug" because we at least report some error later in the pipeline.

[For example, sorbet.run →](https://sorbet.run/?arg=--print=rewrite-tree#%23%20typed%3A%20strict%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%2C%20T%3A%3AHelpers%0A%20%20abstract!%0A%0A%20%20sig%20%7Babstract.returns%28T.nilable%28Integer%29%29%7D%0A%20%20attr_accessor%20%3Amethod6%0A%0A%20%20sig%20%7Breturns%28T.nilable%28Integer%29%29.abstract%7D%0A%20%20attr_accessor%20%3Amethod7%0Aend)

It's fine to keep this here just for fun, but it doesn't exercise the same codepaths as the nearby code.

**Review by jez — APPROVED** [review]
thanks!

File: test/testdata/rewriter/attr_override.rb (hunk 1 above)
Comment (jwinr) [reply test/testdata/rewriter/attr_override.rb:36]: Good to know, thanks for the explanation!
