### PR TITLE
Fix ENFORCE from repeated kwargs

### LINKED ISSUE #1133: (From Fuzzer) namer/namer.cc:387 enforced condition i < ctx.owner.data(ctx)->arguments().size() has failed: (no message provided)
#### Input

[→ View on sorbet.run](https://sorbet.run/#def%20f(k%3A%2Ck%3A)end)

```ruby
def f(k:,k:)end
```

#### Observed output

```
Exception::raise(): namer/namer.cc:387 enforced condition i < ctx.owner.data(ctx)->arguments().size() has failed: (no message provided)

Backtrace:
sorbet::Exception::enforce_handler(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int) (in librealmain.so) (Exception.h:47)
sorbet::namer::NameInserter::fillInArgs(sorbet::core::MutableContext, std::__1::vector<sorbet::ast::ParsedArg, std::__1::allocator<sorbet::ast::ParsedArg> >) (in libnamer.so) (namer.cc:387)
sorbet::namer::NameInserter::preTransformMethodDef(sorbet::core::MutableContext, std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >) (in libnamer.so) (namer.cc:554)
sorbet::ast::PostPonePreTransform_MethodDef<sorbet::namer::NameInserter, sorbet::core::MutableContext, true>::call(sorbet::core::MutableContext, std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >, sorbet::namer::NameInserter&) (in libnamer.so) (treemap.h:204)
sorbet::ast::TreeMapper<sorbet::namer::NameInserter, sorbet::core::MutableContext>::mapMethodDef(std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >, sorbet::core::MutableContext) (in libnamer.so) (treemap.h:293)
sorbet::ast::TreeMapper<sorbet::namer::NameInserter, sorbet::core::MutableContext>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::MutableContext) (in libnamer.so) (treemap.h:666)
sorbet::ast::TreeMapper<sorbet::namer::NameInserter, sorbet::core::MutableContext>::mapClassDef(std::__1::unique_ptr<sorbet::ast::ClassDef, std::__1::default_delete<sorbet::ast::ClassDef> >, sorbet::core::MutableContext) (in libnamer.so) (treemap.h:281)
sorbet::ast::TreeMapper<sorbet::namer::NameInserter, sorbet::core::MutableContext>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::MutableContext) (in libnamer.so) (treemap.h:672)
std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> > sorbet::ast::TreeMap::apply<sorbet::core::MutableContext, sorbet::namer::NameInserter>(sorbet::core::MutableContext, sorbet::namer::NameInserter&, std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >) (in libnamer.so) (treemap.h:712)
sorbet::namer::Namer::run(sorbet::core::MutableContext, sorbet::ast::ParsedFile) (in libnamer.so) (namer.cc:806)
sorbet::realmain::pipeline::name(sorbet::core::GlobalState&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, bool) (in libpipeline.so) (pipeline.cc:735)
sorbet::realmain::pipeline::resolve(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&, bool) (in libpipeline.so) (pipeline.cc:833)
sorbet::realmain::realmain(int, char**) (in librealmain.so) (realmain.cc:429)
main (in sorbet) (main.cc:7)
start (in libdyld.dylib) + 1

min_crashers_new/crash-ad65ac5698ece533cf76b5c24f57bd3c9cb28dff.done:1: Failed to process tree (backtrace is above) https://srb.help/1001
     1 |def f(k:,k:)end
        ^^^^^^^^^^^^^^^

min_crashers_new/crash-ad65ac5698ece533cf76b5c24f57bd3c9cb28dff.done: Exception naming file: min_crashers_new/crash-ad65ac5698ece533cf76b5c24f57bd3c9cb28dff.done (backtrace is above) https://srb.help/1001
Errors: 2
```

#### Expected behavior

Enforce does not fail.

### PR DESCRIPTION
**Pull request by aisamanra**
### Motivation
Fixes #1133: the problem is that [this code in `namer.cc`](https://github.com/sorbet/sorbet/blob/a32794361584bab9f7af6e5729c530ce7311e86d/namer/namer.cc#L394-L396) expects that each time we convert an arg to a symbol, we've expanded the list of arguments in the owning symbol, but [this code in `enterMethodArgumentSymbol`](https://github.com/sorbet/sorbet/blob/a32794361584bab9f7af6e5729c530ce7311e86d/core/GlobalState.cc#L700-L704) allows us to avoid adding anything to the arguments list that if we find another argument with the same name.

In the case of non-keyword parameters, even identically-named parameters (e.g. `def f(x, x)`) will not have a names that are `==` to one another because of how fresh name generation works for the `ArgInfo` type, which means the duplication check in `enterMethodArgumentSymbol` will never fire for positional parameters. The only situation in which the duplication check will fire is when we have repeated keyword parameters, because then we break the invariant expected elsewhere that the argument list expands each time.

This was only one potential simple fix: the other one is to relax the `ENFORCE`, and the slightly-less-simple-but-still-pretty-easy fix is to also generate fresh names in the keyword case to match the behavior of positional parameters: in that case, the code deleted in this branch would also become redundant, so this seemed reasonable in either case, but I'm open to taking a different tack on this.

### Test plan

See included automated tests. Added fuzzed test case.

### CODE REVIEW

**Comment by jez** [comment]
> because of how fresh name generation works

The weird case for method names here is not due to "fresh name generation" in the alpha-varying sense, but instead to make method redefinition checks easier. It used to be the case that

```ruby
def main(args); end
def main(argv); end
```

Was an incompatible redefinition, because `"argv" != "args"`. This was super restrictive, and cropped up in a bunch of unanticipated places when we started to run in incremental resolver mode on pay-server. The way we solved it was to make all positional args have a predictable name, so that any unary method could be redefined with any other unary method, regardless of choice of variable name.

The current solution has (as I understand it) the unfortunate side effect of turning `def foo(x, x); end` into a valid method `def foo(arg0, arg1); end`, which both covers up the fact that Ruby will warn and will make Sorbet behave unpredictably.

What do you think of fixing this in Desugar?

https://github.com/sorbet/sorbet/blob/9eb64b6d82516ee8e4a60da31fd9c202468635eb/ast/desugar/Desugar.cc#L41

^ I think we could edit this function in Desugar.cc to keep track of a set of the names seen so far, and raise an error + omit args when a redundant arg name is found.

**Comment by aisamanra** [comment]
For status: I think `Desugar.cc` isn't the right place for this, because some of the logic is going to be both complicated and also redo work that we do later on: in particular, to make sure that `foo(x, x:)` is also an error, we'll need to tear apart the expressions and/or AST nodes in a way that replicates logic we already have in the `LocalNameInserter` pass. Doing this same check in that pass is _much_ simpler, and can simply involve comparing the generated `NameRef`s of the arguments instead of having to destruct AST nodes to get at the underlying strings.

File: local_vars/local_vars.cc [hunk 1]
```diff
@@ -70,7 +71,22 @@ class LocalNameInserter {
             }
             unique_ptr<ast::Reference> refExpImpl(refExp);
             arg.release();
-            namedArgs.emplace_back(nameArg(move(refExpImpl)));
+            auto named = nameArg(move(refExpImpl));
+            for (auto &prev : namedArgs) {
+                if (prev.name == named.name && !absl::StartsWith(prev.name.data(ctx)->shortName(ctx), "_")) {
```
Comment (aisamanra) [inline local_vars/local_vars.cc]: The `shortName` function allocates a new string, which isn't great, but this should _only_ be necessary when we have repeated argument names to begin with, which is very rarely—usually, we're just comparing two `NameRef`s, which is much cheaper, and they'll almost never be identical.

File: local_vars/local_vars.cc [hunk 2]
```diff
@@ -70,7 +71,22 @@ class LocalNameInserter {
...
+                    if (auto e = ctx.state.beginError(named.loc, core::errors::Namer::RepeatedArgument)) {
+                        auto frame = scopeStack.back();
+                        e.setHeader("Duplicated argument name `{}`", named.name.show(ctx));
+                        if (frame.insideMethod) {
```
Comment (aisamanra) [inline local_vars/local_vars.cc]: These extra clauses point to the method head (if the repeated arguments are in a method) or to the entire block (if in a block) because otherwise, for method heads that are spread across multiple lines, you might not get that context. For example, 
```ruby
def foo(
    this,
    this
); end
```
gives you the error message
```
fuzz/1133.rb:6: Duplicated argument name this https://srb.help/4017
     6 |      this:
              ^^^^^
    fuzz/1133.rb:4: In argument list of method
     4 |def foo(
     5 |      this,
     6 |      this:
     7 |    )
```

File: test/testdata/namer/fuzz_repeated_kwarg.rb [hunk 3]
```diff
@@ -0,0 +1,17 @@
+# typed: false
+# from fuzzer: https://github.com/sorbet/sorbet/issues/1133
+def f1(x, x); end # error: Duplicated argument name `x`
+def f2(x, x=0); end # error: Duplicated argument name `x`
+def f3(x:, x:); end # error: Duplicated argument name `x`
+def f4(x:, x: nil); end # error: Duplicated argument name `x`
+def f5(x, x:); end # error: Duplicated argument name `x`
+def f6(x, x: nil); end # error: Duplicated argument name `x`
+def f7(x=0, x: nil); end # error: Duplicated argument name `x`
```
Comment (jez) [inline test/testdata/namer/fuzz_repeated_kwarg.rb]: Could you add a test where the repeated argument has something between it?

```ruby
def foo(x, y, x); end
```

File: local_vars/local_vars.cc [hunk 4]
```diff
@@ -70,7 +71,22 @@ class LocalNameInserter {
             }
             unique_ptr<ast::Reference> refExpImpl(refExp);
             arg.release();
-            namedArgs.emplace_back(nameArg(move(refExpImpl)));
+            auto named = nameArg(move(refExpImpl));
+            for (auto &prev : namedArgs) {
```
Comment (jez) [inline local_vars/local_vars.cc]: This is accidentally quadratic; not sure if we care to use a hashmap to avoid that.

File: local_vars/local_vars.cc [hunk 5]
```diff
@@ -70,7 +71,22 @@ class LocalNameInserter {
...
+                if (prev.name == named.name && !absl::StartsWith(prev.name.data(ctx)->shortName(ctx), "_")) {
+                    if (auto e = ctx.state.beginError(named.loc, core::errors::Namer::RepeatedArgument)) {
+                        auto frame = scopeStack.back();
```
Comment (jez) [inline local_vars/local_vars.cc]: Can you ENFORCE that this is non-empty?

File: local_vars/local_vars.cc (hunk 2 above)
Comment (jez) [reply local_vars/local_vars.cc]: Can you think of a case when we are neither in a block nor in a method and we get this error? Might be worth ENFORCE'ing in the else case if not.

File: local_vars/local_vars.cc (hunk 4 above)
Comment (aisamanra) [reply local_vars/local_vars.cc]: FWIW, this is the same logic we used indirectly before: it was just hidden behind `enterMethodArgumentSymbol`, which was called for every argument and would traverse all of the existing arguments first, so I don't believe this should be any slower than the current state.

I'm a bit nervous that for the common case of <4 or so arguments, the overhead of allocating a hashmap here would be a greater hit to performance than walking a short array, but I also don't want to make a specific decision one way or another without some data—maybe I can make an issue to investigate further once I've depleted fuzz bugs.

**Comment by DarkDimius** [comment]
> https://github.com/sorbet/sorbet/pull/1326/commits/f4919cfbf6de3e4e645a558f04177635274da1b9

what are the errors there? why are they duplicated?

File: local_vars/local_vars.cc (hunk 1 above)
Comment (DarkDimius) [reply local_vars/local_vars.cc]: > The shortName function allocates a new string

it doesn't. It gives a `string_view`

**Comment by DarkDimius** [comment]
Actually, after thinking a bit more about this, why does this belong in namer?
It's an entirely syntactic property.
Can we move it to Desugar?

**Comment by DarkDimius** [comment]
```
In the case of non-keyword parameters, even identically-named parameters (e.g. def f(x, x)) will not have a names that are == to one another because of how fresh name generation works for the ArgInfo type, which means the duplication check in enterMethodArgumentSymbol will never fire for positional parameters. 
```
Is actually a strong indicator that it doesn't belong to namer indeed :-)

**Comment by aisamanra** [comment]
We could, but the implementation would be less clean in desugar. The reason I didn't put this into desugar before was that `def f(x, x:)` should raise this error as well, but determining that the variable `x` and the keyword `x:` desugar to the same local variable involves replicating the logic found in `local_vars.cc` (in the [`nameArg` function defined here](https://github.com/sorbet/sorbet/blob/master/local_vars/local_vars.cc#L23)) to walk the AST nodes and extract the name that corresponds to the actual bound variable. Putting it here allowed us to reuse that bit of functionality.

The bit you quoted, that started with
> In the case of non-keyword parameters, even identically-named parameters (e.g. def f(x, x)) will not have a names that are == to one another…


referred to an earlier version of the PR and not the current one; I just forgot to update the PR text to reflect the current state of the PR. At the time, I was trying to do this check _after_ the `local_vars` pass, at which point we had already run `nameArg` to resolve the parameter into a local variable. The described problem is sidestepped in this current implementation, because in the body of `local_vars` we still have access to the `NameRef` that describes the local variable bound by an argument: any earlier and we'd have to redo the work that `nameArg` does in resolving the parameter to its name, any later and we'd only have convenient access to the `ArgInfo` and not the actual local name.

File: core/GlobalState.cc [hunk 6]
```diff
@@ -697,11 +697,6 @@ ArgInfo &GlobalState::enterMethodArgumentSymbol(Loc loc, SymbolRef owner, NameRe
     ENFORCE(name.exists(), "entering symbol with non-existing name");
     SymbolData ownerScope = owner.dataAllowingNone(*this);
 
-    for (auto &arg : ownerScope->arguments()) {
```
Comment (DarkDimius) [inline core/GlobalState.cc]: This makes this method dissimilar to other `enter`s.
Why was this neccessary? If it's necessary, can we rename the method to make it not have a similar name to others?

Comment (aisamanra) [reply core/GlobalState.cc]: This was deleted because it broke the assumption in this `ENFORCE`, which stipulates that the arguments list expands every time that we get a new method argument symbol. https://github.com/sorbet/sorbet/blob/a32794361584bab9f7af6e5729c530ce7311e86d/namer/namer.cc#L394-L396 Alternately, I could rewrite or delete the `ENFORCE` there, which I think is trying to maintain an invariant that's not necessary to maintain.

Comment (DarkDimius) [reply core/GlobalState.cc]: TBH, I don't understand why this enforce was firing.
On the contrary, this seems to me like we're duplicating argument symbols in incremental runs, could you verify?

Comment (DarkDimius) [reply core/GlobalState.cc]: I think implementing the following TODO is the proper way:
https://github.com/sorbet/sorbet/blob/a32794361584bab9f7af6e5729c530ce7311e86d/namer/namer.cc#L550

**Comment by aisamanra** [comment]
I've moved the enforcement `arg2Symbol`: that way, `enterMethodArgumentSymbol` can stay as it was, but `arg2Symbol` should be aware of the fact that (in the case of repeated kwargs) we don't have as many method arguments as we expect and fill them in.

File: namer/namer.cc [hunk 7]
```diff
@@ -89,7 +89,21 @@ class NameInserter {
...
         }
+        // we know right now that pos >= arguments().size() because otherwise we would have hit the early return at the
+        // beginning of this method
         auto &argInfo = ctx.state.enterMethodArgumentSymbol(parsedArg.loc, ctx.owner, name);
+        // if enterMethodArgumentSymbol did not emplace a new argument into the list, then it means it's reusing an
+        // existing one, which means we've seen a repeated kwarg (as it treats identically named kwargs as
+        // identical). We know that we need to match the arity of the function as written, so if we don't have as many
+        // arguments as we expect, clone the one we got back from enterMethodArgumentSymbol in the position we expect
+        if (ctx.owner.dataAllowingNone(ctx)->arguments().size() == pos) {
+            ctx.owner.dataAllowingNone(ctx)->arguments().emplace_back(argInfo.deepCopy());
```
Comment (DarkDimius) [inline namer/namer.cc]: could we name-mangle name here for second arg so that the future phases don't need to protect from multiple args with the same name?

File: core/Names.h [hunk 8]
```diff
@@ -48,6 +48,7 @@ enum UniqueNameKind : u2 {
     Overload,
     TypeVarName,
     PositionalArg,       // num >=0 - normal args, -1 ==> restarg, -2 => kwrest arg
+    KeywordArg,          // only used when we have duplicated keyword arguments
```
Comment (DarkDimius) [inline core/Names.h]: can we give it a more descriptive name?
Maybe `MangledKeywordArg`?
