### PR TITLE
Fix crash by fixing funLoc for `Super` and `ZSuper`

### LINKED ISSUE #10035: [Bug] Crash in debug builds when combining `super`, a parameter, and a block pass
The code below fails an assertion and throws an exception under `config=dbg` (passes under `config=release-mac`):

```
Exception::raise() msg="./core/LocOffsets.h:34 enforced condition beginLoc <= endLoc has failed: (no message provided)"

Backtrace:
# abridged, see the section below

/Users/alex/src/github.com/Sorbet/Sorbet/demo.rb:14: Failed to type (backtrace is above) https://srb.help/1001
    14 |    super(&block)
            ^^^^^^^^^^^^^

/Users/alex/src/github.com/Sorbet/Sorbet/demo.rb:13: Failed to process tree (backtrace is above) https://srb.help/1001
    13 |  def demo(&block)
    14 |    super(&block)
    15 |  end

/Users/alex/src/github.com/Sorbet/Sorbet/demo.rb: Exception in cfg+infer: /Users/alex/src/github.com/Sorbet/Sorbet/demo.rb (backtrace is above) https://srb.help/1001
Errors: 3
```

I bisected it down to #9419.
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Parent%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20params%28id%3A%20Integer%2C%20block%3A%20T.proc.void%29.void%20%7D%0A%20%20def%20demo%28id%3A%20123%2C%20%26block%29%0A%20%20end%0Aend%0A%0Aclass%20Child%20%3C%20Parent%0A%20%20sig%20%7B%20params%28block%3A%20T.proc.void%29.void%20%7D%0A%20%20def%20demo%28%26block%29%0A%20%20%20%20super%28%26block%29%0A%20%20end%0Aend%0A)

```ruby
# typed: true

class Parent
  extend T::Sig

  sig { params(id: Integer, block: T.proc.void).void }
  def demo(id: 123, &block)
  end
end

class Child < Parent
  sig { params(block: T.proc.void).void }
  def demo(&block)
    super(&block)
  end
end
```

Here's some variations I tested:

1. Remove the `id` parameter entirely (`def demo(&block)`). No crash.

    ```ruby
    # typed: true

    class Parent
      extend T::Sig

      sig { params(block: T.proc.void).void }
      def demo(&block); end
    end

    class Child < Parent
      sig { params(block: T.proc.void).void }
      def demo(&block) = super(&block)
    end
    ```

1. Don't rely on the default arg, and pass in an explicit value (`super(id: 123, &block)`). No crash.

    ```ruby
    # typed: true

    class Parent
      extend T::Sig

      sig { params(id: Integer, block: T.proc.void).void }
      def demo(id: 123, &block); end
    end

    class Child < Parent
      sig { params(block: T.proc.void).void }
      def demo(&block) = super(id: 123, &block)
    end
    ```

1. Remove `123` default value, don't pass it. Crashes.

    ```ruby
    # typed: true

    class Parent
      extend T::Sig

      sig { params(id: Integer, block: T.proc.void).void }
      def demo(id:, &block); end
    end

    class Child < Parent
      sig { params(block: T.proc.void).void }
      def demo(&block) = super(&block)
    end
    ```

1. Replace `id: 123` kwarg with positional `arg = 123`. No crash.

    ```ruby
    # typed: true

    class Parent
      extend T::Sig

      sig { params(id: Integer, block: T.proc.void).void }
      def demo(id = 123, &block); end
    end

    class Child < Parent
      sig { params(block: T.proc.void).void }
      def demo(&block) = super(&block)
    end
    ```

1. Keep the `id: 123` kwarg, but call it with a posarg (`super(123, &block)`). No crash (reports an error correctly).

    ```ruby
    # typed: true

    class Parent
      extend T::Sig

      sig { params(id: Integer, block: T.proc.void).void }
      def demo(id: 123, &block); end
    end

    class Child < Parent
      sig { params(block: T.proc.void).void }
      def demo(&block) = super(123, &block)
    end
    ```

1. Remove overriding. Call them `demo1` and `demo2`, and replace the `super` call with a call to the named method. No crash.

    ```ruby
    # typed: true

    class Parent
      extend T::Sig

      sig { params(id: Integer, block: T.proc.void).void }
      def demo1(id: 123, &block); end
    end

    class Child < Parent
      sig { params(block: T.proc.void).void }
      def demo2(&block) = demo1(&block)
    end
    ```

1. Remove all the block params, call with `super()`. No crash.

    ```ruby
    # typed: true

    class Parent
      extend T::Sig

      sig { params(id: Integer).void }
      def demo(id: 123); end
    end

    class Child < Parent
      sig { void }
      def demo() = super()
    end
    ```

1. Remove all the block params, call with `super`. No crash.

    ```ruby
    # typed: true

    class Parent
      extend T::Sig

      sig { params(id: Integer).void }
      def demo(id: 123); end
    end

    class Child < Parent
      sig { void }
      def demo() = super
    end
    ```

1. Pass a literal `{}` block instead. Crashes.

    ```ruby
    # typed: true
    
    class Parent
      extend T::Sig

      sig { params(id: Integer, block: T.proc.void).void }
      def demo(id: 123, &block); end
    end

    class Child < Parent
      sig { params(block: T.proc.void).void }
      def demo(&block) = super {}
    end
    ```

#### Observed output

Passes in production builds (such as on Sorbet.run), but trips an `ENFORCE` statement in debug builds.

<details><summary>Full backtrace</summary>

On commit 77f491814ab9843cc83e2cb76d885433d54c1b91 (with cherry picked changes from https://github.com/Shopify/sorbet/tree/llvm-16-0-5 to fix compilation under macOS Tahoe).

```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=1, subcode=0x1012f56e0)
  * frame #0: 0x00000001012f56e4 sorbet`stopInDebugger() at mac.cc:72:9
    frame #1: 0x000000010000b200 sorbet`sorbet::core::LocOffsets::LocOffsets(this=0x000000016fde810c, beginLoc=238, endLoc=231) at LocOffsets.h:34:9
    frame #2: 0x000000010000b148 sorbet`sorbet::core::LocOffsets::LocOffsets(this=0x000000016fde810c, beginLoc=238, endLoc=231) at LocOffsets.h:33:89
    frame #3: 0x000000010000b094 sorbet`sorbet::core::Loc::Loc(this=0x000000016fde810c, file=(_id = 153), begin=238, end=231) at Loc.h:75:70
    frame #4: 0x0000000100002588 sorbet`sorbet::core::Loc::Loc(this=0x000000016fde810c, file=(_id = 153), begin=238, end=231) at Loc.h:75:90
    frame #5: 0x00000001011e89c4 sorbet`sorbet::core::DispatchArgs::argsLoc(this=0x000000016fdee3f0, gs=0x00000007b507c000) const at types.cc:1148:22
    frame #6: 0x0000000101182870 sorbet`sorbet::core::(anonymous namespace)::reportMissingKwargs(gs=0x00000007b507c000, args=0x000000016fdee3f0, method=(_id = 18089), missingKwargs=size=0, inClass=(_id = 3765), targs=size=0) at calls.cc:358:24
    frame #7: 0x00000001011771f0 sorbet`sorbet::core::(anonymous namespace)::dispatchCallSymbol(gs=0x00000007b507c000, args=0x000000016fdee3f0, symbol=(_id = 3765), targs=size=0) at calls.cc:1486:26
    frame #8: 0x000000010116e180 sorbet`sorbet::core::ClassType::dispatchCall(this=0x000000016fdedc60, gs=0x00000007b507c000, args=0x000000016fdee3f0) const at calls.cc:1703:12
    frame #9: 0x00000001011385c0 sorbet`decltype(auto) sorbet::core::(anonymous namespace)::CALL_MEMBER_impl_dispatchCall<sorbet::core::ClassType const, true>::call<sorbet::core::GlobalState const&, sorbet::core::DispatchArgs const&>(self=0x000000016fdedc60, args=0x00000007b507c000, args=0x000000016fdee3f0) at TypePtr.cc:43:1
    frame #10: 0x0000000101138344 sorbet`sorbet::core::TypePtr::dispatchCall(this=0x00000007b5032428, gs=0x00000007b507c000, args=0x000000016fdee3f0) const at TypePtr.cc:425:5
    frame #11: 0x00000001011a4b60 sorbet`sorbet::core::(anonymous namespace)::Magic_callWithBlockPass::simulateCall(gs=0x00000007b507c000, receiver=0x00000007b5032428, innerArgs=0x000000016fdee3f0, passedInBlockType=(store = 2169454014234897), blockTypeOrigins=0x00000007b50323d8, callLoc=Loc @ 0x000000016fdee180, blockLoc=Loc @ 0x000000016fdee170, res=0x000000016fdf4898) at calls.cc:2673:42
    frame #12: 0x00000001011a4300 sorbet`sorbet::core::(anonymous namespace)::Magic_callWithBlockPass::apply(this=0x0000000101a35db8, gs=0x00000007b507c000, args=0x000000016fdf4940, res=0x000000016fdf4898) const at calls.cc:2838:9
    frame #13: 0x0000000101178ed0 sorbet`sorbet::core::(anonymous namespace)::dispatchCallSymbol(gs=0x00000007b507c000, args=0x000000016fdf4940, symbol=(_id = 25), targs=size=1) at calls.cc:1608:20
    frame #14: 0x0000000101179e68 sorbet`sorbet::core::AppliedType::dispatchCall(this=0x00000007b509cb40, gs=0x00000007b507c000, args=0x000000016fdf4940) const at calls.cc:1708:12
    frame #15: 0x0000000101138a4c sorbet`decltype(auto) sorbet::core::(anonymous namespace)::CALL_MEMBER_impl_dispatchCall<sorbet::core::AppliedType const, true>::call<sorbet::core::GlobalState const&, sorbet::core::DispatchArgs const&>(self=0x00000007b509cb40, args=0x00000007b507c000, args=0x000000016fdf4940) at TypePtr.cc:43:1
    frame #16: 0x00000001011384dc sorbet`sorbet::core::TypePtr::dispatchCall(this=0x00000007b5032320, gs=0x00000007b507c000, args=0x000000016fdf4940) const at TypePtr.cc:425:5
    frame #17: 0x00000001009024e4 sorbet`sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_0::operator()(this=0x000000016fdf5eb0, send=0x00000007b506d900) const at environment.cc:1061:49
    frame #18: 0x0000000100901918 sorbet`bool sorbet::typecaseHelper<sorbet::cfg::InstructionPtr, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_0&>(base=0x00000007b4d9d298, func=0x000000016fdf5eb0) at typecase.h:89:9
    frame #19: 0x00000001008e6178 sorbet`void sorbet::typecase<sorbet::cfg::InstructionPtr, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_0, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_1, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_2, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_3, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_4, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_5, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_6, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_7, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_8, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_9, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_10, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_11, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_12, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_13, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_14, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_15, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::CFG const&, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr const&, std::__1::optional<sorbet::cfg::BasicBlock::BlockExitCondInfo> const&)::$_16>(base=0x00000007b4d9d298, funcs=0x000000016fdf5eb0, funcs=0x000000016fdf5e80, funcs=0x000000016fdf5e58, funcs=0x000000016fdf5e38, funcs=0x000000016fdf5e08, funcs=0x000000016fdf5df0, funcs=0x000000016fdf5dd8, funcs=0x000000016fdf5dc0, funcs=0x000000016fdf5d90, funcs=0x000000016fdf5d58, funcs=0x000000016fdf5d38, funcs=0x000000016fdf5d18, funcs=0x000000016fdf5cf8, funcs=0x000000016fdf5ce0, funcs=0x000000016fdf5cc8, funcs=0x000000016fdf5cb0, funcs=0x000000016fdf5c78) at typecase.h:99:34
    frame #20: 0x00000001008e448c sorbet`sorbet::infer::Environment::processBinding(this=0x00000007b52e0780, ctx=Context @ 0x000000016fdf6fa0, inWhat=0x00000007b4dc2400, bind=0x00000007b4d9d280, loopCount=0, bindMinLoops=0, knowledgeFilter=0x000000016fdf78b0, constr=0x0000000101a42338, methodReturnType=0x000000016fdf7ad0, parentUpdateKnowledgeReceiver= Has Value=false ) at environment.cc:1027:9
    frame #21: 0x000000010092cb7c sorbet`sorbet::infer::Inference::run(ctx=Context @ 0x000000016fdf8320, cfg=sorbet::cfg::CFG @ 0x00000007b4dc2400) at inference.cc:343:29
    frame #22: 0x0000000100469248 sorbet`sorbet::realmain::pipeline::(anonymous namespace)::CFGCollectorAndTyper::preTransformMethodDef(this=0x000000016fdf9a80, ctx=Context @ 0x000000016fdf8448, tree=0x00000007b506d720) at pipeline.cc:1428:19
    frame #23: 0x00000001004690fc sorbet`decltype(auto) sorbet::ast::MapFunctions<(sorbet::ast::TreeMapKind)1>::CALL_MEMBER_impl_preTransformMethodDef<sorbet::realmain::pipeline::(anonymous namespace)::CFGCollectorAndTyper, true>::call<sorbet::core::Context&, sorbet::ast::ExpressionPtr&>(self=0x000000016fdf9a80, args=0x000000016fdf8920, args=0x00000007b506d720) at treemap.h:179:5
    frame #24: 0x00000001004684c0 sorbet`sorbet::ast::TreeMapper<sorbet::realmain::pipeline::(anonymous namespace)::CFGCollectorAndTyper, sorbet::core::Context, (sorbet::ast::TreeMapKind)1, (sorbet::ast::TreeMapDepthKind)1>::mapMethodDef(this=0x000000016fdf9780, v=0x00000007b506d720, ctx=Context @ 0x000000016fdf8920) at treemap.h:344:9
    frame #25: 0x0000000100467920 sorbet`sorbet::ast::TreeMapper<sorbet::realmain::pipeline::(anonymous namespace)::CFGCollectorAndTyper, sorbet::core::Context, (sorbet::ast::TreeMapKind)1, (sorbet::ast::TreeMapDepthKind)1>::mapIt(this=0x000000016fdf9780, what=0x00000007b506d720, ctx=Context @ 0x000000016fdf8ad0) at treemap.h:602:28
    frame #26: 0x0000000100468460 sorbet`sorbet::ast::TreeMapper<sorbet::realmain::pipeline::(anonymous namespace)::CFGCollectorAndTyper, sorbet::core::Context, (sorbet::ast::TreeMapKind)1, (sorbet::ast::TreeMapDepthKind)1>::mapClassDef(this=0x000000016fdf9780, v=0x00000007b514e7a0, ctx=Context @ 0x000000016fdf8f40) at treemap.h:337:13
    frame #27: 0x00000001004678e8 sorbet`sorbet::ast::TreeMapper<sorbet::realmain::pipeline::(anonymous namespace)::CFGCollectorAndTyper, sorbet::core::Context, (sorbet::ast::TreeMapKind)1, (sorbet::ast::TreeMapDepthKind)1>::mapIt(this=0x000000016fdf9780, what=0x00000007b514e7a0, ctx=Context @ 0x000000016fdf90d0) at treemap.h:599:28
    frame #28: 0x0000000100469040 sorbet`sorbet::ast::TreeMapper<sorbet::realmain::pipeline::(anonymous namespace)::CFGCollectorAndTyper, sorbet::core::Context, (sorbet::ast::TreeMapKind)1, (sorbet::ast::TreeMapDepthKind)1>::mapInsSeq(this=0x000000016fdf9780, v=0x000000016fdf9f50, ctx=Context @ 0x000000016fdf9350) at treemap.h:528:13
    frame #29: 0x0000000100468014 sorbet`sorbet::ast::TreeMapper<sorbet::realmain::pipeline::(anonymous namespace)::CFGCollectorAndTyper, sorbet::core::Context, (sorbet::ast::TreeMapKind)1, (sorbet::ast::TreeMapDepthKind)1>::mapIt(this=0x000000016fdf9780, what=0x000000016fdf9f50, ctx=Context @ 0x000000016fdf9770) at treemap.h:691:28
    frame #30: 0x00000001004675b0 sorbet`void sorbet::ast::ShallowWalk::apply<sorbet::core::Context, sorbet::realmain::pipeline::(anonymous namespace)::CFGCollectorAndTyper>(ctx=Context @ 0x000000016fdf9a70, func=0x000000016fdf9a80, to=0x000000016fdf9f50) at treemap.h:782:20
    frame #31: 0x00000001004665c0 sorbet`sorbet::realmain::pipeline::(anonymous namespace)::typecheckOne(ctx=Context @ 0x000000016fdf9f60, resolved=ParsedFile @ 0x000000016fdf9f50, opts=0x000000016fdfcc20, intentionallyLeakASTs=true) at pipeline.cc:1500:13
    frame #32: 0x0000000100465844 sorbet`sorbet::realmain::pipeline::typecheck(sorbet::core::GlobalState const&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile>>, sorbet::realmain::options::Options const&, sorbet::WorkerPool&, bool, std::__1::optional<std::__1::shared_ptr<sorbet::core::lsp::PreemptionTaskManager>>, bool, bool)::$_1::operator()(this=0x00000007b4c14fc8) const at pipeline.cc:1592:37
    frame #38: 0x0000000100dd1824 sorbet`std::__1::function<void ()>::operator()(this=0x000000016fdfa4b8) const at function.h:1156:12
    frame #39: 0x00000001012e3a40 sorbet`sorbet::WorkerPoolImpl::multiplexJob(this=0x00000007b5034000, taskName="typecheck", t=sorbet::WorkerPool::Task @ 0x000000016fdfa4b8) at WorkerPoolImpl.cc:86:9
    frame #40: 0x0000000100413f84 sorbet`sorbet::realmain::pipeline::typecheck(gs=0x00000007b507c000, what=size=1, opts=0x000000016fdfcc20, workers=0x00000007b5034000, cancelable=false, preemptionManager= Has Value=false , presorted=false, intentionallyLeakASTs=true) at pipeline.cc:1565:21
    frame #41: 0x0000000100007094 sorbet`sorbet::realmain::realmain(argc=3, argv=0x000000016fdfe7c0) at realmain.cc:657:17
    frame #42: 0x0000000100001a5c sorbet`main(argc=3, argv=0x000000016fdfe7c0) at main.cc:6:16
    frame #43: 0x0000000189bb9d54 dyld`start + 7184
```

#### Expected behavior

Do not fail the `ENFORCE` check.

### PR DESCRIPTION
**Pull request by jez**
### Motivation

Fixes #10035

### Test plan

See included automated tests.

### CODE REVIEW

File: ast/Helpers.h [hunk 1]
```diff
@@ -551,9 +551,14 @@ class MK {
         const uint32_t length = "super"sv.size();
         auto superKeywordLoc = core::LocOffsets{loc.beginPos(), loc.beginPos() + length};
 
+        auto superLen = "super"sv.size();
+        auto funLoc = loc.beginPos() + superLen <= loc.endPos()
+                          ? core::LocOffsets(loc.beginPos(), loc.beginPos() + superLen)
+                          : loc.copyWithZeroLength();
```
Comment (froydnj) [inline ast/Helpers.h]: Some of this logic seems like it could be merged with the above calculation of `superKeywordLoc`?

```c++
auto funLoc = superKeywordLoc.endPos <= loc.endPos ? superKeywordLoc : loc.copyWithZeroLength();
```

seems a little more straightforward.

**Comment by jez** [comment]
> It is not immediately clear to me how this fixes the crash

The crash itself happened in the location when computing `argsLoc()`, where we would construct a loc whose `beginPos` was _after_ its `endPos`, an invariant that is only checked in ENFORCE builds. Attempting to use this loc (later in the pipeline) in production builds caused nonsensical indexing math, usually triggering some sort of crash.

The first fix (changing the funLoc of super) makes us not construct those known-bad locs, by changing it so that if both the funLoc and the block loc are present for `super`, it's not the case that the funLoc overlaps the block loc.

The second fix (changing argsLoc) is an admission that we probably won't be able to catch all such problems in the future (it is not generally an invariant we can rely on that funLoc is always before the blockLoc, and it would probably be too hard to introduce such an invariant).

File: ast/Helpers.h (hunk 1 above)
Comment (jez) [reply ast/Helpers.h]: oh wow, I completely missed that we were already constructing the superKeywordLoc.
