### PR TITLE
Desugar &. calls to use NilClass.===

### LINKED ISSUE #3276: Incorrect desugaring for &.foo
### Problem

```
[1] pry(main)> class A
[1] pry(main)*   def ==(other)
[1] pry(main)*     return true
[1] pry(main)*   end
[1] pry(main)* end
=> :==
[2] pry(main)> A.new&.to_s
=> "#<A:0x00007fbbd697e548>"
[3] pry(main)> class A
[3] pry(main)*   def nil?
[3] pry(main)*     true
[3] pry(main)*   end
[3] pry(main)* end
=> :nil?
[4] pry(main)> A.new&.to_s
=> "#<A:0x00007fbba68b14d8>"
```
### Proposed solution

We currently desugar `x&.to_s` to compare `x == nil`. It should instead desugar into `nil == x`

### PR DESCRIPTION
**Pull request by marianosimone**
This is an optimization that avoids potentially calling into an
arbitrary `==` for the object in which the safe navigation is being
used.

Fixes #3276

### CODE REVIEW

**Comment by marianosimone** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HcnDS16BSZLzWa

**Comment by marianosimone** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HcndJCD7ElEkTE

File: test/testdata/lsp/hover_ampersand_operations.rb [hunk 1]
```diff
@@ -18,13 +18,6 @@ def main
                     # ^ hover: sig {returns(String)}
 
   # Safenav
-  dog = Dog.new
-  breed = dog&.breed
```
Comment (DarkDimius) [inline test/testdata/lsp/hover_ampersand_operations.rb:22]: Let's update the test rather then deleting it?

Comment (marianosimone) [reply test/testdata/lsp/hover_ampersand_operations.rb:22]: Mh... but this test is for hover on ampersand operations... and this case no longer requires an ampersand operation (which results in an error, instead of hover information)

Should we have a different test somewhere else that test for an error being shown instead?

Comment (DarkDimius) [reply test/testdata/lsp/hover_ampersand_operations.rb:22]: > (which results in an error, instead of hover information)

it should have _both_ an error and support hover on it.

Comment (marianosimone) [reply test/testdata/lsp/hover_ampersand_operations.rb:22]: Done!

**Comment by marianosimone** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_HcowvXPC5a2jO4

File: test/testdata/lsp/hover_ampersand_operations.rb [hunk 2]
```diff
@@ -39,4 +49,13 @@ def main
...
                      # ^ hover: sig {returns(String)}
+
+                    
+
+  # Examples of where the detection of dead branch loc is "weird" to me
+  str_breed = dog.breed&.to_s # here the unreachable is at dog, which is not close to the &
+  cat_breed = Animal::Cat.new&.breed # here the unreachable code is at Animal
+  maybe_dog_breed_forced = T.must(maybeDog)&.breed # here the unreachable code is at T
+  @dog = dog
+  own_dog_breed = @dog&.breeed # here the unreachable code is at @
```
Comment (jez) [inline test/testdata/lsp/hover_ampersand_operations.rb:60]: Since these aren't LSP-related they should probably live in their own test file in `test/testdata/desugar`. Having small test cases are nice, because they run more quickly and are easier to put under a debugger. And not putting them in LSP makes it clear that this feature is not impacted by LSP in any way.

Comment (marianosimone) [reply test/testdata/lsp/hover_ampersand_operations.rb:60]: Yeah, these were not intended to be here at all.. I just pushed them so you had a reproducible case. If we end up deciding to merge this PR w/o the autocorrector, I'll just remove the latest commit and can report these bugs as a separate issue.
