### PR TITLE
runtime: Fix sig block deletion race

### LINKED ISSUE #1386: sorbet-runtime crashes when two threads call the same wrapped method
#### Input

```ruby
require 'sorbet-runtime'

loop do
  klass = Class.new do
    extend T::Sig
    sig {void}
    def self.hello
    end
  end

  t1 = Thread.new do
    1000.times do
      klass.hello
    end
  end

  t2 = Thread.new do
    1000.times do
      klass.hello
    end
  end

  t1.join
  t2.join
end
```

#### Observed output

```
No `sig` wrapper for #<UnboundMethod: #<Class:#<Class:0x00007fa1062bb4a8>>#hello> (RuntimeError)
```

#### Expected behavior

Program loops forever.

---

It looks like we need synchronization around https://github.com/sorbet/sorbet/blob/8014895b2562273fee34dc81d468cd30817b9ff7/gems/sorbet-runtime/lib/types/private/methods/_methods.rb#L352

### PR DESCRIPTION
**Pull request by XrXr**
When two threads commit to calling the the same wrapper and
one thread deletes the sig block from the `sig_wrappers` hash
before the other one does the look up, sorbet-runtime raises.

Fix this issue by checking whether the sig block was already
evaluated when it is missing from the sig_wrappers hash.

Fixes #1386

### Motivation
This is making CI flaky for us.

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by XrXr** [comment]
hm, I think while this PR gets rid of the error, there is double wrapping happening when there was an exception happening before. I would say it's an improvement but it's not perfect...

File: gems/sorbet-runtime/test/types/edge_cases.rb [hunk 1]
```diff
@@ -297,4 +297,17 @@ def foo; end
     assert_match(/A previous invocation of #<UnboundMethod: /, e.message)
   end
 
+  it 'does not crash when two threads call the same wrapper' do
+    5000.times do
```
Comment (DarkDimius) [inline gems/sorbet-runtime/test/types/edge_cases.rb]: could locks or some other control primitive be used to reproduce the error reliably?

Comment (XrXr) [reply gems/sorbet-runtime/test/types/edge_cases.rb]: I can't think of a good way to do it since it requires very fine grained scheduling of the two threads inside sorbet-runtime's code. I suppose it's possible with some monkey patching but I think at that point it's not worth it.

This test takes one second to run right now, which is okay to me. I can remove it if it's a concern.

Comment (XrXr) [reply gems/sorbet-runtime/test/types/edge_cases.rb]: I came up with 90ae979 which uses a barrier + a mutex + monkey patching to consistently reproduce the race. Not problem free of course, since this is now white box testing. If the wrapper code stops calling `run_sig_block_for_method` one day the test will lose value, and this also adds a development dependency on concurrent-ruby.

Let me know what you think.

File: gems/sorbet-runtime/sorbet-runtime.gemspec [hunk 2]
```diff
@@ -13,4 +13,5 @@ Gem::Specification.new do |s|
   s.add_development_dependency 'minitest', '~> 5.11'
   s.add_development_dependency 'mocha', '~> 1.7'
   s.add_development_dependency 'rake'
+  s.add_development_dependency 'concurrent-ruby', '~> 1.1.5'
```
Comment (DarkDimius) [inline gems/sorbet-runtime/sorbet-runtime.gemspec]: could you add a comment that indicates what it's for?

File: gems/sorbet-runtime/lib/types/private/methods/_methods.rb [hunk 3]
```diff
@@ -345,13 +345,18 @@ def self.maybe_run_sig_block_for_method(method)
...
 
-  private_class_method def self.run_sig_block_for_key(key)
+  private_class_method def self.run_sig_block_for_key(key, sig_block = nil)
     blk = @sig_wrappers[key]
-    if !blk
+    if sig_block
+      if blk && blk != sig_block
+        raise "Bug: `sig` wrapper for #{key_to_method(key)} stored with wrong key"
+      end
+      blk = sig_block
```
Comment (jez) [inline gems/sorbet-runtime/lib/types/private/methods/_methods.rb]: Is this line redundant? I think at this point `!(blk != sig_block)`?

File: gems/sorbet-runtime/lib/types/private/methods/_methods.rb [hunk 4]
```diff
@@ -345,13 +345,18 @@ def self.maybe_run_sig_block_for_method(method)
...
-    run_sig_block_for_key(method_to_key(method))
+  def self.run_sig_block_for_method(method, sig_block)
+    run_sig_block_for_key(method_to_key(method), sig_block)
   end
 
-  private_class_method def self.run_sig_block_for_key(key)
+  private_class_method def self.run_sig_block_for_key(key, sig_block = nil)
     blk = @sig_wrappers[key]
-    if !blk
+    if sig_block
```
Comment (DarkDimius) [inline gems/sorbet-runtime/lib/types/private/methods/_methods.rb]: I don't understand this code either. 
The code seems to always use `blk` below and even while it takes `sig_block` it checks that they are the same. Thus it seems equivalent to old code.
Am I missing something?

**Comment by XrXr** [comment]
The only thing important to the fix was `blk = sig_block if !blk` but I complicated it with a sanity test. I've removed all but the essentials.

File: gems/sorbet-runtime/lib/types/private/methods/_methods.rb (hunk 3 above)
Comment (XrXr) [reply gems/sorbet-runtime/lib/types/private/methods/_methods.rb]: Should be more clear now hopefully! The sanity test I had complicated things too much.

**Comment by XrXr** [comment]
It's now clear to me that any caller that do not pass `sig_block` suffers from same race this PR addresses for the plain case. So override / abstract validation, `T::Utils.register_forwarder`, `T::Utils.run_all_sig_blocks` all use `maybe_run_sig_block_for_key` which doesn't pass a sig_block which suffers from this race.

Kind of a systemic problem, but one step at a time, I guess...
