### PR TITLE
Track indexing errors on files, instead of only parse errors

### LINKED ISSUE #8263: anonymous rest parameter check only fails on first run of type check or after removing sorbet cache
I think the new anonymous rest parameter check is somehow caching information and not correctly evaluating on successive runs. I get reported errors on the first run of a type check, and not on successive runs. If I remove the `tmp/cache/sorbet` directory, the error appears again, but only for one execution. It does not happen for other errors.

I added the following file `foo.rb` at the project top level:

```ruby
def foo
  [1,2,3].each do |*|
    puts "test"
  end
end
```

Then I ran the type check and got the expected error:

```console
❯❯❯ bin/srb tc
foo.rb:2: Anonymous rest parameter in block args https://srb.help/3012
     2 |  [1,2,3].each do |*|
                           ^
  Note:
    Naming the rest parameter will ensure you can access it in the block
  Autocorrect: Use -a to autocorrect
    foo.rb:2: Insert _
     2 |  [1,2,3].each do |*|
                            ^
Errors: 1
```

Ran it again two more times, no errors:

```console
❯❯❯ bin/srb tc
No errors! Great job.
❯❯❯ bin/srb tc
No errors! Great job.
```

Remove the cache and run it again, get the error again:

```console
❯❯❯ rm -rf tmp/cache/sorbet
❯❯❯ bin/srb tc
foo.rb:2: Anonymous rest parameter in block args https://srb.help/3012
     2 |  [1,2,3].each do |*|
                           ^
  Note:
    Naming the rest parameter will ensure you can access it in the block
  Autocorrect: Use -a to autocorrect
    foo.rb:2: Insert _
     2 |  [1,2,3].each do |*|
                            ^
Errors: 1
```

### PR DESCRIPTION
**Pull request by elliottt**
Instead of tracking only parse errors on files, track whether or not errors were raised during the indexing phase of the pipeline. This allows errors during the desugar, rewriter, and local_vars passes to also prevent the file from being cached.

### Motivation
Fixes #8263

### Test plan

See included automated tests.

### CODE REVIEW

File: parser/Parser.cc [hunk 1]
```diff
@@ -149,7 +149,6 @@ unique_ptr<Node> Parser::run(core::GlobalState &gs, core::FileRef file, Parser::
     // report the hints. Always reporting the original parse errors ensures that the user can always
     // see the real cause in case the hints are misleading.
     if (!driver->diagnostics.empty()) {
-        file.data(gs).setHasParseErrors(true);
```
Comment (elliottt) [inline parser/Parser.cc:152]: It's not necessary to remove this, but it did seem redundant with the processing in pipeline.cc at this point.

File: test/cli/errors-skip-cache/test.rb
Comment (jez) [inline test/cli/errors-skip-cache/test.rb:1]: Can we audit every call to `beginError` in desugar, rewriter, and local_vars and see whether they report errors that look like they mutate the trees?

For example, in #8263 I mentioned some other test cases that this logic would fix—let's make sure that this fixes them by adding tests. In that comment I stopped after I saw a handful of similar errors, just to make the case that the root cause was not just the new "Anonymous rest paramater" error. There are probably more errors which suffered from this behavior and I think it would be good to have a test for them.

The way I would do it would be to have one `*.rb` file per error in this CLI test directory.

File: test/cli/errors-skip-cache/test.sh [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+
+mkdir "$dir/cache"
+
+run_sorbet() {
+  # Ideally this would include counters output so that we could verify the cache
+  # miss, but there are a lot of unstable metrics in the counters output, and
+  # filtering it means that we'll lose the errors that duplicate across sorbet
+  # invocations.
+  #
+  # TODO(trevor): update this to include counter output if we fix `--counter`
```
Comment (jez) [inline test/cli/errors-skip-cache/test.sh:18]: I don't think that this actually matters so much—if we were to make a change to the cache such that we actually *were* able to have a cache hit but still have the errors show up on the warm cache, we wouldn't actually care to enforce that there _must_ be a cache miss on this example.

That is, I think that the structure of this test is sufficiently fine, absent the `--counter` flag not working.

File: main/lsp/requests/completion.cc [hunk 3]
```diff
@@ -1276,7 +1276,7 @@ unique_ptr<ResponseMessage> CompletionTask::runRequest(LSPTypecheckerDelegate &t
         if (enableTypedFalseCompletionNudges) {
             ENFORCE(fref.exists());
             auto level = fref.data(gs).strictLevel;
-            if (!fref.data(gs).hasParseErrors() && level < core::StrictLevel::True) {
+            if (!fref.data(gs).hasIndexErrors() && level < core::StrictLevel::True) {
```
Comment (jez) [inline main/lsp/requests/completion.cc:1279]: This is one place where the change in behavior could affect things. We should audit this call site and see whether this causes problems for whatever completion.cc was trying to use this bit for.

File: infer/environment.cc
Comment (jez) [inline infer/environment.cc:1]: Honestly the two calls to `hasParseErrors` here seem suspect? I'm not sure what they're doing (and wouldn't we want to assign a location no matter whether the file had parse errors? is there some reason why that's not possible?)

It might be worth trying to delete that part of the `ENFORCE` condition on master and seeing what tests fail.

File: main/pipeline/pipeline.cc [hunk 4]
```diff
@@ -200,6 +200,12 @@ ast::ParsedFile indexOne(const options::Options &opts, core::GlobalState &lgs, c
             if (opts.stopAfterPhase == options::Phase::PARSER) {
                 return emptyParsedFile(file);
             }
+
+            // As the parser does some management of errors that can be recovered from, we consider the count of errors
+            // that could render the file uncacheable to start after it's finished. The parser is responsible
+            // for managing the `hasIndexErrors` flag on the file up to this point.
+            auto initialErrors = lgs.totalErrors();
```
Comment (jez) [inline main/pipeline/pipeline.cc:207]: From Slack, capturing for posterity:

> I do not think we should be solving this in pipeline.cc
>
> I think we should probably be solving this somewhere like `GlobalState::_error` and looking at the error code, checking to see whether `error->what->code < 4000` and calling `setHasIndexErrors` there.

**Review by jez — CHANGES_REQUESTED** [review]
Done leaving comments for now, lmk when you'd like another look.

File: parser/Parser.cc (hunk 1 above)
Comment (jez) [reply parser/Parser.cc:152]: I believe that this *does* become redundant with the other changes in this PR if you use the `GlobalState::_error` approach described in another comment.

If that's not the case, I'd love to dig into why it's not the case.

File: test/cli/errors-skip-cache/test.rb
Comment (elliottt) [reply test/cli/errors-skip-cache/test.rb:1]: I went through all the call-sites that I changed to `beginIndexerError`, and added files that corresponded roughly to that class of error in `test/cli/errors-skip-cache`.

File: test/cli/errors-skip-cache/test.sh (hunk 2 above)
Comment (elliottt) [reply test/cli/errors-skip-cache/test.sh]: I've removed the comment.

File: main/lsp/requests/completion.cc (hunk 3 above)
Comment (elliottt) [reply main/lsp/requests/completion.cc:1279]: This seems a little not great: it will only show the typed-false nudge when the file would already pass all the checks in the indexer. Maybe it's worth tracking parse errors and indexer errors as two separate flags on the `File`?

Comment (elliottt) [reply main/lsp/requests/completion.cc]: I added this behavior, with the relationship that parse errors imply indexer errors. This means that we can keep the existing behavior of nudging when the file parses, but skipping the cache when there are any errors added during indexing.

File: infer/environment.cc
Comment (elliottt) [reply infer/environment.cc:1]: The only test that triggers this error is `crash_after_parse_errors.rb`. It seems that the partial parse of the lambda at `->e` introduces the variable `e`, and then recovers by removing it. As a result, the use of `hasParserErrors` in the ENFORCEs is working around the fact that the `r=e` bindings are referencing lambda variables that no longer exist. (Two uses of `e` is significant, because the first one gets it into the `_vars` map with no origins, and the second actually uses it and triggers the ENFORCE.)

I think we should make a separate ticket about fixing the parser and removing these unnecessary guards on the ENFORCEs.

File: main/lsp/requests/completion.cc (hunk 3 above)
Comment (jez) [reply main/lsp/requests/completion.cc]: If this is the only reason why you started to track hasParseErrors and hasIndexErrors, I think it might be worth not going to that trouble.

The original context for this is that sometimes we would give people a completion item seeming to claim that if they upgraded their file to `# typed: true`, they would get completion results.

But in cases where the entire file failed to parse, or parsed but in a way that dropped a ton of context from the tree, we didn't want to show that completion result for fear of misleading the user.

In this case, I think that if for example you tried to get completion results on `X| &&= 0`, this **also** would have made the parse be `EmptyTree`, and thus Sorbet would see no query responses, and would report this error. As you can see, this is [already a problem on master](https://sorbet.run/#%23%20typed%3A%20false%0A%0AXZY%20%3D%201%0A%0AXY%20%26%26%3D%201):

image

So I actually think that there's probably value in just having this callsite say `hasIndexErrors`.

File: test/cli/errors-skip-cache/test.sh [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+dir=$(mktemp -d)
+cleanup() {
+    rm -r "$dir"
+}
+trap cleanup EXIT
+
+mkdir "$dir/cache"
+
+run_sorbet() {
+  set -x
```
Comment (jez) [inline test/cli/errors-skip-cache/test.sh:13]: Why not have this at the top-level?

Comment (elliottt) [reply test/cli/errors-skip-cache/test.sh:13]: Ah, I was using that to debug, and should not have included it. Thank you for catching that!

File: core/Context.cc [hunk 6]
```diff
@@ -56,6 +56,9 @@ Loc MutableContext::locAt(LocOffsets offsets) const {
 ErrorBuilder MutableContext::beginError(LocOffsets loc, ErrorClass what) const {
     return state.beginError(Loc(file, loc), what);
 }
+ErrorBuilder MutableContext::beginIndexerError(LocOffsets loc, ErrorClass what) const {
+    return state.beginIndexerError(Loc(file, loc), what);
```
Comment (jez) [inline core/Context.cc:60]: This duplicates less code.

```suggestion
        if (what.code < 4000) {
        // As errors from the indexing phase control whether or not we should cache trees, we set this flag on the file
        // even if the erorr would be suppressed, to ensure that the experience when the cache is enabled is consistent.
        this->file.data(*this).setHasIndexErrors(true);

        // All parse errors are index errors, but not all index errors are parse errors.
        if (what.code < 3000) {
            this->file.data(*this).setHasParseErrors(true);
        }
    }

    return this->beginError(loc, what);
```

File: core/GlobalState.cc [hunk 7]
```diff
@@ -2302,6 +2302,25 @@ ErrorBuilder GlobalState::beginError(Loc loc, ErrorClass what) const {
...
+
+        // All parse errors are index errors, but not all index errors are parse errors.
+        if (what.code < 3000) {
+            loc.file().data(*this).setHasParseErrors(true);
+        }
+    }
+
+    return ErrorBuilder(*this, shouldReportErrorOn(loc, what), loc, what);
+}
+
```
Comment (jez) [inline core/GlobalState.cc:2323]:
```suggestion
```

For if you take the other suggestion.

File: core/Context.h [hunk 8]
```diff
@@ -67,6 +67,7 @@ class MutableContext final {
     MutableContext withOwner(SymbolRef sym) const;
     MutableContext withFile(FileRef file) const;
     ErrorBuilder beginError(LocOffsets loc, ErrorClass what) const;
+    ErrorBuilder beginIndexerError(LocOffsets loc, ErrorClass what) const;
```
Comment (jez) [inline core/Context.h:70]:
```suggestion
    // A version of `beginError` that's specific to the index phase of the pipeline, as it will record that index errors
    // have been seen on the file associated with the loc.
    ErrorBuilder beginIndexerError(LocOffsets loc, ErrorClass what) const;
```

File: main/pipeline/pipeline.cc [hunk 9]
```diff
@@ -200,6 +200,7 @@ ast::ParsedFile indexOne(const options::Options &opts, core::GlobalState &lgs, c
             if (opts.stopAfterPhase == options::Phase::PARSER) {
                 return emptyParsedFile(file);
             }
+
```
Comment (jez) [inline main/pipeline/pipeline.cc:203]:
```suggestion
``` 

Looks like a stray edit?

Comment (elliottt) [reply main/pipeline/pipeline.cc:203]: Yep, forgot to remove that after removing the changes that I introduced earlier to track indexer errors in pipeline.cc.

File: main/lsp/requests/completion.cc (hunk 3 above)
Comment (elliottt) [reply main/lsp/requests/completion.cc]: Yep, that was the only reason. I'll back that change out, which I think is nice as we no longer have to think about maintaining the `parse errors => index errors` relationship.

File: infer/environment.cc
Comment (elliottt) [reply infer/environment.cc:1]: #8269 should fix this.

**Comment by elliottt** [comment]
@jez, I ended up moving the `beginIndexerError` method back to `GlobalState`, as it was necessary for recording errors in the parser builder (which only has a `GlobalState` and `FileRef` available).

**Comment by jez** [comment]
> @jez, I ended up moving the `beginIndexerError` method back to `GlobalState`, as it was necessary for recording errors in the parser builder (which only has a `GlobalState` and `FileRef` available).

Ah, sorry about that, didn't realize.

**Review by jez — APPROVED** [review]
