### PR TITLE
Validate `type_member` args before symbol manipulation

### LINKED ISSUE #6780: ENFORCE failure when giving extra arg to `type_member`
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20X%20%3D%20type_member%28%3Aout%2C%20%3Aextra%29%0Aend)

```ruby
# typed: true

class A
  extend T::Generic

  X = type_member(:out, :extra)
end
```

#### Observed output

```
editor.rb:6: Too many args in type definition https://srb.help/4011
     6 |  X = type_member(:out, :extra)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

**Note** The above is what sorbet.run shows, but it doesn't run ENFORCEs. This is what a debug build shows:

```
❯ sorbet foo.rb
Exception::raise(): namer/namer.cc:1968 enforced condition sym.exists() has failed: (no message provided)

Backtrace:
  #3 0xbc09f2
  #4 0x13cf752 sorbet::namer::(anonymous namespace)::TreeSymbolizer::handleTypeMemberDefinition()
  #5 0x13ce69b sorbet::namer::(anonymous namespace)::TreeSymbolizer::postTransformAssign()
  #6 0x13ce3ba sorbet::ast::MapFunctions<>::CALL_MEMBER_impl_postTransformAssign<>::call<>()
  #7 0x13cb4ae sorbet::ast::TreeMapper<>::mapAssign()
  #8 0x13ca290 sorbet::ast::TreeMapper<>::mapIt()
  #9 0x13caafa sorbet::ast::TreeMapper<>::mapClassDef()
  #10 0x13c9c2b sorbet::ast::TreeMapper<>::mapIt()
  #11 0x13caafa sorbet::ast::TreeMapper<>::mapClassDef()
  #12 0x13c9c2b sorbet::ast::TreeMapper<>::mapIt()
  #13 0x13c97aa sorbet::ast::TreeWalk::apply<>()
  #14 0x13c94b8 sorbet::namer::(anonymous namespace)::symbolizeTrees()::$_5::operator()()
  #15 0x13c916d std::__1::__invoke<>()
  #16 0x13c911d std::__1::__invoke_void_return_wrapper<>::__call<>()
  #17 0x13c90ed std::__1::__function::__alloc_func<>::operator()()
  #18 0x13c82a9 std::__1::__function::__func<>::operator()()
  #19 0x1768642 std::__1::__function::__value_func<>::operator()()
  #20 0x175eee5 std::__1::function<>::operator()()
  #21 0x1bf0733 sorbet::WorkerPoolImpl::multiplexJob()
  #22 0x139f2cc sorbet::namer::(anonymous namespace)::symbolizeTrees()
  #23 0x139db7e sorbet::namer::Namer::runInternal()
  #24 0x139f700 sorbet::namer::Namer::run()
  #25 0xf5e746 sorbet::realmain::pipeline::name()
  #26 0xf5ee31 sorbet::realmain::pipeline::resolve()
  #27 0xbb2569 sorbet::realmain::realmain()
  #28 0xbace42 main
  #29 0x7f4590203083 __libc_start_main
  #30 0xbacd4e _start

Exception::raise(): ast/Trees.cc:91 enforced condition ptr != nullptr has failed: (no message provided)

Backtrace:
  #3 0xbc09f2
  #4 0x18dd364 sorbet::ast::ExpressionPtr::loc()
  #5 0x13ca1e1 sorbet::ast::TreeMapper<>::mapIt()
  #6 0x13caafa sorbet::ast::TreeMapper<>::mapClassDef()
  #7 0x13c9c2b sorbet::ast::TreeMapper<>::mapIt()
  #8 0x13caafa sorbet::ast::TreeMapper<>::mapClassDef()
  #9 0x13c9c2b sorbet::ast::TreeMapper<>::mapIt()
  #10 0x13c97aa sorbet::ast::TreeWalk::apply<>()
  #11 0x13c94b8 sorbet::namer::(anonymous namespace)::symbolizeTrees()::$_5::operator()()
  #12 0x13c916d std::__1::__invoke<>()
  #13 0x13c911d std::__1::__invoke_void_return_wrapper<>::__call<>()
  #14 0x13c90ed std::__1::__function::__alloc_func<>::operator()()
  #15 0x13c82a9 std::__1::__function::__func<>::operator()()
  #16 0x1768642 std::__1::__function::__value_func<>::operator()()
  #17 0x175eee5 std::__1::function<>::operator()()
  #18 0x1bf0733 sorbet::WorkerPoolImpl::multiplexJob()
  #19 0x139f2cc sorbet::namer::(anonymous namespace)::symbolizeTrees()
  #20 0x139db7e sorbet::namer::Namer::runInternal()
  #21 0x139f700 sorbet::namer::Namer::run()
  #22 0xf5e746 sorbet::realmain::pipeline::name()
  #23 0xf5ee31 sorbet::realmain::pipeline::resolve()
  #24 0xbb2569 sorbet::realmain::realmain()
  #25 0xbace42 main
  #26 0x7f4590203083 __libc_start_main
  #27 0xbacd4e _start

foo.rb:3: Failed to process tree (backtrace is above) https://srb.help/1001
     3 |class A
     4 |  extend T::Generic
     5 |
     6 |  X = type_member(:out, :extra)
     7 |end

???: Exception resolving (backtrace is above) https://srb.help/1001
Errors: 2

```

#### Expected behavior

Sorbet should not crash.

- - -

### PR DESCRIPTION
**Pull request by jwinr**
Sorbet was crashing before it could even hit the "Too many args in type definition" error because it was using `ENFORCE` to assume the type member symbol exists and updates `asgn.lhs` to reference it before it even does the check for the number of positional arguments. This change modifies the `handleTypeMemberDefinition` method in `namer.cc` so that the validation step happens before any symbol manipulation.

### Motivation
Fixes #6780: "ENFORCE failure when giving extra arg to type_member"

### Test plan

See included automated tests.

### CODE REVIEW

**Review by jez — APPROVED** [review]
This is great, thanks!

File: namer/namer.cc [hunk 1]
```diff
@@ -2020,6 +2020,20 @@ class TreeSymbolizer {
...
+        if (send->hasPosArgs() || send->hasKwArgs() || send->block() != nullptr) {
+            if (send->numPosArgs() > 1) {
+                if (auto e = ctx.beginError(send->loc, core::errors::Namer::InvalidTypeDefinition)) {
+                    e.setHeader("Too many args in type definition");
+                }
+                auto send = ast::MK::Send0Block(asgn.loc, ast::MK::T(asgn.loc), core::Names::typeAlias(),
+                                                asgn.loc.copyWithZeroLength(),
+                                                ast::MK::Block0(asgn.loc, ast::MK::Untyped(asgn.loc)));
+                return handleAssignment(
+                    ctx, ast::make_expression<ast::Assign>(asgn.loc, std::move(asgn.lhs), std::move(send)));
```
Comment (jez) [inline namer/namer.cc:2033]: For consistency, we usually like to use the helpers in ast/Helpers.h, so this would be ast::MK::Assign(…)

You can also get away with not using std:: on the calls to move if you want.

File: namer/namer.cc [hunk 2]
```diff
@@ -2020,6 +2020,20 @@ class TreeSymbolizer {
             }
         }
 
+        // Prevent a crash by validating the arguments before we do any symbol lookups or manipulations
+        if (send->hasPosArgs() || send->hasKwArgs() || send->block() != nullptr) {
+            if (send->numPosArgs() > 1) {
+                if (auto e = ctx.beginError(send->loc, core::errors::Namer::InvalidTypeDefinition)) {
+                    e.setHeader("Too many args in type definition");
+                }
+                auto send = ast::MK::Send0Block(asgn.loc, ast::MK::T(asgn.loc), core::Names::typeAlias(),
```
Comment (jez) [inline namer/namer.cc:2029]: The fact that this didn’t work before (it was using Send1) indicates we might also want to have something in the test that uses the untyped constant (e.g. use `X` in the test below in a signature of a method and use T.reveal_type to check that it gets treated as T.untyped)

File: namer/namer.cc [hunk 3]
```diff
@@ -2020,6 +2020,20 @@ class TreeSymbolizer {
             }
         }
 
+        // Prevent a crash by validating the arguments before we do any symbol lookups or manipulations
+        if (send->hasPosArgs() || send->hasKwArgs() || send->block() != nullptr) {
+            if (send->numPosArgs() > 1) {
+                if (auto e = ctx.beginError(send->loc, core::errors::Namer::InvalidTypeDefinition)) {
+                    e.setHeader("Too many args in type definition");
```
Comment (jez) [inline namer/namer.cc:2027]: This error message could be a little better:

- ideally it mentions “type member” or “type template” because there are other ways to define types than just generic types
- Ideally the error header interpolates the name of the bad constant somewhere
- Ideally, there’s an autocorrect to delete the extra arguments, using e.replaceWith (to either replace the extra arguments with `""` or to replace all the arguments with the first argument (the latter handles the edge case of also deleting any comma between arg 1 and 2)

File: namer/namer.cc [hunk 4]
```diff
@@ -2020,6 +2020,20 @@ class TreeSymbolizer {
             }
         }
 
+        // Prevent a crash by validating the arguments before we do any symbol lookups or manipulations
+        if (send->hasPosArgs() || send->hasKwArgs() || send->block() != nullptr) {
+            if (send->numPosArgs() > 1) {
+                if (auto e = ctx.beginError(send->loc, core::errors::Namer::InvalidTypeDefinition)) {
```
Comment (jez) [inline namer/namer.cc:2026]: Ideally this error location would point to the bad arguments, not the whole method call, like what you would get for a normal “too many arguments provided to method” error

**Review by jez — COMMENTED** [review]
For sake of completeness, I’ve pointed out some things that aren’t great about this part of the codebase that predate your fix, in case you wanted to address them too.

**Comment by jez** [comment]
Your change will auto merge when the tests pass, so if you feel like it, go ahead and make the follow up fixes in a new PR.

**Comment by jwinr** [comment]
> For sake of completeness, I’ve pointed out some things that aren’t great about this part of the codebase that predate your fix, in case you wanted to address them too.

I'll get to it as soon as I can. Thanks for the in-depth review!
