### PR TITLE
Parse type members as SelfTypeParam, and unwrap them later

### LINKED ISSUE #206: Segfault when intersecting interface and generics
https://sorbet.run/#module%20Interface%0A%20%20extend(T%3A%3ASig)%0A%20%20interface!%0Aend%0A%0Aclass%20Klass%0A%20%20R%20%3D%20type_member%0A%20%20%0A%20%20sig%20%7B%20params(params%3A%20T.all(R%2C%20Interface)).void%20%7D%0A%20%20def%20foo(params)%0A%20%20end%0Aend

```ruby
module Interface
  extend(T::Sig)
  interface!
end

class Klass
  R = type_member
  
  sig { params(params: T.all(R, Interface)).void }
  def foo(params)
  end
end
```

### PR DESCRIPTION
**Pull request by elliottt**
`Types::all` will raise an error in `glbGround` if a bare `LambdaParam` is passed in, which is the case when parsing type member references in a signature. This PR changes the behavior of the signature parser to instead produce a `SelfTypeParam`, avoiding issues with `Types::all`. At the end of type parsing, the type is traversed again, turning `SelfTypeParam` occurrences back into bare `LambdaParams`, so that they will behave as expected during instantiation.

### Motivation

Fixes #206 

### Test plan

See included automated tests.

### CODE REVIEW

File: core/Types.h [hunk 1]
```diff
@@ -160,6 +160,9 @@ class Types final {
     static TypePtr widen(Context ctx, const TypePtr &type);
     static std::optional<int> getProcArity(const AppliedType &type);
 
+    /** Unwrap SelfTypeParam instances that belong to the given owner, to a bare LambdaParam */
+    static TypePtr unwrapSkolemVariables(Context ctx, const TypePtr &ty);
```
Comment (DarkDimius) [inline core/Types.h]: the word `Skolem` has waay to many meanings and this is the first time it's used.
WDYT about `unwrapSelfTypeParams`?

File: core/types/types.cc [hunk 2]
```diff
@@ -859,6 +859,66 @@ TypePtr Types::widen(Context ctx, const TypePtr &type) {
...
+        [&](SelfTypeParam *param) {
+            auto sym = param->definition;
+            if (sym.data(ctx)->owner == ctx.owner) {
+                ENFORCE(cast_type<LambdaParam>(sym.data(ctx)->resultType.get()) != nullptr);
+                ret = sym.data(ctx)->resultType;
+            } else {
+                ret = type;
+            }
+        },
+        [&](Type *tp) { ret = type; });
```
Comment (DarkDimius) [inline core/types/types.cc]: WDYT about making default  do `Exception::notImplemented`?

File: core/Types.h (hunk 1 above)
Comment (elliottt) [reply core/Types.h]: Good point, I'll make that change. Thanks!

File: core/types/types.cc (hunk 2 above)
Comment (elliottt) [reply core/types/types.cc]: I think that's a good idea. I'll make that change, and add the missing cases.

**Comment by elliottt** [comment]
The test failures are due to a mismatch between pipeline.cc and test_corpus.cc. One is running a pass that the other is not, and as a result test_corpus.cc sees empty sig blocks.

**Comment by elliottt** [comment]
> The test failures are due to a mismatch between pipeline.cc and test_corpus.cc. One is running a pass that the other is not, and as a result test_corpus.cc sees empty sig blocks.

This wasn't accurate: the real problem was that signature parsing sometimes leaves the `returns` field of `ParsedSig` as `nullptr`, and I should have only been calling `unwrapSelfTypeParam` when it was present.

File: core/types/types.cc [hunk 3]
```diff
@@ -859,6 +859,70 @@ TypePtr Types::widen(Context ctx, const TypePtr &type) {
     return ret;
 }
 
+TypePtr Types::unwrapSelfTypeParam(Context ctx, const TypePtr &type) {
+    ENFORCE(type != nullptr);
+
+    TypePtr ret;
+
+    typecase(
+        type.get(), [&](ClassType *klass) { ret = type; }, [&](TypeVar *tv) { ret = type; },
```
Comment (dmitry-stripe) [inline core/types/types.cc]: /me angry at formatter

Comment (elliottt) [reply core/types/types.cc]: me too!
