### PR TITLE
Don't get arg info for non-existent method symbols

### LINKED ISSUE #1258: (From Fuzzer) core/Symbols.cc:119 enforced condition this->exists() has failed
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23typed%3Astrict%0Adef%20c%28x%29b%28x%29end)

```ruby
#typed:strict
def c(x)b(x)end
```

#### Observed output

```
Exception::raise(): core/Symbols.cc:119 enforced condition this->exists() has failed: (no message provided)

Backtrace:
sorbet::Exception::enforce_handler(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int) (in librealmain.so) (Exception.h:47)
sorbet::core::SymbolRef::data(sorbet::core::GlobalState const&) const (in libcore.so) (Symbols.cc:119)
sorbet::infer::(anonymous namespace)::extractArgType(sorbet::core::Context, sorbet::cfg::Send&, sorbet::core::DispatchComponent&, int) (in libinfer.so) (SigSuggestion.cc:103)
sorbet::infer::(anonymous namespace)::extractSendArgumentKnowledge(sorbet::core::Context, sorbet::core::Loc, sorbet::cfg::Send*, absl::flat_hash_map<sorbet::core::LocalVariable, absl::InlinedVector<sorbet::core::NameRef, 1ul, std::__1::allocator<sorbet::core::NameRef> >, absl::hash_internal::Hash<sorbet::core::LocalVariable>, std::__1::equal_to<sorbet::core::LocalVariable>, std::__1::allocator<std::__1::pair<sorbet::core::LocalVariable const, absl::InlinedVector<sorbet::core::NameRef, 1ul, std::__1::allocator<sorbet::core::NameRef> > > > > const&, absl::flat_hash_map<sorbet::core::NameRef, sorbet::core::TypePtr, absl::hash_internal::Hash<sorbet::core::NameRef>, std::__1::equal_to<sorbet::core::NameRef>, std::__1::allocator<std::__1::pair<sorbet::core::NameRef const, sorbet::core::TypePtr> > >&) (in libinfer.so) (SigSuggestion.cc:149)
sorbet::infer::(anonymous namespace)::guessArgumentTypes(sorbet::core::Context, sorbet::core::SymbolRef, std::__1::unique_ptr<sorbet::cfg::CFG, std::__1::default_delete<sorbet::cfg::CFG> >&) (in libinfer.so) (SigSuggestion.cc:234)
sorbet::infer::SigSuggestion::maybeSuggestSig(sorbet::core::Context, sorbet::core::ErrorBuilder&, std::__1::unique_ptr<sorbet::cfg::CFG, std::__1::default_delete<sorbet::cfg::CFG> >&, sorbet::core::TypePtr const&, sorbet::core::TypeConstraint&) (in libinfer.so) (SigSuggestion.cc:395)
sorbet::infer::Inference::run(sorbet::core::Context, std::__1::unique_ptr<sorbet::cfg::CFG, std::__1::default_delete<sorbet::cfg::CFG> >) (in libinfer.so) (inference.cc:216)
sorbet::realmain::pipeline::CFGCollectorAndTyper::preTransformMethodDef(sorbet::core::Context, std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >) (in libpipeline.so) (pipeline.cc:54)
sorbet::ast::PostPonePreTransform_MethodDef<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context, true>::call(sorbet::core::Context, std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >, sorbet::realmain::pipeline::CFGCollectorAndTyper&) (in libpipeline.so) (treemap.h:204)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapMethodDef(std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:293)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:666)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapClassDef(std::__1::unique_ptr<sorbet::ast::ClassDef, std::__1::default_delete<sorbet::ast::ClassDef> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:281)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:672)
std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> > sorbet::ast::TreeMap::apply<sorbet::core::Context, sorbet::realmain::pipeline::CFGCollectorAndTyper>(sorbet::core::Context, sorbet::realmain::pipeline::CFGCollectorAndTyper&, std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >) (in libpipeline.so) (treemap.h:712)
sorbet::realmain::pipeline::typecheckOne(sorbet::core::Context, sorbet::ast::ParsedFile, sorbet::realmain::options::Options const&) (in libpipeline.so) (pipeline.cc:697)
sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3::operator()() const (in libpipeline.so) (pipeline.cc:943)
decltype(std::__1::forward<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&>(fp)()) std::__1::__invoke<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&>(sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&&&) (in libpipeline.so) (type_traits:4353)
std::__1::__function::__value_func<void ()>::operator()() const (in libconcurrency.so) + 53
std::__1::function<void ()>::operator()() const (in libconcurrency.so) + 21
sorbet::WorkerPoolImpl::multiplexJob(std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::function<void ()>) (in libconcurrency.so) + 275
sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&) (in libpipeline.so) (pipeline.cc:932)
sorbet::realmain::realmain(int, char**) (in librealmain.so) (realmain.cc:463)
main (in sorbet) (main.cc:7)
start (in libdyld.dylib) + 1
0x00000003 (in sorbet)

/Users/jvilk/stripe/sorbet/newestestest_crashers/crash-2e2fbec70d8a7762045fcefbf2fab3d5aff1a205.done:2: Failed to process tree (backtrace is above) https://srb.help/1001
     2 |def c(x)b(x)end
        ^^^^^^^^^^^^^^^

/Users/jvilk/stripe/sorbet/newestestest_crashers/crash-2e2fbec70d8a7762045fcefbf2fab3d5aff1a205.done:2: Method `b` does not exist on `Object` https://srb.help/7003
     2 |def c(x)b(x)end
                ^^^^

/Users/jvilk/stripe/sorbet/newestestest_crashers/crash-2e2fbec70d8a7762045fcefbf2fab3d5aff1a205.done:2: This function does not have a `sig` https://srb.help/7017
     2 |def c(x)b(x)end
        ^^^^^^^^

/Users/jvilk/stripe/sorbet/newestestest_crashers/crash-2e2fbec70d8a7762045fcefbf2fab3d5aff1a205.done: Exception in cfg+infer: /Users/jvilk/stripe/sorbet/newestestest_crashers/crash-2e2fbec70d8a7762045fcefbf2fab3d5aff1a205.done (backtrace is above) https://srb.help/1001
Errors: 4
```

#### Expected behavior

Exception does not occur.

### PR DESCRIPTION
**Pull request by aisamanra**
### Motivation
Fixes #1258; adds an extra check to make sure we don't run afoul of an `ENFORCE`.

It's possible this isn't the right place for this check, and that maybe we should avoid generating `DispatchComponent`s with non-existent methods instead of checking against them when using them, but based on other places in the codebase (e.g. the `allComponentsPresent` method in `calls.cc`) I surmised that we do expect to sometimes have non-existent methods in our `DispatchComponent`s, hence my choice of placement for this check.

### Test plan

See included automated tests. Added the fuzzed test from #1258 as well.

### CODE REVIEW

File: infer/SigSuggestion.cc [hunk 1]
```diff
@@ -145,7 +146,7 @@ void extractSendArgumentKnowledge(core::Context ctx, core::Loc bindLoc, cfg::Sen
         }
         core::TypePtr thisType;
         auto iter = &dispatchInfo;
-        while (iter != nullptr) {
+        while (iter != nullptr && iter->main.method.exists()) {
```
Comment (DarkDimius) [inline infer/SigSuggestion.cc]: This will stop it from iterating past a single non-existent component.

Comment (DarkDimius) [reply infer/SigSuggestion.cc]: We should iterate over all of them

Comment (aisamanra) [reply infer/SigSuggestion.cc]: Oof. That's what I get for thinking, "Oh, I'll just write a quick fix at midnight."
