### PR TITLE
Error on empty attr names

### LINKED ISSUE #8494: ENFORCE failure for empty string passed to `attr_reader`
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20attr_reader%20%22%22%0Aend)

```ruby
# typed: true

class A
  attr_reader ""
end
```

#### Observed output

```
editor.rb:4: Bad attribute name "" https://srb.help/3501
     4 |  attr_reader ""
                      ^^
Errors: 1
```

When running Sorbet over this snippet with a debug build of Sorbet, we get this crash:

```
❯ sorbet foo.rb
Exception::raise() msg="rewriter/AttrReader.cc:46 enforced condition source.size() > 2 has failed: (no message provided)"

Backtrace:
sorbet::ConstExprStr::ConstExprStr<18ul>(char const (&) [18ul]) (in sorbet) + 0
sorbet::rewriter::(anonymous namespace)::getName(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&) (in sorbet) + 2400
sorbet::rewriter::AttrReader::run(sorbet::core::MutableContext, sorbet::ast::Send*, sorbet::ast::ExpressionPtr*) (in sorbet) + 1152
sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::Send&)::operator()(sorbet::ast::Send&) const (in sorbet) + 1064
bool sorbet::typecaseHelper<sorbet::ast::ExpressionPtr, sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::Send&)&>(sorbet::ast::ExpressionPtr&, sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::Send&)&) (in sorbet) + 64
void sorbet::typecase<sorbet::ast::ExpressionPtr, sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::Assign&), sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::Send&), sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::MethodDef&), sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::ExpressionPtr const&)>(sorbet::ast::ExpressionPtr&, sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::Assign&)&&, sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::Send&)&&, sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::MethodDef&)&&, sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&)::'lambda'(sorbet::ast::ExpressionPtr const&)&&) (in sorbet) + 80
sorbet::rewriter::Rewriterer::postTransformClassDef(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr&) (in sorbet) + 624
decltype(auto) sorbet::ast::MapFunctions<(sorbet::ast::TreeMapKind)1>::CALL_MEMBER_impl_postTransformClassDef<sorbet::rewriter::Rewriterer, true>::call<sorbet::core::MutableContext&, sorbet::ast::ExpressionPtr&>(sorbet::rewriter::Rewriterer&, sorbet::core::MutableContext&, sorbet::ast::ExpressionPtr&) (in sorbet) + 64
sorbet::ast::TreeMapper<sorbet::rewriter::Rewriterer, sorbet::core::MutableContext, (sorbet::ast::TreeMapKind)1, (sorbet::ast::TreeMapDepthKind)0>::mapClassDef(sorbet::ast::ExpressionPtr&, sorbet::core::MutableContext) (in sorbet) + 284
sorbet::ast::TreeMapper<sorbet::rewriter::Rewriterer, sorbet::core::MutableContext, (sorbet::ast::TreeMapKind)1, (sorbet::ast::TreeMapDepthKind)0>::mapIt(sorbet::ast::ExpressionPtr&, sorbet::core::MutableContext) (in sorbet) + 240
sorbet::ast::TreeMapper<sorbet::rewriter::Rewriterer, sorbet::core::MutableContext, (sorbet::ast::TreeMapKind)1, (sorbet::ast::TreeMapDepthKind)0>::mapClassDef(sorbet::ast::ExpressionPtr&, sorbet::core::MutableContext) (in sorbet) + 228
sorbet::ast::TreeMapper<sorbet::rewriter::Rewriterer, sorbet::core::MutableContext, (sorbet::ast::TreeMapKind)1, (sorbet::ast::TreeMapDepthKind)0>::mapIt(sorbet::ast::ExpressionPtr&, sorbet::core::MutableContext) (in sorbet) + 240
void sorbet::ast::TreeWalk::apply<sorbet::core::MutableContext, sorbet::rewriter::Rewriterer>(sorbet::core::MutableContext, sorbet::rewriter::Rewriterer&, sorbet::ast::ExpressionPtr&) (in sorbet) + 84
sorbet::rewriter::Rewriter::run(sorbet::core::MutableContext, sorbet::ast::ExpressionPtr) (in sorbet) + 72
sorbet::realmain::pipeline::runRewriter(sorbet::core::GlobalState&, sorbet::core::FileRef, sorbet::ast::ExpressionPtr) (in sorbet) + 476
sorbet::realmain::pipeline::indexOne(sorbet::realmain::options::Options const&, sorbet::core::GlobalState&, sorbet::core::FileRef, sorbet::ast::ExpressionPtr) (in sorbet) + 1192
sorbet::realmain::pipeline::index(sorbet::core::GlobalState&, absl::lts_20240722::Span<sorbet::core::FileRef>, sorbet::realmain::options::Options const&, sorbet::WorkerPool&, std::__1::unique_ptr<sorbet::OwnedKeyValueStore const, std::__1::default_delete<sorbet::OwnedKeyValueStore const>> const&) (in sorbet) + 452
sorbet::realmain::realmain(int, char**) (in sorbet) + 12092
main (in sorbet) + 36
start (in dyld) + 2840

foo.rb:3: Failed to process tree (backtrace is above) https://srb.help/1001
     3 |class A
     4 |  attr_reader ""
     5 |end

foo.rb: Exception parsing file: foo.rb (backtrace is above) https://srb.help/1001

foo.rb:4: Bad attribute name "" https://srb.help/3501
     4 |  attr_reader ""
                      ^^
Errors: 3
```

#### Expected behavior

Sorbet should not crash.

- - -

I see pretty similar code in `rewriter/Prop.cc`. I don't think it's _quite_ the same? But we should make sure it doesn't suffer the same problems.

### PR DESCRIPTION
**Pull request by elliottt**
We were returning `core::Names::empty()` when an attribute name was supplied as the empty string, when the downstream logic handled errors by checking for `core::NameRef::noName()` values.

### Motivation
Fixes #8494

### Test plan

See included automated tests.

### CODE REVIEW

File: rewriter/AttrReader.cc [hunk 1]
```diff
@@ -28,15 +28,19 @@ pair<core::NameRef, core::LocOffsets> getName(core::MutableContext ctx, ast::Exp
...
-            bool validAttr = (isalpha(shortName.front()) || shortName.front() == '_') &&
+            bool validAttr = !shortName.empty() && (isalpha(shortName.front()) || shortName.front() == '_') &&
                              absl::c_all_of(shortName, [](char c) { return isalnum(c) || c == '_'; });
             if (validAttr) {
                 res = nameRef;
             } else {
                 if (auto e = ctx.beginIndexerError(name.loc(), core::errors::Rewriter::BadAttrArg)) {
-                    e.setHeader("Bad attribute name \"{}\"", absl::CEscape(shortName));
+                    if (shortName.empty()) {
+                        e.setHeader("Attribute names must be non-empty");
```
Comment (elliottt) [inline rewriter/AttrReader.cc:38]: Not 100% sure about the phrasing here.

File: rewriter/AttrReader.cc [hunk 2]
```diff
@@ -28,15 +28,19 @@ pair<core::NameRef, core::LocOffsets> getName(core::MutableContext ctx, ast::Exp
...
+                    } else {
+                        e.setHeader("Bad attribute name \"{}\"", absl::CEscape(shortName));
+                    }
                 }
-                res = core::Names::empty();
+                return make_pair(core::NameRef::noName(), lit->loc);
```
Comment (elliottt) [inline rewriter/AttrReader.cc:43]: I opted for an early return here, to avoid raising an incorrect error about the attribute name needing to be a symbol or string.

**Review by jez — COMMENTED** [review]
I left a handful of comments here:

https://github.com/sorbet/sorbet/pull/8470/files#diff-93fd1ac5b747adc33673456c462d875e40bf644fcfcaa61ee9b2d6f29da04a04

they apply to your change too. If you want to make those changes and push it up, we can go ahead and merge this. The linked PR will likely take longer to land.

File: rewriter/util/Util.cc [hunk 3]
```diff
@@ -323,4 +323,72 @@ ast::ExpressionPtr ASTUtil::thunkBody(core::MutableContext ctx, ast::ExpressionP
...
+            auto shortName = res.shortName(ctx);
+            if (!validAttrName(shortName)) {
+                if (auto e = ctx.beginIndexerError(name.loc(), core::errors::Rewriter::BadAttrArg)) {
+                    if (shortName.empty()) {
+                        e.setHeader("Attribute names must be non-empty");
+                    } else {
+                        e.setHeader("Bad attribute name `{}`", shortName);
+                    }
+                }
+                return make_pair(core::NameRef::noName(), lit->loc);
```
Comment (jez) [inline rewriter/util/Util.cc:369]: out of curiosity, why not pull all the error handling into the new helper function too, and change the method to `validateAttrArg`?

**Review by jez — APPROVED** [review]

File: rewriter/util/Util.cc (hunk 3 above)
Comment (elliottt) [reply rewriter/util/Util.cc:369]: That's a good idea. At the time I was imagining that it might be worth having slightly different messages depending on the type, but as they're the same we shouldn't duplicate code.
