### PR TITLE
Avoid out-of-bounds error in subtype checks

### LINKED ISSUE #1132: (From Fuzzer) Assertion failed: (i < size()), function operator[], file external/com_google_absl/absl/container/inlined_vector.h, line 315.
#### Input

[→ View on sorbet.run](https://sorbet.run/#%20%23typed%3Atrue%0Amodule%20MyEnumerable%0Aextend%20T%3A%3AGeneric%0AA%20%3D%20type_member%0A%20sig%20%7Bparams(a%3A%20MyEnumerable%5B%5D)%7D%0A%20%20def-(a)%20end%0A%20class%20MySet%0Ainclude%20MyEnumerable%0A%20A%20%3D%0Anew-MySet.new()%20%20end%0Aend)

```ruby
 #typed:true
module MyEnumerable
extend T::Generic
A = type_member
 sig {params(a: MyEnumerable[])}
  def-(a) end
 class MySet
include MyEnumerable
 A =
new-MySet.new()  end
end
```

#### Observed output

```
min_crashers_new/crash-23b616ebe09cd87bbf473ebce5a51cc03afe394f.done:9: Type variable A needs to be declared as `= type_member(SOMETHING)` https://srb.help/5018
     9 | A =
         ^

min_crashers_new/crash-23b616ebe09cd87bbf473ebce5a51cc03afe394f.done:5: Wrong number of type parameters for MyEnumerable. Expected: 1, got: 0 https://srb.help/7010
     5 | sig {params(a: MyEnumerable[])}
                        ^^^^^^^^^^^^^^

min_crashers_new/crash-23b616ebe09cd87bbf473ebce5a51cc03afe394f.done:5: Malformed sig: No return type specified. Specify one with .returns() https://srb.help/5003
     5 | sig {params(a: MyEnumerable[])}
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Assertion failed: (i < size()), function operator[], file external/com_google_absl/absl/container/inlined_vector.h, line 315.
Abort trap: 6
```

#### Expected behavior

Sorbet does not fail the assertion.

### LINKED ISSUE #1168: (From Fuzzer) (Incremental Resolver) Assertion failed: (i < size()), function operator[], file external/com_google_absl/absl/container/inlined_vector.h, line 308.
NOTE: Different from https://github.com/sorbet/sorbet/issues/1132 in that this only triggers with `--stress-incremental-resolver`

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20TestSubtypin%20%20class%20Parent%0A%20%20%20%20extend%20T%3A%3AGeneric%0A%0A%20%20%20%20TParent%20%3D%20type_F%20Parent%0A%20%20%20%20TParent%20%3D%20type_member%0A%20%20end%0A%0A%20%20class%20DifferentArityChild%20%3C%20Parent%0A%20eArityCent%20parent%20%3D%20T.cast%28nil%2C%20Parent%5BInteger%5D%29%0A%20%20%20%20if%20parent.is_a%3F%28DifferentArityChild%29%0A%20%20%20%20%20%20%20%20T.assert_type%21%28parent%2Cd%5BInteger%5D%29%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20end%0Aend)

```ruby
# typed: true
class TestSubtypin  class Parent
    extend T::Generic

    TParent = type_F Parent
    TParent = type_member
  end

  class DifferentArityChild < Parent
 eArityCent parent = T.cast(nil, Parent[Integer])
    if parent.is_a?(DifferentArityChild)
        T.assert_type!(parent,d[Integer])
      end
    end
  end
end
```

#### Observed output

With `--stress-incremental-resolver`:
```
/Users/jvilk/stripe/sorbet/newest_fuzzers/crash-02509bced12dbfd45a9b12ca494bb81f6051a41a.done:16: Parse Error: unexpected token: syntax error https://srb.help/2001
    16 |end
        ^^^

/Users/jvilk/stripe/sorbet/newest_fuzzers/crash-02509bced12dbfd45a9b12ca494bb81f6051a41a.done:6: Redefining constant `TestSubtypin::Parent::TParent` https://srb.help/4011
     6 |    TParent = type_member
            ^^^^^^^
    /Users/jvilk/stripe/sorbet/newest_fuzzers/crash-02509bced12dbfd45a9b12ca494bb81f6051a41a.done:5: Previous definition
     5 |    TParent = type_F Parent
            ^^^^^^^

/Users/jvilk/stripe/sorbet/newest_fuzzers/crash-02509bced12dbfd45a9b12ca494bb81f6051a41a.done:9: Type `TParent` declared by parent `TestSubtypin::Parent` must be re-declared in `TestSubtypin::DifferentArityChild` https://srb.help/5014
     9 |  class DifferentArityChild < Parent
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /Users/jvilk/stripe/sorbet/newest_fuzzers/crash-02509bced12dbfd45a9b12ca494bb81f6051a41a.done:6: `TParent` declared in parent here
     6 |    TParent = type_member
            ^^^^^^^^^^^^^^^^^^^^^

/Users/jvilk/stripe/sorbet/newest_fuzzers/crash-02509bced12dbfd45a9b12ca494bb81f6051a41a.done:12: Malformed type declaration. Unknown type syntax. Expected a ClassName or T.<func> https://srb.help/5004
    12 |        T.assert_type!(parent,d[Integer])
                                      ^^^^^^^^^^

/Users/jvilk/stripe/sorbet/newest_fuzzers/crash-02509bced12dbfd45a9b12ca494bb81f6051a41a.done:346: Parse Error: unexpected token: syntax error https://srb.help/2001
     346 |end
          ^^^

/Users/jvilk/stripe/sorbet/newest_fuzzers/crash-02509bced12dbfd45a9b12ca494bb81f6051a41a.done:335: Redefining constant `TParent` https://srb.help/4012
     335 |    TParent = type_F Parent
              ^^^^^^^^^^^^^^^^^^^^^^^
    /Users/jvilk/stripe/sorbet/newest_fuzzers/crash-02509bced12dbfd45a9b12ca494bb81f6051a41a.done:103: Previous definition
     103 |
     104 |
     105 |
     106 |
     107 |
         |...
     120 |
     121 |
     122 |
     123 |
     124 |

/Users/jvilk/stripe/sorbet/newest_fuzzers/crash-02509bced12dbfd45a9b12ca494bb81f6051a41a.done:336: Redefining constant `TestSubtypin::Parent::TParent` https://srb.help/4011
     336 |    TParent = type_member
              ^^^^^^^
    /Users/jvilk/stripe/sorbet/newest_fuzzers/crash-02509bced12dbfd45a9b12ca494bb81f6051a41a.done:335: Previous definition
     335 |    TParent = type_F Parent
              ^^^^^^^
Assertion failed: (i < size()), function operator[], file external/com_google_absl/absl/container/inlined_vector.h, line 308.
```

#### Expected behavior

Exception does not occur.

### PR DESCRIPTION
**Pull request by aisamanra**
### Motivation
Fixes #1132 and fixes #1168 by checking for an out-of-bounds index in subtyping checks.

### Test plan

See included automated tests. Added fuzzed test case.

### CODE REVIEW

**Comment by aisamanra** [comment]
Okay, I wanted to go through and find out whether this was a situation where `alignTypeArgs` was doing something bad and the fix should be there instead, but in this case, I think `alignTypeArgs` is doing the right thing—finding arguments that don't line up and putting `noSymbol()` in the aligned position—and we should instead just be defensive about going over the edge of the array.

File: core/types/subtyping.cc [hunk 1]
```diff
@@ -1032,6 +1032,9 @@ bool isSubTypeUnderConstraintSingle(Context ctx, TypeConstraint &constr, const T
                 int i = 0;
                 while (indexes[j] != a1->klass.data(ctx)->typeMembers()[i]) {
                     i++;
+                    if (i >= a1->klass.data(ctx)->typeMembers().size()) {
```
Comment (DarkDimius) [inline core/types/subtyping.cc]: Could we leave a comment on why this is necessary in code?

Comment (DarkDimius) [reply core/types/subtyping.cc]: Also, why does this _stop_ iteration over `j` entirely? I think we may need to validate other `j`s
