### PR TITLE
Avoid trying to print emptytree

### LINKED ISSUE #1533: core/Files.cc:119 enforced condition gs.files[_id] has failed
#### Input

```ruby
# typed: true

A = def f; end
```

#### Observed output

enforce

#### Expected behavior

no enforce

### PR DESCRIPTION
**Pull request by aisamanra**
### Motivation
Fixes #1533 by not printing suggestions about `Loc::none()`. Also turn one usage of `EmptyTree` into `Nil` to avoid more confusing location-less error messages.

### Test plan

See included automated tests. Included two tests from #1533.

### CODE REVIEW

File: test/testdata/desugar/assign_empty_parens.rb [hunk 1]
```diff
@@ -0,0 +1,2 @@
+# typed: strict
+U = ()
```
Comment (jez) [inline test/testdata/desugar/assign_empty_parens.rb]: Can you add an example here that uses `begin; end` as well?
