### PR TITLE
Disallow multiple sigs in non-stdlib Object contexts

### LINKED ISSUE #1085: (From Fuzzer) Incremental resolver: core/GlobalState.cc:663 enforced condition res.data(*this)->arguments().empty() has failed
#### Input

[→ View on sorbet.run](https://sorbet.run/#def%20z%0A2sig%20%7B%7D%0Asig%7B%7D%0Adef-f%0Aend%0Aend)

```ruby
def z
2sig {}
sig{}
def-f
end
end
```

#### Observed output

Run debug build with `./bazel-bin/main/sorbet --stress-incremental-resolver file.rb`:

```
fuzz_crashers/min/crash-138a5e97baf0ba3dd8c0a38d1a6c333d95fb841a.done:2: Parse Error: unexpected token: syntax error https://srb.help/2001
     2 |2sig {}
         ^^^
Exception::raise(): core/GlobalState.cc:663 enforced condition res.data(*this)->arguments().empty() has failed: (no message provided)

Backtrace:
sorbet::Exception::enforce_handler(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int) (in librealmain.so) (Exception.h:47)
sorbet::core::GlobalState::enterNewMethodOverload(sorbet::core::Loc, sorbet::core::SymbolRef, sorbet::core::NameRef, unsigned short, std::__1::vector<int, std::__1::allocator<int> > const&) (in libcore.so) (GlobalState.cc:663)
sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk::processStatement(sorbet::core::MutableContext, std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >&, absl::InlinedVector<sorbet::ast::Send*, 1ul, std::__1::allocator<sorbet::ast::Send*> >&)::'lambda'(sorbet::ast::MethodDef*)::operator()(sorbet::ast::MethodDef*) const (in libresolver.so) (resolver.cc:1099)
sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk::processStatement(sorbet::core::MutableContext, std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >&, absl::InlinedVector<sorbet::ast::Send*, 1ul, std::__1::allocator<sorbet::ast::Send*> >&) (in libresolver.so) (resolver.cc:1148)
sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk::processInSeq(sorbet::core::MutableContext, std::__1::unique_ptr<sorbet::ast::InsSeq, std::__1::default_delete<sorbet::ast::InsSeq> >&) (in libresolver.so) (resolver.cc:995)
sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk::postTransformInsSeq(sorbet::core::MutableContext, std::__1::unique_ptr<sorbet::ast::InsSeq, std::__1::default_delete<sorbet::ast::InsSeq> >) (in libresolver.so) (resolver.cc:1355)
sorbet::ast::PostPonePostTransform_InsSeq<sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk, sorbet::core::MutableContext, true>::call(sorbet::core::MutableContext, std::__1::unique_ptr<sorbet::ast::InsSeq, std::__1::default_delete<sorbet::ast::InsSeq> >, sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk&) (in libresolver.so) (treemap.h:242)
sorbet::ast::TreeMapper<sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk, sorbet::core::MutableContext>::mapInsSeq(std::__1::unique_ptr<sorbet::ast::InsSeq, std::__1::default_delete<sorbet::ast::InsSeq> >, sorbet::core::MutableContext) (in libresolver.so) (treemap.h:604)
sorbet::ast::TreeMapper<sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk, sorbet::core::MutableContext>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::MutableContext) (in libresolver.so) (treemap.h:668)
sorbet::ast::TreeMapper<sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk, sorbet::core::MutableContext>::mapMethodDef(std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >, sorbet::core::MutableContext) (in libresolver.so) (treemap.h:303)
sorbet::ast::TreeMapper<sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk, sorbet::core::MutableContext>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::MutableContext) (in libresolver.so) (treemap.h:666)
sorbet::ast::TreeMapper<sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk, sorbet::core::MutableContext>::mapClassDef(std::__1::unique_ptr<sorbet::ast::ClassDef, std::__1::default_delete<sorbet::ast::ClassDef> >, sorbet::core::MutableContext) (in libresolver.so) (treemap.h:281)
sorbet::ast::TreeMapper<sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk, sorbet::core::MutableContext>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::MutableContext) (in libresolver.so) (treemap.h:672)
std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> > sorbet::ast::TreeMap::apply<sorbet::core::MutableContext, sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk>(sorbet::core::MutableContext, sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk&, std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >) (in libresolver.so) (treemap.h:712)
sorbet::resolver::Resolver::resolveSigs(sorbet::core::MutableContext, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >) (in libresolver.so) (resolver.cc:1565)
sorbet::resolver::Resolver::runTreePasses(sorbet::core::MutableContext, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >) (in libresolver.so) (resolver.cc:1594)
sorbet::realmain::pipeline::incrementalResolve(sorbet::core::GlobalState&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&) (in libpipeline.so) (pipeline.cc:321)
sorbet::realmain::pipeline::resolve(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&, bool) (in libpipeline.so) (pipeline.cc:874)
sorbet::realmain::realmain(int, char**) (in librealmain.so) (realmain.cc:426)
main (in sorbet) (main.cc:7)
start (in libdyld.dylib) + 1
0x00000003 (in sorbet)

Exception::raise(): main/pipeline/pipeline.cc:875 enforced condition reresolved.size() == 1 has failed: (no message provided)

Backtrace:
sorbet::Exception::enforce_handler(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int) (in librealmain.so) (Exception.h:47)
sorbet::realmain::pipeline::resolve(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&, bool) (in libpipeline.so) (pipeline.cc:875)
sorbet::realmain::realmain(int, char**) (in librealmain.so) (realmain.cc:426)
main (in sorbet) (main.cc:7)
start (in libdyld.dylib) + 1
0x00000003 (in sorbet)


fuzz_crashers/min/crash-138a5e97baf0ba3dd8c0a38d1a6c333d95fb841a.done:2: To use `sig`, this file must declare an explicit `# typed:` sigil (found: none). If you're not sure which one to use, start with `# typed: false` https://srb.help/5038
     2 |2sig {}
         ^^^^^^

fuzz_crashers/min/crash-138a5e97baf0ba3dd8c0a38d1a6c333d95fb841a.done:2: Malformed sig: No return type specified. Specify one with .returns() https://srb.help/5003
     2 |2sig {}
         ^^^^^^

fuzz_crashers/min/crash-138a5e97baf0ba3dd8c0a38d1a6c333d95fb841a.done:3: Malformed sig: No return type specified. Specify one with .returns() https://srb.help/5003
     3 |sig{}
        ^^^^^

fuzz_crashers/min/crash-138a5e97baf0ba3dd8c0a38d1a6c333d95fb841a.done:37: Failed to process tree (backtrace is above) https://srb.help/1001
    37 |2sig {}
    38 |sig{}
    39 |def-f
    40 |end

???: Exception resolving (backtrace is above) https://srb.help/1001

???: Exception resolving (backtrace is above) https://srb.help/1001
Errors: 7
```

#### Expected behavior

The ENFORCE does not fail.

### LINKED ISSUE #1166: (From Fuzzer) core/types/calls.cc:195 enforced condition ctx.permitOverloadDefinitions() has failed: overload not permitted here
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23typed%3Atrue%0Adef%20r%0Asig%7B%7D%0Asig%7B%7D%0Adef%20_%3Bend%20end%0A_)

```ruby
#typed:true
def r
sig{}
sig{}
def _;end end
_
```

#### Observed output

```
/Users/jvilk/stripe/sorbet/newest_fuzzers/crash-9d4182f22ccb727ec0cbad220fe26db445f3a9b9.done:3: Malformed `sig`: No return type specified. Specify one with .returns() https://srb.help/5003
     3 |sig{}
        ^^^^^

/Users/jvilk/stripe/sorbet/newest_fuzzers/crash-9d4182f22ccb727ec0cbad220fe26db445f3a9b9.done:4: Malformed `sig`: No return type specified. Specify one with .returns() https://srb.help/5003
     4 |sig{}
        ^^^^^
Exception::raise(): core/types/calls.cc:195 enforced condition ctx.permitOverloadDefinitions() has failed: overload not permitted here

Backtrace:
sorbet::core::guessOverload(sorbet::core::Context, sorbet::core::SymbolRef, sorbet::core::SymbolRef, absl::InlinedVector<sorbet::core::TypeAndOrigins const*, 2ul, std::__1::allocator<sorbet::core::TypeAndOrigins const*> >&, sorbet::core::TypePtr const&, std::__1::vector<sorbet::core::TypePtr, std::__1::allocator<sorbet::core::TypePtr> >&, bool) (in libcore.so) (calls.cc:195)
sorbet::core::dispatchCallSymbol(sorbet::core::Context, sorbet::core::DispatchArgs, sorbet::core::Type const*, sorbet::core::SymbolRef, std::__1::vector<sorbet::core::TypePtr, std::__1::allocator<sorbet::core::TypePtr> >&) (in libcore.so) (calls.cc:508)
sorbet::core::ClassType::dispatchCall(sorbet::core::Context, sorbet::core::DispatchArgs) (in libcore.so) (calls.cc:815)
sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_12::operator()(sorbet::cfg::Send*) const (in libinfer.so) (environment.cc:769)
sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&) (in libinfer.so) (environment.cc:745)
sorbet::infer::Inference::run(sorbet::core::Context, std::__1::unique_ptr<sorbet::cfg::CFG, std::__1::default_delete<sorbet::cfg::CFG> >) (in libinfer.so) (inference.cc:162)
sorbet::realmain::pipeline::CFGCollectorAndTyper::preTransformMethodDef(sorbet::core::Context, std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >) (in libpipeline.so) (pipeline.cc:54)
sorbet::ast::PostPonePreTransform_MethodDef<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context, true>::call(sorbet::core::Context, std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >, sorbet::realmain::pipeline::CFGCollectorAndTyper&) (in libpipeline.so) (treemap.h:204)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapMethodDef(std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:293)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:666)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapClassDef(std::__1::unique_ptr<sorbet::ast::ClassDef, std::__1::default_delete<sorbet::ast::ClassDef> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:281)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:672)
std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> > sorbet::ast::TreeMap::apply<sorbet::core::Context, sorbet::realmain::pipeline::CFGCollectorAndTyper>(sorbet::core::Context, sorbet::realmain::pipeline::CFGCollectorAndTyper&, std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >) (in libpipeline.so) (treemap.h:712)
sorbet::realmain::pipeline::typecheckOne(sorbet::core::Context, sorbet::ast::ParsedFile, sorbet::realmain::options::Options const&) (in libpipeline.so) (pipeline.cc:693)
sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3::operator()() const (in libpipeline.so) (pipeline.cc:938)
decltype(std::__1::forward<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&>(fp)()) std::__1::__invoke<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&>(sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&&&) (in libpipeline.so) (type_traits:4353)
std::__1::__function::__value_func<void ()>::operator()() const (in libconcurrency.so) + 53
std::__1::function<void ()>::operator()() const (in libconcurrency.so) + 21
sorbet::WorkerPoolImpl::multiplexJob(std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::function<void ()>) (in libconcurrency.so) + 275
sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&) (in libpipeline.so) (pipeline.cc:927)
sorbet::realmain::realmain(int, char**) (in librealmain.so) (realmain.cc:430)
main (in sorbet) (main.cc:7)
start (in libdyld.dylib) + 1
0x00000003 (in sorbet)


/Users/jvilk/stripe/sorbet/newest_fuzzers/crash-9d4182f22ccb727ec0cbad220fe26db445f3a9b9.done:6: Failed to type (backtrace is above) https://srb.help/1001
     6 |_
        ^

/Users/jvilk/stripe/sorbet/newest_fuzzers/crash-9d4182f22ccb727ec0cbad220fe26db445f3a9b9.done:6: Failed to process tree (backtrace is above) https://srb.help/1001
     6 |_
        ^

/Users/jvilk/stripe/sorbet/newest_fuzzers/crash-9d4182f22ccb727ec0cbad220fe26db445f3a9b9.done:3: Method `sig` does not exist on `Object` https://srb.help/7003
     3 |sig{}
        ^^^^^

/Users/jvilk/stripe/sorbet/newest_fuzzers/crash-9d4182f22ccb727ec0cbad220fe26db445f3a9b9.done:4: Method `sig` does not exist on `Object` https://srb.help/7003
     4 |sig{}
        ^^^^^

/Users/jvilk/stripe/sorbet/newest_fuzzers/crash-9d4182f22ccb727ec0cbad220fe26db445f3a9b9.done: Exception in cfg+infer: /Users/jvilk/stripe/sorbet/newest_fuzzers/crash-9d4182f22ccb727ec0cbad220fe26db445f3a9b9.done (backtrace is above) https://srb.help/1001
Errors: 7
```

#### Expected behavior

Exception does not occur.

### PR DESCRIPTION
**Pull request by aisamanra**
### Motivation
Fixes #1085 and fixes #1166. We had a loophole where, because the owner of methods defined on `<root>` was `Object`, we would allow multiple overloaded `sig`s on nested method definitions. Sometimes this would result in anomalous broken invariants (as in #1085) and sometimes we would fail later on when realizing that those methods (given that they do end up on `<root>` eventually) should not have allowed overloads in the first place.

### Test plan

See included automated tests. This added fuzzed tests from two sources, as well.

### CODE REVIEW

**Comment by aisamanra** [comment]
I made this change by adding an extra parameter to `Context::permitOverloadDefinitions` which represents the file in which the method or sig appears: this allows us to check, even if we've (say) re-opened `Object` or defined a method inside another top-level `def`, whether we've done so inside a stdlib file or not. It wasn't clear to me that there was a better way of doing so given just the information available in the `Context`—that is to say, whether we could distinguish the situation where we were defining new methods on `Object` in the stdlib versus the situation where we had reopened `Object` somewhere else and were defining new methods on it, as both of them would have `Object` as the owner in the context. If there is a preferable way, I'd be happy to do that isntead.

File: core/types/calls.cc [hunk 1]
```diff
@@ -200,7 +200,7 @@ SymbolRef guessOverload(Context ctx, SymbolRef inClass, SymbolRef primary,
                         InlinedVector<const TypeAndOrigins *, 2> &args, const TypePtr &fullType, vector<TypePtr> &targs,
                         bool hasBlock) {
     counterInc("calls.overloaded_invocations");
-    ENFORCE(ctx.permitOverloadDefinitions(), "overload not permitted here");
+    ENFORCE(ctx.permitOverloadDefinitions(primary.data(ctx)->loc().file()), "overload not permitted here");
```
Comment (elliottt) [inline core/types/calls.cc]: Why not just `ctx.withOwner(primary).permitOverloadDefinitions()` instead? It looks like `permitOverloadDefinitions` is already consulting the owner.

File: test/cli/incremental-resolver/expect-failures/multiple_sigs.rb [hunk 2]
```diff
@@ -0,0 +1,6 @@
+def z
+2sig {}
```
Comment (DarkDimius) [inline test/cli/incremental-resolver/expect-failures/multiple_sigs.rb]: can we simplify this test while keeping the tested behavior?

File: core/types/calls.cc (hunk 1 above)
Comment (aisamanra) [reply core/types/calls.cc]: This would work here but not in the other uses of `permitOverloadDefinitions`, which runs earlier and therefore has less information available to it.
