### PR TITLE
Prevent top-level use of type_member

### LINKED ISSUE #1087: (From Fuzzer) Exception::raise(): LambdaParam::derivesFrom not implemented, not clear what it should do. Let's see this fire first.
#### Input

<a href="https://sorbet.run/#%23%20typed%3A%20true%0Ac)%0A%20Elem%20%3D%20type_member%0A%20%20sig%20%7Bparams(block%3A%20T.proc.params(ar0%3A%20Elem).vo).vid%7D%0A%20%20def%20yield_type_member(%26block))yield_type_member%20%7B%20%7C%20y%2C%20z%7C%20%7D%0A%20end">→ View on sorbet.run</a>

```ruby
# typed: true
c)
 Elem = type_member
  sig {params(block: T.proc.params(ar0: Elem).vo).vid}
  def yield_type_member(&block))yield_type_member { | y, z| }
 end
```

#### Observed output

```
fuzz_crashers/min2/crash-7901bf465c9825fbc2fa1b558cfd89927a12f77a.done:2: Parse Error: unexpected token: syntax error https://srb.help/2001
     2 |c)
         ^

fuzz_crashers/min2/crash-7901bf465c9825fbc2fa1b558cfd89927a12f77a.done:5: Parse Error: unexpected token: syntax error https://srb.help/2001
     5 |  def yield_type_member(&block))yield_type_member { | y, z| }
                                       ^

fuzz_crashers/min2/crash-7901bf465c9825fbc2fa1b558cfd89927a12f77a.done:4: Malformed signature: vid is invalid in this context https://srb.help/5003
     4 |  sig {params(block: T.proc.params(ar0: Elem).vo).vid}
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    fuzz_crashers/min2/crash-7901bf465c9825fbc2fa1b558cfd89927a12f77a.done:4: Consult https://sorbet.org/docs/sigs for signature syntax
     4 |  sig {params(block: T.proc.params(ar0: Elem).vo).vid}
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

fuzz_crashers/min2/crash-7901bf465c9825fbc2fa1b558cfd89927a12f77a.done:4: Malformed signature: vo is invalid in this context https://srb.help/5003
     4 |  sig {params(block: T.proc.params(ar0: Elem).vo).vid}
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    fuzz_crashers/min2/crash-7901bf465c9825fbc2fa1b558cfd89927a12f77a.done:4: Consult https://sorbet.org/docs/sigs for signature syntax
     4 |  sig {params(block: T.proc.params(ar0: Elem).vo).vid}
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

fuzz_crashers/min2/crash-7901bf465c9825fbc2fa1b558cfd89927a12f77a.done:4: Malformed T.proc: You must specify a return type https://srb.help/5004
     4 |  sig {params(block: T.proc.params(ar0: Elem).vo).vid}
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

fuzz_crashers/min2/crash-7901bf465c9825fbc2fa1b558cfd89927a12f77a.done:4: Malformed sig: No return type specified. Specify one with .returns() https://srb.help/5003
     4 |  sig {params(block: T.proc.params(ar0: Elem).vo).vid}
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception::raise(): LambdaParam::derivesFrom not implemented, not clear what it should do. Let's see this fire first.

Backtrace:
sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_17::operator()(sorbet::cfg::LoadYieldParams*) const (in libinfer.so) (environment.cc:886)
sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&) (in libinfer.so) (environment.cc:745)
sorbet::infer::Inference::run(sorbet::core::Context, std::__1::unique_ptr<sorbet::cfg::CFG, std::__1::default_delete<sorbet::cfg::CFG> >) (in libinfer.so) (inference.cc:162)
sorbet::realmain::pipeline::CFGCollectorAndTyper::preTransformMethodDef(sorbet::core::Context, std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >) (in libpipeline.so) (pipeline.cc:54)
sorbet::ast::PostPonePreTransform_MethodDef<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context, true>::call(sorbet::core::Context, std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >, sorbet::realmain::pipeline::CFGCollectorAndTyper&) (in libpipeline.so) (treemap.h:204)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapMethodDef(std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:293)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:666)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapClassDef(std::__1::unique_ptr<sorbet::ast::ClassDef, std::__1::default_delete<sorbet::ast::ClassDef> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:281)
sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in libpipeline.so) (treemap.h:672)
std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> > sorbet::ast::TreeMap::apply<sorbet::core::Context, sorbet::realmain::pipeline::CFGCollectorAndTyper>(sorbet::core::Context, sorbet::realmain::pipeline::CFGCollectorAndTyper&, std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >) (in libpipeline.so) (treemap.h:712)
sorbet::realmain::pipeline::typecheckOne(sorbet::core::Context, sorbet::ast::ParsedFile, sorbet::realmain::options::Options const&) (in libpipeline.so) (pipeline.cc:693)
sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3::operator()() const (in libpipeline.so) (pipeline.cc:938)
decltype(std::__1::forward<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&>(fp)()) std::__1::__invoke<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&>(sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&&&) (in libpipeline.so) (type_traits:4353)
sorbet::WorkerPoolImpl::multiplexJob(std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::function<void ()>) (in libconcurrency.so) (WorkerPoolImpl.cc:0)
sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&) (in libpipeline.so) (pipeline.cc:927)
sorbet::realmain::realmain(int, char**) (in librealmain.so) (realmain.cc:427)
main (in sorbet) (main.cc:7)
start (in libdyld.dylib) + 1


fuzz_crashers/min2/crash-7901bf465c9825fbc2fa1b558cfd89927a12f77a.done:5: Failed to type (backtrace is above) https://srb.help/1001
     5 |  def yield_type_member(&block))yield_type_member { | y, z| }
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

fuzz_crashers/min2/crash-7901bf465c9825fbc2fa1b558cfd89927a12f77a.done:5: Failed to process tree (backtrace is above) https://srb.help/1001
     5 |  def yield_type_member(&block))yield_type_member { | y, z| }
     6 | end

fuzz_crashers/min2/crash-7901bf465c9825fbc2fa1b558cfd89927a12f77a.done: Exception in cfg+infer: fuzz_crashers/min2/crash-7901bf465c9825fbc2fa1b558cfd89927a12f77a.done (backtrace is above) https://srb.help/1001
Errors: 9
```

#### Expected behavior

ENFORCE does not trigger.

### PR DESCRIPTION
**Pull request by aisamanra**
### Motivation
Fixes #1087: this is a situation that can only ever happen in an error, and I went back and forth on whether to try to implement this check elsewhere, but after some digging and reflection, I think this implementation is both correct and sufficient here.

Most of our type-checking code doesn't care about `LambdaParam` types. If we're in the context of a class that uses a `LambdaParam`, then we convert it to a `SelfTypeParam` instead (e.g. if we wrapped the relevant fuzzed test case in `class A; ...; end`, then we don't see the same error because the type surfaces as a `SelfTypeParam` instead of a `LambdaParam`.) We might also instantiate them with known type variables or with `T.untyped` if we're working in a different context.

This hits into an edge-case where if you use a `type_member` at the top level, then we don't instantiate it into a `SelfTypeParam` and keep using it as a `LambdaParam` directly, and then (in this case) try to check and see if it's a kind of `Array` so that maybe we can splat it into a proc. If we _had_ instantiated it into a `SelfTypeParam`, then we'd just return `false` for that same check, so this copies that behavior into `LambdaParam::derivesFrom`, along with a comment about why.

### Test plan

See included automated tests. Added relevant fuzzed test.

### CODE REVIEW

File: core/types/types.cc [hunk 1]
```diff
@@ -663,8 +663,11 @@ SelfTypeParam::SelfTypeParam(const SymbolRef definition) : definition(definition
 }
 
 bool LambdaParam::derivesFrom(const GlobalState &gs, SymbolRef klass) const {
-    Exception::raise(
-        "LambdaParam::derivesFrom not implemented, not clear what it should do. Let's see this fire first.");
+    // This only ever gets called in bad situations when we haven't instantiated a LambdaParam as either a SelfTypeParam
+    // (within the body of a generic class) or a specific type (after having instantiated the class with specific
+    // parameters and/or T.untyped.) However, those errors are captured elsewhere, so here we can follow the same
+    // behavior as SelfTypeParam and return 'false'.
```
Comment (DarkDimius) [inline core/types/types.cc]: `SelfTypeParam` is a valid type inside method bodies, while method bodies should _never_ see uninstantiated `LambdaParam`. It's like a free type variable, if you have it, the expression isn't well formed.

**Comment by aisamanra** [comment]
This now has a completely different tack: it instead determines that a `type_member` is being used at the top-level and never instantiates it as a type variable at all; this means that it's never in scope as a `LambdaParam` to begin with. This fixes the situation in which we might have a type variable available to a method despite neither the method nor the owning class being generic (which would happen because the top-level type parameter would be attached to `T.class_of(<root>)` while the method was owned by `Object`.)

This PR also changes the behavior of another error slightly: previously, when we used `type_member` with incorrect arguments, we would remove that binding from the graph, which meant that _uses_ of the type member being defined would raise additional errors. This PR causes us to treat the type member as a type alias for `T.undefined` in that case: this means that we still raise the relevant error, but then uses are silenced.

The minor downside to this second change is that we occasionally get anomalous and oddly-ordered errors when there are other errors present that involve the same type member: for example, if we define a top-level `type_member` and then try to redefine it as a constant, then we get an error about how we're redefining a constant as a different type. I mention this for completeness—I'd argue that this makes errors better in the majority of real-world situations, and there are only a few cases (e.g. writing `X = 5; X = type_member` at the top-level—something you're only likely to see when fuzzing or explicitly trying to examine Sorbet's behavior in the presence of odd programs) where the error messages get slightly more odd, and even then they're still useful.

File: namer/namer.cc [hunk 2]
```diff
@@ -792,6 +803,23 @@ class NameInserter {
         return make_unique<ast::EmptyTree>();
     }
 
+    unique_ptr<ast::Expression> handleAssignment(core::MutableContext ctx, unique_ptr<ast::Assign> asgn) {
+        auto *send = ast::cast_tree<ast::Send>(asgn->rhs.get());
```
Comment (aisamanra) [inline namer/namer.cc]: This function was pulled out of `postTransformAssign` so it could be easily reused up in `handleTypeMemberDefinition`; all it does is call `fillAssign` and then, if the `Assign` node is assigning a type alias, flips the relevant flag on the symbol.
