### PR TITLE
Fix crash in lub with tuples

### LINKED ISSUE #5286: Enforce failure in `T.all` with `T.type_parameter` and applied type
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%0A%20%20type_parameters%28%3AU%29%0A%20%20.params%28%0A%20%20%20%20x%3A%20T.any%28%0A%20%20%20%20%20%20T.type_parameter%28%3AU%29%2C%0A%20%20%20%20%20%20T%3A%3AArray%5BT.type_parameter%28%3AU%29%5D%0A%20%20%20%20%29%0A%20%20%29%0A%20%20.returns%28T%3A%3AArray%5BT.type_parameter%28%3AU%29%5D%29%0A%7D%0Adef%20foo%28x%29%0A%20%20case%20x%0A%20%20when%20Array%0A%20%20%20%20T.reveal_type%28x%29%0A%20%20else%0A%20%20%20%20T.reveal_type%28x%29%0A%20%20%20%20%5Bx%5D%0A%20%20end%0Aend%0A)

```ruby
# typed: true
extend T::Sig

sig {
  type_parameters(:U)
  .params(
    x: T.any(
      T.type_parameter(:U),
      T::Array[T.type_parameter(:U)]
    )
  )
  .returns(T::Array[T.type_parameter(:U)])
}
def foo(x)
  case x
  when Array
    T.reveal_type(x)
  else
    T.reveal_type(x)
    [x]
  end
end

```

#### Observed output

```
editor.rb:16: Expected BasicObject but found T.any(T::Array[Object#foo#U], Object#foo#U) for argument other https://srb.help/7002
    16 |  when Array
               ^^^^^
  Expected BasicObject for argument other of method Module#===:
    https://github.com/sorbet/sorbet/tree/master/rbi/core/module.rbi#L161:
     161 |        other: BasicObject,
                  ^^^^^
  Got T.any(T::Array[Object#foo#U], Object#foo#U) originating from:
    editor.rb:14:
    14 |def foo(x)
                ^

editor.rb:17: Revealed type: T.all(T::Array[T.untyped], T.any(T::Array[Object#foo#U], Object#foo#U)) https://srb.help/7014
    17 |    T.reveal_type(x)
            ^^^^^^^^^^^^^^^^
  Got T.all(T::Array[T.untyped], T.any(T::Array[Object#foo#U], Object#foo#U)) originating from:
    editor.rb:14:
    14 |def foo(x)
                ^
    editor.rb:16:
    16 |  when Array
               ^^^^^

editor.rb:19: Revealed type: Object#foo#U https://srb.help/7014
    19 |    T.reveal_type(x)
            ^^^^^^^^^^^^^^^^
  Got Object#foo#U originating from:
    editor.rb:14:
    14 |def foo(x)
                ^
    editor.rb:16:
    16 |  when Array
               ^^^^^
Errors: 3
```

#### Expected behavior

It's honestly unclear whether this should be a bug or not, and if it is a bug how to fix it.

We intentionally haven't allowed type tests on generics (because if you allow type tests on generics, you lose parametricity). In this case the type tests is in some sense "safe" because the `T.any` allows it, but I don't currently have a clear idea of how to translate that feeling to a policy.

Separately, it looks like the `T.all` doesn't collapse the generic away, which is also surprising, but I'm not sure whether that's a bug or not.

- - -

**Update** in fact, the `T.all` behavior is a bug, and it even fails an ENFORCE:

```
❯ sorbet example.rb
Exception::raise(): core/types/subtyping.cc:49 enforced condition Types::isSubType(gs, t1, ret) has failed:
TupleType {
  0 = SelfTypeParam(<C <U Object>>#<U foo>#<T <U U> $1>)
}
is not a super type of
AppliedType {
      klass = <C <U Array>>
      targs = [
        <C <U Elem>> = T.untyped
      ]
    } & (AppliedType {
          klass = <C <U Array>>
          targs = [
            <C <U Elem>> = SelfTypeParam(<C <U Object>>#<U foo>#<T <U U> $1>)
          ]
        } | SelfTypeParam(<C <U Object>>#<U foo>#<T <U U> $1>))
was lubbing with TupleType {
  0 = SelfTypeParam(<C <U Object>>#<U foo>#<T <U U> $1>)
}

Backtrace:
  #3 0x1a94083 sorbet::core::Types::any()
  #4 0x1228f92 sorbet::infer::Environment::mergeWith()
  #5 0x12162e3 sorbet::infer::Inference::run()
  #6 0xf08b45 sorbet::realmain::pipeline::CFGCollectorAndTyper::preTransformMethodDef()
  #7 0xf0898a sorbet::ast::MapFunctions<>::CALL_MEMBER_impl_preTransformMethodDef<>::call<>()
  #8 0xf07caf sorbet::ast::TreeMapper<>::mapMethodDef()
  #9 0xf06e26 sorbet::ast::TreeMapper<>::mapIt()
  #10 0xf07c54 sorbet::ast::TreeMapper<>::mapClassDef()
  #11 0xf06dd8 sorbet::ast::TreeMapper<>::mapIt()
  #12 0xf088d8 sorbet::ast::TreeMapper<>::mapInsSeq()
  #13 0xf076a4 sorbet::ast::TreeMapper<>::mapIt()
  #14 0xf06aaa sorbet::ast::ShallowWalk::apply<>()
  #15 0xed3f7c sorbet::realmain::pipeline::(anonymous namespace)::typecheckOne()
  #16 0xed3223 sorbet::realmain::pipeline::typecheck()::$_4::operator()()
  #17 0xed2f1d std::__1::__invoke<>()
  #18 0xed2ecd std::__1::__invoke_void_return_wrapper<>::__call<>()
  #19 0xed2e9d std::__1::__function::__alloc_func<>::operator()()
  #20 0xed2069 std::__1::__function::__func<>::operator()()
  #21 0x16f6532 std::__1::__function::__value_func<>::operator()()
  #22 0x16ecec5 std::__1::function<>::operator()()
  #23 0x1ae4263 sorbet::WorkerPoolImpl::multiplexJob()
  #24 0xec6506 sorbet::realmain::pipeline::typecheck()
  #25 0xb380db sorbet::realmain::realmain()
  #26 0xb32602 main
  #27 0x7fb84b301083 __libc_start_main
  #28 0xb3250e _start
```

### PR DESCRIPTION
**Pull request by jez**
The idea is that if we have to widen a proxy type to its underlying type
in order to attempt to collapse it with the other half of the `lub`, we
want to make that widening permanent.

If the code hadn't crashed via the ENFORCE, the revealed type in the
test would have been `[T.type_parameter(:U)] (1-tuple)`, which would
have been wrong, because the `when Array` branch doesn not necessarily
return a 1-tuple (that is what the ENFORCE correctly caught).

The crash looked like this:

    [2022-07-23 00:42:41.802] [fatalFallback] [error] Exception::raise(): core/types/subtyping.cc:49 enforced condition Types::isSubType(gs, t1, ret) has failed:
    TupleType {
      0 = SelfTypeParam(<C <U Object>>#<U foo>#<T <U U> $1>)
    }
    is not a super type of
    AppliedType {
          klass = <C <U Array>>
          targs = [
            <C <U Elem>> = T.untyped
          ]
        } & (AppliedType {
              klass = <C <U Array>>
              targs = [
                <C <U Elem>> = SelfTypeParam(<C <U Object>>#<U foo>#<T <U U> $1>)
              ]
            } | SelfTypeParam(<C <U Object>>#<U foo>#<T <U U> $1>))
    was lubbing with TupleType {
      0 = SelfTypeParam(<C <U Object>>#<U foo>#<T <U U> $1>)
    }

### Motivation

Fixes #5286

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_M6k2jfg1PfaSs7
→ https://go/builds/bui_M6k29r5X90A0MX

File: test/testdata/infer/lub_tuple_array.rb [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+      T.type_parameter(:U),
+      T::Array[T.type_parameter(:U)]
+    )
+  )
+  .returns(T::Array[T.type_parameter(:U)])
+}
+def foo(x)
+  res = case x
+  when Array
+    # This type is particularly unweildly, and I'd love to make it smaller if possible.
```
Comment (froydnj) [inline test/testdata/infer/lub_tuple_array.rb:17]:
```suggestion
    # This type is particularly unwieldy, and I'd love to make it smaller if possible.
```

**Review by froydnj — APPROVED** [review]

File: test/testdata/infer/lub_tuple_array.rb (hunk 1 above)
Comment (jez) [reply test/testdata/infer/lub_tuple_array.rb:17]: wow TIL; i always thought it was unweildly
