### PR TITLE
Catch certain kinds of incorrect calls to `raise`

### LINKED ISSUE #4209: Check signature of an error class constructor in `raise` called with two arguments
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20Error%20%3C%20StandardError%0A%20%20def%20initialize(message%2C%20arg)%0A%20%20%20%20super(message)%0A%20%20%20%20%40arg%20%3D%20arg%0A%20%20end%0Aend%0A%0Araise%20Error%2C%20%22Message%22)

```ruby
# typed: true
extend T::Sig

class Error < StandardError
  def initialize(message, arg)
    super(message)
    @arg = arg
  end
end

raise Error, "Message"
```

#### Observed output

```
No errors! Great job.
```

On runtime, `ArgumentError: wrong number of arguments (given 1, expected 2)` error occurs.

#### Expected behavior

`srb tc` reports an error like `Not enough arguments provided for method Error#initialize. Expected: 2, got: 1` for
```ruby
raise Error, "Message"
```

### PR DESCRIPTION
**Pull request by jez**
### Motivation

Fixes #4209

See commits for summary.

### Test plan

See included automated tests.

### CODE REVIEW

File: core/types/calls.cc [hunk 1]
```diff
@@ -4386,6 +4444,7 @@ const vector<Intrinsic> intrinsics{
 
     {Symbols::Kernel(), Intrinsic::Kind::Instance, Names::proc(), &Kernel_proc},
     {Symbols::Kernel(), Intrinsic::Kind::Instance, Names::lambda(), &Kernel_proc},
+    {Symbols::Kernel(), Intrinsic::Kind::Instance, Names::raise(), &Kernel_raise},
```
Comment (froydnj) [inline core/types/calls.cc:4447]: Since `Kernel#raise` and `Kernel#fail` are the same function (#5930), we should have an intrinsic for `Kernel#fail` as well?

File: core/types/calls.cc [hunk 2]
```diff
@@ -4141,6 +4141,64 @@ class Kernel_proc : public IntrinsicMethod {
...
+        // `.new` (https://ruby-doc.org/core-2.7.2/Exception.html#method-c-exception) but anything
+        // that defines a method called `exception` could be called. We don't implement that here,
+        // because implicit conversions are hard in the presence of subtyping. Instead, we restrict
+        // the check to only subclasses of `Exception`, not arbitrary classes.
+        auto classOfException = make_type<ClassType>(Symbols::Exception().data(gs)->lookupSingletonClass(gs));
+        if (!args.args[0]->type.isUntyped() && !Types::isSubType(gs, args.args[0]->type, classOfException)) {
+            return;
+        }
+
+        uint16_t newNumPosArgs = args.args.size() >= 2 ? 1 : 0;
```
Comment (froydnj) [inline core/types/calls.cc:4166]: This was surprising to me until I looked at the documentation and saw that `raise` doesn't forward an unlimited number of arguments.  Bizarre.

File: core/types/calls.cc [hunk 3]
```diff
@@ -4141,6 +4141,64 @@ class Kernel_proc : public IntrinsicMethod {
...
+        // - arguably none of this intrinsic should run if we don't know that arg0 isn't a Class
+        //
+        // Technically speaking, the Ruby VM actually implements this by way of calling
+        // arg0.exception. It just so happens that Exception.exception is defined to forward to
+        // `.new` (https://ruby-doc.org/core-2.7.2/Exception.html#method-c-exception) but anything
+        // that defines a method called `exception` could be called. We don't implement that here,
+        // because implicit conversions are hard in the presence of subtyping. Instead, we restrict
+        // the check to only subclasses of `Exception`, not arbitrary classes.
+        auto classOfException = make_type<ClassType>(Symbols::Exception().data(gs)->lookupSingletonClass(gs));
+        if (!args.args[0]->type.isUntyped() && !Types::isSubType(gs, args.args[0]->type, classOfException)) {
```
Comment (froydnj) [inline core/types/calls.cc:4162]: WDYT about pulling `args.args[0]` out into a separate variable (`klass` or somesuch) and using it here and below?

File: test/testdata/intrinsics/kernel_raise.rb [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+    raise MyError, "arg"
+    #              ^^^^^ error: Missing required keyword argument `input` for method `MyError#initialize`
+    #              ^^^^^ error: Too many positional arguments provided for method `MyError#initialize`. Expected: `0`, got: `1`
+  end
+
+  0.times do
+    raise cls, "arg"
+    #          ^^^^^ error: Missing required keyword argument `input` for method `MyError#initialize`
+    #          ^^^^^ error: Too many positional arguments provided for method `MyError#initialize`. Expected: `0`, got: `1`
+  end
```
Comment (froydnj) [inline test/testdata/intrinsics/kernel_raise.rb:56]: WDYT about additional tests:

1. Cases where the `initialize` method takes a single arg, but we provide more to `raise`, e.g. `raise MyError, "arg", ["more", "stuff"]` -- trying to verify that we don't pass those extra arguments to the `new` call.
2. Cases where the `initialize` method takes multiple args, but we only provide the single arg (I think this was the original motivating example?)
3. Cases where the `initialize` method takes multiple args, and we provide those multiple args to `raise`, but of course they are not handled.  This is kind of redundant with case 1, I guess?

File: core/serialize/serialize.cc [hunk 5]
```diff
@@ -631,6 +631,7 @@ void SerializerImpl::pickle(Pickler &p, const Method &what) {
         pickle(p, a);
     }
     pickle(p, what.resultType);
+    p.putU4(what.intrinsicOffset);
```
Comment (froydnj) [inline core/serialize/serialize.cc:634]: Whoops, good catch.

**Review by froydnj — APPROVED** [review]
Mostly extra things to consider; the `Kernel#fail` bit should be addressed before landing, I think.

File: core/types/calls.cc (hunk 2 above)
Comment (jez) [reply core/types/calls.cc:4166]: 🙂-intensifies

File: core/serialize/serialize.cc (hunk 5 above)
Comment (jez) [reply core/serialize/serialize.cc:634]: I mentioned this in the commit message but I think this wasn't so much a bug as much as a choice not to serialize function pointers to a cache (before intrinsic became intrinsicOffset)

**Comment by jez** [comment]
> Mostly extra things to consider; the `Kernel#fail` bit should be addressed before landing, I think.

I believe I covered all your points. Going to auto-merge, but lmk if you have anything else.

**Comment by jez** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_NEle7FBO5QEwyg
→ https://go/builds/bui_NEle3YPO0md9IR
