### PR TITLE
fix placement for instance variables defined in toplevel methods

### LINKED ISSUE #6376: Crash in resolveField after recent changes to fields
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Asig%20%7Breturns%28T.untyped%29%7D%0Aattr_writer%20%3Afoo)

```ruby
# typed: strict

sig {returns(T.untyped)}
attr_writer :foo
```

#### Observed output

```
editor.rb:4: Malformed sig. Type not specified for argument foo https://srb.help/5003
     4 |attr_writer :foo
                     ^^^
    editor.rb:3: Signature
     3 |sig {returns(T.untyped)}
        ^^^^^^^^^^^^^^^^^^^^^^^^

editor.rb:4: The instance variable @foo must be declared using T.let when specifying # typed: strict https://srb.help/7043
     4 |attr_writer :foo
                     ^^^

editor.rb:3: Method sig does not exist on T.class_of(<root>) https://srb.help/7003
     3 |sig {returns(T.untyped)}
        ^^^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:3: Insert extend T::Sig
     3 |sig {returns(T.untyped)}
        ^

editor.rb:3: Method returns does not exist on T.class_of(<root>) https://srb.help/7003
     3 |sig {returns(T.untyped)}
             ^^^^^^^
Errors: 4
```

When there's a debug build:

```
❯ sorbet foo.rb
Exception::raise(): resolver/resolver.cc:2103 enforced condition prior.exists() has failed: (no message provided)

Backtrace:
  #3 0xb8ea52
  #4 0x14a35f6 sorbet::resolver::(anonymous namespace)::ResolveTypeMembersAndFieldsWalk::resolveField()
  #5 0x143ac4e sorbet::resolver::(anonymous namespace)::ResolveTypeMembersAndFieldsWalk::run<>()
  #6 0x1437211 sorbet::resolver::Resolver::run()
  #7 0xf24379 sorbet::realmain::pipeline::resolve()
  #8 0xb80651 sorbet::realmain::realmain()
  #9 0xb7af82 main
  #10 0x7f8ae510e083 __libc_start_main
  #11 0xb7ae8e _start

```

#### Expected behavior

There should be no ENFORCE failure.

- - -

A bisect reveals that http://go/srb/commit/f6135c7b09532ea2dbb4df17da37f1b39e78303a is the first bad commit

### PR DESCRIPTION
**Pull request by froydnj**
### Motivation

Fixes #6376.

### Test plan

See included automated tests.  The testcase was generated at `f6135c7b09532ea2dbb4df17da37f1b39e78303a^`

### CODE REVIEW

File: core/FoundDefinitions.h [hunk 1]
```diff
@@ -196,6 +196,7 @@ struct FoundField {
     };
     Kind kind;
     bool onSingletonClass;
+    bool fromWithinMethod;
```
Comment (jez) [inline core/FoundDefinitions.h:199]: Out of curiosity, how did this work previously when it was done in resolver, not namer?

**Review by jez — APPROVED** [review]

File: core/FoundDefinitions.h (hunk 1 above)
Comment (froydnj) [reply core/FoundDefinitions.h:199]: It work(ed/s) correctly in resolver because the `Context` structure that we get has a method as its `owner` field.  We decided to always have fields owned by classes, not methods, so we have to hack things a bit here.

It's very sad that this code is *almost* `methodOwner`...but not quite.
