### PR TITLE
Check visibility in runtime override checks

### LINKED ISSUE #8958: Runtime override checking ignores visibility
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Arequire_relative%20'gems%2Fsorbet-runtime%2Flib%2Fsorbet-runtime'%0A%0Aclass%20Parent%0A%20%20extend%20T%3A%3ASig%2C%20T%3A%3AHelpers%0A%0A%20%20abstract!%0A%0A%20%20sig%20%7B%20abstract.returns%28Integer%29%20%7D%0A%20%20def%20foo%3B%20end%0Aend%0A%0Aclass%20Child%20%3C%20Parent%0A%20%20sig%20%7B%20override.returns%28Integer%29%20%7D%0A%20%20private%20def%20foo%3B%200%3B%20end%0Aend%0A%0AT%3A%3AUtils.run_all_sig_blocks%0A)

```ruby
# typed: true
require_relative 'gems/sorbet-runtime/lib/sorbet-runtime'

class Parent
  extend T::Sig, T::Helpers

  abstract!

  sig { abstract.returns(Integer) }
  def foo; end
end

class Child < Parent
  sig { override.returns(Integer) }
  private def foo; 0; end
end

T::Utils.run_all_sig_blocks

```

#### Observed output

```
No errors! Great job.
```

```
❯ ruby foo.rb

❯ # ^ nothing printed
```

#### Expected behavior

There should be an exception at runtime like what would have been raised for mismatched types.

- - -

See #5522 for the feature tracking the static side of this.

With a different example:

```ruby
# typed: true
require_relative 'gems/sorbet-runtime/lib/sorbet-runtime'

class Parent
  extend T::Sig, T::Helpers

  abstract!

  sig { abstract.returns(String) }
  def foo; end
end

class Child < Parent
  sig { override.returns(Integer) }
  def foo; 0; end
end

T::Utils.run_all_sig_blocks
```

```
❯ ruby foo.rb
/Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/signature_validation.rb:272:in `validate_override_types': Incompatible return type in signature for implementation of method `foo`: (RuntimeError)
* Base: `String` (in Parent at foo.rb:10)
* Implementation: `Integer` (in Child at foo.rb:15)
(The types must be covariant.)
        from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/signature_validation.rb:91:in `validate'
        from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:392:in `build_sig'
        from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:348:in `run_sig'
        from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:248:in `block in _on_method_added'
        from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:449:in `run_sig_block_for_key'
        from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:469:in `block in run_all_sig_blocks'
        from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:466:in `loop'
        from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:466:in `run_all_sig_blocks'
        from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/utils.rb:85:in `run_all_sig_blocks'
        from foo.rb:18:in `<main>'
```

This same logic should look at public/private.

### PR DESCRIPTION
**Pull request by CT075**
### Motivation
This resolves #8958.

### Test plan
Added unit tests to `gems/sorbet-runtime/test/types/visibility.rb`

### CODE REVIEW

File: gems/sorbet-runtime/test/types/visibility.rb
Comment (jez) [inline gems/sorbet-runtime/test/types/visibility.rb:1]: If we're going to implement `visibility_strength` to include `protected`, we should probably have tests for it in both parent and child

File: gems/sorbet-runtime/test/types/visibility.rb [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+    child = Class.new(parent) do
+      extend T::Sig, T::Helpers
+      sig { override.returns(Integer) }
+      private def foo; 0; end
+    end
+
+    T::Private::Abstract::Validate.validate_subclass(child)
+  end
+
+  it "allows private/private overrides" do
```
Comment (jez) [inline gems/sorbet-runtime/test/types/visibility.rb]: is this test name copy/pasted from above?

File: gems/sorbet-runtime/test/types/visibility.rb
Comment (jez) [reply gems/sorbet-runtime/test/types/visibility.rb:1]: specifically, I think probably we want tests for `private` → `protected` and then `protected` → `private`.

(`public` → `protected` is probably redundant with the existing test for `public` → `private`, but you could add it if you want. `private`/`protected` → `public` also seems like it's not particularly at risk of being wrong)

File: gems/sorbet-runtime/lib/types/private/methods/signature_validation.rb [hunk 2]
```diff
@@ -276,6 +277,36 @@ def self.validate_override_types(signature, super_signature)
...
+            "* Base: #{super_vis} (in #{method_loc_str(super_method)})\n" \
+            "* #{mode_noun.capitalize}: #{vis} (in #{method_loc_str(method)})\n" \
+            "(The override must be at least as permissive as the supermethod)" \
+    end
+  end
+
+  private_class_method def self.method_visibility(method)
+    if method.owner.private_method_defined?(method.name, false)
+      return :private
+    elsif method.owner.public_method_defined?(method.name, false)
```
Comment (jez) [inline gems/sorbet-runtime/lib/types/private/methods/signature_validation.rb]: public methods are the overwhelming common case—probably makes sense to order this check first

File: gems/sorbet-runtime/lib/types/private/methods/signature_validation.rb [hunk 3]
```diff
@@ -276,6 +277,36 @@ def self.validate_override_types(signature, super_signature)
...
+
+    if visibility_strength(vis) > visibility_strength(super_vis)
+      raise "Incompatible visibility for #{mode_noun} of method #{method.name}\n" \
+            "* Base: #{super_vis} (in #{method_loc_str(super_method)})\n" \
+            "* #{mode_noun.capitalize}: #{vis} (in #{method_loc_str(method)})\n" \
+            "(The override must be at least as permissive as the supermethod)" \
+    end
+  end
+
+  private_class_method def self.method_visibility(method)
```
Comment (jez) [inline gems/sorbet-runtime/lib/types/private/methods/signature_validation.rb:303]: I wonder if it's worth mentioning that there is another helper that looks like this in `call_validation.rb`? or even whether it's worth factoring things to be able to reuse the code.

**Review by jez — APPROVED** [review]
great, thanks!

We're still blocked until we can test this on Stripe's codebase but the changes here are what we want

**Comment by CT075** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_SWXi3iPpSR5Z2d
→ https://go/builds/bui_SWXi9dGKJwr7ED
→ https://go/builds/bui_SWXj5I86yEV1wn

This change also has sorbet-runtime changes. Those tests:

→ https://go/builds/bui_SWXqrK1MGYUkpy

**Comment by CT075** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_SZ7T6Q2cUUZSl4
→ https://go/builds/bui_SZ7T8G38Enfc7T
→ https://go/builds/bui_SZ7U4eyCIGyNPD

This change also has sorbet-runtime changes. Those tests:

→ https://go/builds/bui_SZ7eLENlj2QoCS

**Comment by CT075** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_SZ85I42vPgLyi4
→ https://go/builds/bui_SZ85EFjtuASojc
→ https://go/builds/bui_SZ86XeaBYGeufB

This change also has sorbet-runtime changes. Those tests:

→ https://go/builds/bui_SZ8BU6No8GW6sf

**Comment by CT075** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_SZ9cGUXVZ2eVt5
→ https://go/builds/bui_SZ9clibSkhVcnc
→ https://go/builds/bui_SZ9dTHWIJfe0LC

This change also has sorbet-runtime changes. Those tests:

→ https://go/builds/bui_SZ9kQ0n55GEBwe

**Comment by CT075** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_Sb2BXffhxzORfW
→ https://go/builds/bui_Sb2BJJE6CTU4nZ
→ https://go/builds/bui_Sb2Crf23eLgQpJ

This change also has sorbet-runtime changes. Those tests:

→ https://go/builds/bui_Sb2Ioaf2M1YjJy

**Comment by CT075** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_SbQMrcn5FyN9xa
→ https://go/builds/bui_SbQM8tAZPpxCHC
→ https://go/builds/bui_SbQNBkn9hSNQCF

This change also has sorbet-runtime changes. Those tests:

→ https://go/builds/bui_SbQTc1YQdHb2UQ

**Comment by CT075** [comment]
The tests pass, so I think we're mostly good to go. @jez can you take one last look (since the approval is a bit stale)? I think [this](https://github.com/sorbet/sorbet/compare/a80dd3c..e9bc1cb) is the diff from the initial PR.

File: gems/sorbet-runtime/lib/types/private/methods/_methods.rb [hunk 4]
```diff
@@ -589,6 +589,19 @@ def self.install_hooks(mod)
...
+  # `name` must be an instance method (for class methods, pass in mod.singleton_class)
+  def self.visibility_method_name(mod, name)
+    if mod.public_method_defined?(name)
+      :public
+    elsif mod.protected_method_defined?(name)
+      :protected
+    elsif mod.private_method_defined?(name)
+      :private
+    else
+      mod.method(name) # Raises
```
Comment (jez) [inline gems/sorbet-runtime/lib/types/private/methods/_methods.rb]: minor, but so we don't forget for the future, might be worth this
```suggestion
      # Raises a NameError formatted like the Ruby VM would (the exact text formatting
      # of these errors changed across Ruby VM versions, in ways that would sometimes
      # cause tests to fail if they were dependent on hard coding errors).
      mod.method(name)
```

File: gems/sorbet-runtime/lib/types/private/methods/signature_validation.rb [hunk 5]
```diff
@@ -276,6 +277,33 @@ def self.validate_override_types(signature, super_signature)
     end
   end
 
+  def self.validate_override_visibility(signature, super_signature)
+    return if super_signature.mode == Modes.untyped
+    return unless [Modes.override, Modes.overridable_override].include?(signature.mode)
```
Comment (jez) [inline gems/sorbet-runtime/lib/types/private/methods/signature_validation.rb:287]: This behavior differs from the `validate_override_shapes` and `validate_override_types` call

1. Should it?
2. If it should, is it worth documenting why?

Comment (CT075) [reply gems/sorbet-runtime/lib/types/private/methods/signature_validation.rb:287]: Added a note about why; it's probably worth removing eventually, but maybe not worth blocking this PR on it.
