### PR TITLE
Fix error count reporting in metrics

### LINKED ISSUE #1211: Bug in metrics for error 7003
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20T1%3B%20end%0A%0Amodule%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Breturns(T1)%7D%0A%20%20def%20only_a%3B%20T.unsafe(nil)%3B%20end%0Aend%0A%0Amodule%20B%0A%20%20extend%20T%3A%3ASig%0Aend%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20%7Bparams(ab%3A%20T.all(A%2C%20B)).returns(T.untyped)%7D%0Adef%20test_one(ab)%0A%20%20T.assert_type!(ab.only_a%2C%20T1)%0Aend%0A)

```ruby
# typed: true
module T1; end

module A
  extend T::Sig

  sig {returns(T1)}
  def only_a; T.unsafe(nil); end
end

module B
  extend T::Sig
end

extend T::Sig

sig {params(ab: T.all(A, B)).returns(T.untyped)}
def test_one(ab)
  T.assert_type!(ab.only_a, T1)
end
```

Run `sorbet --metrics-file metrics.json`, you'll see that `No errors! Great job.`.

#### Observed output

In `metrics.json`:
```json
{
 "repo": "none",
 "sha": "none",
 "status": "Success",
 "branch": "none",
 "timestamp": "1562357143",
 "uuid": "0x1b24a8d7e24c58e1-0xed1eed05-0x48ab-0xacaf-0xcd7b32378d63cb280x41a7",
 "metrics": [
  ...
  {
   "name": "ruby_typer.unknown..error.p25",
   "value": 7003
  },
  {
   "name": "ruby_typer.unknown..error.p50",
   "value": 7003
  },
  {
   "name": "ruby_typer.unknown..error.p75",
   "value": 7003
  },
  {
   "name": "ruby_typer.unknown..error.p90",
   "value": 7003
  },
  {
   "name": "ruby_typer.unknown..error.min",
   "value": 7003
  },
  {
   "name": "ruby_typer.unknown..error.max",
   "value": 7003
  },
  {
   "name": "ruby_typer.unknown..error.total",
   "value": 1
  },
  ...
  ]
}
```

To debug further, apply this patch:
```diff
--- a/core/GlobalState.cc
+++ b/core/GlobalState.cc
@@ -10,6 +10,7 @@
 #include "core/Unfreeze.h"
 #include "core/errors/errors.h"
 #include <utility>
+#include <iostream>
 
 #include "absl/strings/str_cat.h"
 #include "absl/strings/str_split.h"
@@ -1221,6 +1222,7 @@ bool GlobalState::hadCriticalError() const {
 ErrorBuilder GlobalState::beginError(Loc loc, ErrorClass what) const {
     bool reportForFile = shouldReportErrorOn(loc, what);
     if (reportForFile) {
+        cout << "Error file: " << loc.file().data(*this).path() << ":" << loc.position(*this).first.line << ":" << loc.position(*this).first.column << "-" << loc.position(*this).second.line << ":" << loc.position(*this).second.column << " error code: " << what.code << endl;
         prodHistogramAdd("error", what.code, 1);
     }
     if (what == errors::Internal::InternalError) {
```

Then you'll see output like this:
```
Error file: ./temp.rb:19:18-19:27 error code: 7003
No errors! Great job.
```

So Sorbet thinks that the method `only_a` doesn't exist on `ab` (even though that method does exist) on line 19 for the metrics.

#### Expected behavior

Metrics should be consistent with the output on the screen, so there should be no errors in the metrics file.

### PR DESCRIPTION
**Pull request by aisamanra**
### Motivation
Fixes #1211: certain parts of our code will start to produce `Error` values that turn out to not be relevant, especially in type-checking: e.g. when we're dispatching a method `#m` on a value of type `T.all(X, Y)`, there will be situations where the method is not present on `X`, which will lead us to produce an `UnknownMethod` error, but we'll then find the method on `Y`, at which point we'll get rid of the error without adding it to the error queue. However, we were previously adding information to the metrics as soon as we _created_ an `Error` value, and not when we added it to the queue, which meant that these thrown-away errors would appear in the metrics output despite not appearing in the final output. This simply moves the logic so that we don't report an error to the metrics until we're sure it's going to show up in the output as well.

### Test plan

See included automated tests.

### CODE REVIEW

File: core/GlobalState.cc [hunk 1]
```diff
@@ -1211,6 +1211,9 @@ void GlobalState::_error(unique_ptr<Error> error) const {
         loc.file().data(*this).minErrorLevel_ = min(loc.file().data(*this).minErrorLevel_, error->what.minLevel);
     }
 
+    if (shouldReportErrorOn(loc, error->what)) {
```
Comment (DarkDimius) [inline core/GlobalState.cc]: I feel that this is still too early. The thing on the other end of error queue may decide to ignore the error.

**Comment by aisamanra** [comment]
Oh, you're absolutely right. I've pushed one that I've confirmed breaks against master.
