### PR TITLE
Process all arguments to private modifiers

### LINKED ISSUE #3661: private can take multiple symbol arguments
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20def%20foo%3B%20end%0A%20%20def%20bar%3B%20end%0A%0A%20%20private%20%3Afoo%2C%20%3Abar%0Aend%0A%0A%23%20missing%20two%20errors%3A%0AA.new.foo%20%23%20%3D%3E%20NoMethodError%3A%20private%20method%20%60foo'%20called%0AA.new.bar%20%23%20%3D%3E%20NoMethodError%3A%20private%20method%20%60bar'%20called)

```ruby
# typed: true
class A
  def foo; end
  def bar; end

  private :foo, :bar
end

# missing two errors:
A.new.foo # => NoMethodError: private method `foo' called
A.new.bar # => NoMethodError: private method `bar' called
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

This should behave identically to having written `private :foo; private :bar`:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20def%20foo%3B%20end%0A%20%20def%20bar%3B%20end%0A%0A%20%20private%20%3Afoo%0A%20%20private%20%3Abar%0Aend%0A%0AA.new.foo%20%23%20error%3A%20Non-private%20call%20to%20private%20method%20%60A%23foo%60%0AA.new.bar%20%23%20error%3A%20Non-private%20call%20to%20private%20method%20%60A%23bar%60)

```ruby
# typed: true
class A
  def foo; end
  def bar; end

  private :foo
  private :bar
end

A.new.foo # error: Non-private call to private method `A#foo`
A.new.bar # error: Non-private call to private method `A#bar`
```

```
editor.rb:10: Non-private call to private method A#foo https://srb.help/7031
    10 |A.new.foo # error: Non-private call to private method `A#foo`
        ^^^^^^^^^
    editor.rb:3: Defined as
     3 |  def foo; end
          ^^^^^^^

editor.rb:11: Non-private call to private method A#bar https://srb.help/7031
    11 |A.new.bar # error: Non-private call to private method `A#bar`
        ^^^^^^^^^
    editor.rb:4: Defined as
     4 |  def bar; end
          ^^^^^^^
Errors: 2
```

- - -

This is a bug for all the other method visibility modifiers too: `private` / `public` / `private_class_method` / `protected`.

### PR DESCRIPTION
**Pull request by jez**
### Motivation

Fixes #3661.

### Test plan

See the commit history for the diff to the test.

### CODE REVIEW

File: namer/namer.cc [hunk 1]
```diff
@@ -469,59 +469,59 @@ class SymbolFinder {
...
+    void addMethodModifier(core::Context ctx, core::NameRef modifierName, const ast::TreePtr &arg) {
+        auto target = unwrapLiteralToMethodName(ctx, arg);
+        if (target.exists()) {
+            foundDefs->addModifier(Modifier{
+                Modifier::Kind::Method,
+                getOwner(),
+                arg.loc(),
+                /*name*/ modifierName,
+                target,
+            });
```
Comment (elliottt) [inline namer/namer.cc:499]: 👍

**Review by elliottt — COMMENTED** [review]
🚢
