### PR TITLE
Method renames: handle secondary dispatch components (union types)

### LINKED ISSUE #3665: Rename symbol fails to consider all components of a method call
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20def%20foo%3B%20end%0Aend%0Aclass%20B%0A%20%20def%20foo%3B%20end%0Aend%0A%0Aextend%20T%3A%3ASig%0Asig%20%7Bparams(x%3A%20T.any(A%2C%20B)).void%7D%0Adef%20example(x)%0A%20%20x.foo%0A%23%20%20%20%5E%20apply-rename%3A%20%5BA%5D%20newName%3A%20bar%0Aend)

```ruby
# typed: true
class A
  def foo; end
end
class B
  def foo; end
end

extend T::Sig
sig {params(x: T.any(A, B)).void}
def example(x)
  x.foo
#   ^ apply-rename: [A] newName: bar
end
```

#### Observed output

Making the indicated rename request in sorbet.run only applies the rename to the first component of the dispatch result.

Namely, it only renames `A#foo` → `A#bar`, and neglects the fact that the LSP query returned that the method call could have also been to `B#foo`.

#### Expected behavior

Either:

- We should rename each method in the dispatch result, or
- We should detect the case where there are multiple dispatch results, and abort (better than doing the wrong thing).

- - -

### PR DESCRIPTION
**Pull request by soam-stripe**
While searching for related symbols in method renames, handle multiple dispatch results in sends. When we find a secondary dispatch result, we follow the dispatch result linked list, adding any new methods we find. You can think of this code as the traversal of a graph where nodes are methods, and edges exist between methods that are related either by overriding or by being used in a union type.

(previous PR: #3746)

### Motivation

Fixes #3665 -- the current code doesn't handle cases where there is more than one dispatch result for a send.

### Test plan

See included automated tests.

### CODE REVIEW

File: main/lsp/requests/rename.cc [hunk 1]
```diff
@@ -91,6 +90,74 @@ core::SymbolRef findRootClassWithMethod(const core::GlobalState &gs, core::Symbo
     return root;
 }
 
+class UniqueSymbolQueue {
+public:
+    UniqueSymbolQueue() : iter(0) {}
+
+    bool tryEnqueue(core::SymbolRef s) {
+        auto insertResult = set.insert(s);
+        bool isNew = insertResult.second;
```
Comment (jvilk-stripe) [inline main/lsp/requests/rename.cc:99]: TIL this returns pair that indicates if insertion added an element!

File: main/lsp/requests/rename.cc [hunk 2]
```diff
@@ -91,6 +90,74 @@ core::SymbolRef findRootClassWithMethod(const core::GlobalState &gs, core::Symbo
...
+            auto result = symbols[iter];
+            iter++;
+            return result;
+        }
+        return core::SymbolRef();
+    }
+
+private:
+    int iter;
+    vector<core::SymbolRef> symbols;
```
Comment (jvilk-stripe) [inline main/lsp/requests/rename.cc:117]: You can actually make this a `std::deque` so you can push things on the end and pop things off the front (or vice-versa). Then you don't need `iter`.

File: main/lsp/requests/rename.cc [hunk 3]
```diff
@@ -91,6 +90,74 @@ core::SymbolRef findRootClassWithMethod(const core::GlobalState &gs, core::Symbo
...
+        auto insertResult = set.insert(s);
+        bool isNew = insertResult.second;
+        if (isNew) {
+            symbols.emplace_back(s);
+        }
+        return isNew;
+    }
+
+    core::SymbolRef pop() {
+        if (iter < symbols.size()) {
```
Comment (jvilk-stripe) [inline main/lsp/requests/rename.cc:107]: With a deque, this becomes `if (!symbols.empty())`

File: test/testdata/lsp/rename/method_nilable.rb [hunk 4]
```diff
@@ -0,0 +1,18 @@
+# typed: true
+# frozen_string_literal: true
+
+class C1
+  def m1
+#      ^ apply-rename: [A] newName: m2
```
Comment (jez) [inline test/testdata/lsp/rename/method_nilable.rb:6]: Nice! Super cool to see that `c&.m1` is renamed below.

**Review by jez — COMMENTED** [review]
i only did a cursory look. excited to see this bug fixed, and i'll let john finish the review

**Review by jvilk-stripe — APPROVED** [review]
I had a minor suggestion that will clean up the UniqueSymbolQueue.
