### PR TITLE
Sort operators later in completion results

### LINKED ISSUE #5148: Completion results should sort punctuation-only methods to the bottom
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20%7Bparams%28x%3A%20Integer%29.void%7D%0Adef%20foo%28x%29%0A%20%20x.%0A%20%20%23%20%5E%20completion%3A%20abs%2C%20...%0Aend)

```ruby
# typed: true
extend T::Sig

sig {params(x: Integer).void}
def foo(x)
  x.
  # ^ completion: abs, ...
end
```

#### Observed output

```
editor.rb:8: unexpected token "end" https://srb.help/2001
     8 |end
        ^^^
Errors: 1
```

Screen Shot 2022-01-24 at 10 53 22 PM

#### Expected behavior

Punctuation methods are very unlikely to be what the user wants after typing `x.` here. We should put them lower in the list.
- - -

### PR DESCRIPTION
**Pull request by elliottt**
Sort method operators later in completion results, as users are usually looking for named methods instead. This change moves all operators after all textual method names, but preserves the existing depth heuristic ordering for each group.

After this change, operators will no longer be the first thing in the completion results list:
Screenshot 2025-06-02 at 17 32 44

Whereas before, you would see methods like `%` always bubble to the top.
Screenshot 2025-06-02 at 11 31 01

### Motivation
Fixes #5148

### Test plan

See included automated tests.

### CODE REVIEW

File: test/testdata/lsp/completion/operators.rb [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+    "hi"
+  end
+end
+
+sig { params(x: A).void }
+def test(x)
+  # We should see the completion item for `%` sorted later, as users are for the
+  # most part not looking for operator completions.
+  x.
+  # ^ completion: test, %, class, ...
```
Comment (jez) [inline test/testdata/lsp/completion/operators.rb]: I wonder if we should go further and sort these all the way to the bottom. `x.class` is still more likely than `x.%(y)`

File: main/lsp/requests/completion.cc [hunk 2]
```diff
@@ -969,18 +971,25 @@ vector<SimilarMethod> computeDedupedMethods(const core::GlobalState &gs, const c
...
+
+        if (absl::StartsWith(leftShortName, prefix) && !absl::StartsWith(rightShortName, prefix)) {
+            return true;
+        }
+        if (!absl::StartsWith(leftShortName, prefix) && absl::StartsWith(rightShortName, prefix)) {
+            return false;
+        }
 
-            return leftShortName < rightShortName;
+        // We want to sort operators later, but still keep lower depth operators higher in the list.
```
Comment (jez) [inline main/lsp/requests/completion.cc]: related to my other comment, I'm kind of find if we completely lose the ancestor depth information for operators—so long as it's still deterministic—if it means that they're truly at the way bottom.

File: main/lsp/requests/completion.cc [hunk 3]
```diff
@@ -969,18 +971,25 @@ vector<SimilarMethod> computeDedupedMethods(const core::GlobalState &gs, const c
...
+        bool leftOper = absl::c_contains(OPERATOR_CHARS, leftShortName.front());
+        bool rightOper = absl::c_contains(OPERATOR_CHARS, rightShortName.front());
```
Comment (jez) [inline main/lsp/requests/completion.cc]: not blocking: I wonder if `absl::StrContains` is better optimized for strings here? I can't tell from godbolt

https://godbolt.org/z/9feMeE1xh

and I'm too lazy to write a microbenchmark

File: main/lsp/requests/completion.cc [hunk 4]
```diff
@@ -969,18 +971,25 @@ vector<SimilarMethod> computeDedupedMethods(const core::GlobalState &gs, const c
...
-        if (leftShortName != rightShortName) {
-            if (absl::StartsWith(leftShortName, prefix) && !absl::StartsWith(rightShortName, prefix)) {
-                return true;
-            }
-            if (!absl::StartsWith(leftShortName, prefix) && absl::StartsWith(rightShortName, prefix)) {
-                return false;
-            }
+        if (leftShortName == rightShortName) {
+            return left.method.id() < right.method.id();
+        }
```
Comment (jez) [inline main/lsp/requests/completion.cc]: Not blocking: I wonder if we even need this case. I guess it's for like, overloads? But I don't think that our test suite is discerning enough to care whether overloads actually came back in a different sorted order. e.g., the `^ completion` assertions wouldn't disambiguate between `^ completion: overload.1, overload.2` or anything like that, and I don't think our test harness has anything to say about the associated documentation information included in the CompletionItem, short of a LSP recording test, which I don't think we have for completion.

File: test/testdata/lsp/completion/operators.rb (hunk 1 above)
Comment (elliottt) [reply test/testdata/lsp/completion/operators.rb]: That's what I had done initially, but had thought it might be worth keeping methods defined on that class earlier in the list. Happy to go either way on this one.

File: main/lsp/requests/completion.cc (hunk 4 above)
Comment (elliottt) [reply main/lsp/requests/completion.cc]: If we're not worried about keeping the sort order in the results deterministic, is the only reason for keeping overloads in the list for documentation?

File: main/lsp/requests/completion.cc (hunk 3 above)
Comment (elliottt) [reply main/lsp/requests/completion.cc]: `StrContains` generates significantly less code, so I'm happy to switch to that.

Comment (jez) [reply main/lsp/requests/completion.cc]: less code but that's mostly because it hides code behind the dynamically linked call to `memchr` `¯\_(ツ)_/¯`. The c_contains one doesn't have any `call` instructions, I don't think. If the link settings were different such that it got inlined, maybe it generates the same (or more) code?

File: main/lsp/requests/completion.cc (hunk 4 above)
Comment (jez) [reply main/lsp/requests/completion.cc]: I guess that I never captured the work to be done for overloads.

I think the fact that overloads show up as duplicate entries in the list is probably not a great outcome. Probably it would be better to have a single CompletionItem, but in the documentation show an overloaded signature like

```ruby
sig { params(x: Integer).void }
sig { params(x: String).void }
def some_overloaded_method(x); end
```

In practice, I don't think anyone explicitly chooses an overload when they're accepting a completion item. I think the only reason I can possibly think why we _might_ want to leave the completion items separate is **if** there were a way to connect the chosen completion item to a subsequent "signature help" menu item showing which specific argument types you can provide for something.

But even if that were a feature of the LSP spec (I don't think it is?), we probably still want to collapse the duplicate entries just for cleanliness in the completion dropdown.

File: main/lsp/requests/completion.cc (hunk 3 above)
Comment (elliottt) [reply main/lsp/requests/completion.cc]: I totally missed that! The `c_contains` version has no calls at all, so maybe we should keep that one after all.

Comment (jez) [reply main/lsp/requests/completion.cc]: not to keep going down this rabbit hole, but I could also imagine that memchr in libc++ is implemented with a ton of vector instructions `¯\_(ツ)_/¯` so really it's hard to say

File: main/lsp/requests/completion.cc (hunk 2 above)
Comment (elliottt) [reply main/lsp/requests/completion.cc]: They'll stay ordered by depth now, but in a section that comes after all other methods.

File: main/lsp/requests/completion.cc (hunk 3 above)
Comment (elliottt) [reply main/lsp/requests/completion.cc]: Eh, it's a short constant defined in this file, so that might also tip the balance back towards a short loop with no calls.

File: main/lsp/requests/completion.cc (hunk 4 above)
Comment (elliottt) [reply main/lsp/requests/completion.cc]: This seems like it'll have some other fallout, so I'm going to pull it into a separate PR.
