### PR TITLE
Fix #1438

### LINKED ISSUE #1438: Unexpected code is unreachable
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20T%3A%3ABoolean).void%7D%0A%20%20def%20testing(x)%0A%20%20%20%20bar%20%3D%20!x%0A%20%20%20%20zap%20%3D%20!bar%20%7C%7C%20123%0A%0A%20%20%20%20if%20x%0A%20%20%20%20%20%20raise%0A%20%20%20%20end%0A%0A%20%20%20%20bar%0A%20%20end%0Aend)

```ruby
# typed: true
class A
  extend T::Sig

  sig {params(x: T::Boolean).void}
  def testing(x)
    bar = !x
    zap = !bar || 123

    if x
      raise
    end

    bar
  end
end
```

#### Observed output

```
editor.rb:11: This code is unreachable https://srb.help/7006
    11 |      raise
              ^^^^^

editor.rb:14: This code is unreachable https://srb.help/7006
    14 |    bar
            ^^^
Errors: 2
```

#### Expected behavior

Code should not be unreachable

### PR DESCRIPTION
**Pull request by DarkDimius**
### Motivation
I'm on run

### Test plan
Added test from issue

### CODE REVIEW

File: infer/environment.cc [hunk 1]
```diff
@@ -348,8 +348,8 @@ void Environment::updateKnowledge(core::Context ctx, core::LocalVariable local,
         if (fnd != vars.end()) {
             whoKnows.truthy = fnd->second.knowledge.falsy;
             whoKnows.falsy = fnd->second.knowledge.truthy;
-            fnd->second.knowledge.truthy.mutate().noTypeTests.emplace_back(local, core::Types::falsyTypes());
```
Comment (DarkDimius) [inline infer/environment.cc]: this was reverse from how it should have been.

**Comment by elliottt** [comment]
Fixes #1438

**Comment by DarkDimius** [comment]
Checked on pay-server that this doesn't introduce new errors go/kgKtkfF2
