### PR TITLE
Fix a parser crash with empty match vars

### LINKED ISSUE #8903: LSP crashes at typedruby_release_bison.cc:8124:9
Sorbet LSP crashes when a open a file with the following content.

Sorbet version 0.5.12058.20250502171628-3d94f25ee

#### Input

[→ View on sorbet.run](https://sorbet.run/#case%20foo%3B%20in%20%7B%22%22%3A%2C%20n2%3A%2C%20%22n3%3A%7D%20then%20true%3B%20end%0A)

```ruby
case foo; in {"":, n2:, "n3:} then true; end

```

#### Observed output

```
Loading...
```
There is a crash in sorbet.run web console.

It also crashes when I run it locally, with the following stack trace.

```
👋 Hey there! Heads up that this is not a release build of sorbet.
Release builds are faster and more well-supported by the Sorbet team.
Check out the README to learn how to build Sorbet in release mode.
To forcibly silence this error, either pass --silence-dev-message,
or set SORBET_SILENCE_DEV_MESSAGE=1 in your shell environment.

Sorbet raised uncaught exception type="std::out_of_range" what="`InlinedVector::at(size_type)` failed bounds check"
Backtrace:
  #3 0x55555645b172 in std::__terminate(void (*)()) cxa_handlers.cpp:0:0
  #4 0x55555645aa66 __cxa_rethrow
  #5 0x555557678674 in ruby_parser::bison::typedruby_release::parser::parse() /proc/self/cwd/bazel-out/k8-fastbuild/bin/parser/parser/typedruby_release_bison.cc:8124:9
  #6 0x5555575ff524 in ruby_parser::typedruby_release::parse(void const*, bool) /proc/self/cwd/parser/parser/cc/driver.cc:223:7
  #7 0x5555575fbb68 in sorbet::parser::Builder::build(ruby_parser::base_driver*, bool) const /proc/self/cwd/parser/Builder.cc:2719:37
  #8 0x5555574ff91c in sorbet::parser::Parser::run(sorbet::core::GlobalState&, sorbet::core::FileRef, sorbet::parser::Parser::Settings, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>) /proc/self/cwd/parser/Parser.cc:146:24
  #9 0x5555569c8657 in sorbet::realmain::pipeline::(anonymous namespace)::runParser(sorbet::core::GlobalState&, sorbet::core::FileRef, sorbet::realmain::options::Printers const&, bool, bool) /proc/self/cwd/main/pipeline/pipeline.cc:212:17
  #10 0x5555569c5689 in sorbet::realmain::pipeline::indexOne(sorbet::realmain::options::Options const&, sorbet::core::GlobalState&, sorbet::core::FileRef, sorbet::ast::ExpressionPtr) /proc/self/cwd/main/pipeline/pipeline.cc:300:30
  #11 0x5555569cec9b in sorbet::realmain::pipeline::index(sorbet::core::GlobalState&, absl::lts_20240722::Span<sorbet::core::FileRef const>, sorbet::realmain::options::Options const&, sorbet::WorkerPool&, std::__1::unique_ptr<sorbet::OwnedKeyValueStore const, std::__1::default_delete<sorbet::OwnedKeyValueStore const>> const&, bool) /proc/self/cwd/main/pipeline/pipeline.cc:644:31
  #12 0x55555654474f in sorbet::realmain::realmain(int, char**) /proc/self/cwd/main/realmain.cc:695:23
  #13 0x5555564d3c6a in main /proc/self/cwd/main/main.cc:6:16
  #14 0x7ffff7cee5d0 __libc_start_call_main
  #15 0x7ffff7cee680 __libc_start_main@GLIBC_2.2.5
  #16 0x555556394945 _start

Aborted

```

#### Expected behavior

It should not crash.

- - -

### PR DESCRIPTION
**Pull request by elliottt**
Sorbet is crashing when encountering an unterminated string symbol in a match expression. This PR fixes the problem by catching the empty case, and entering it manually.

This introduces a new parser error, with text that mirrors the error from the ruby parser:

```
irb(main):002:0> case nil; in {"":} then true end
/Users/trevor/.rbenv/versions/3.1.2/lib/ruby/3.1.0/irb/workspace.rb:119:in `eval': (irb):2: key must be valid as local variables (SyntaxError)
case nil; in {"":} then true end
              ^~~
(irb):2: identifier  is not valid to set
        from /Users/trevor/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
        from /Users/trevor/.rbenv/versions/3.1.2/bin/irb:25:in `load'
        from /Users/trevor/.rbenv/versions/3.1.2/bin/irb:25:in `<main>'
```

and from Sorbet after this change:

```
% ./bazel-bin/main/sorbet test/testdata/parser/crash_case_empty_var.rb
👋 Hey there! Heads up that this is not a release build of sorbet.
Release builds are faster and more well-supported by the Sorbet team.
Check out the README to learn how to build Sorbet in release mode.
To forcibly silence this error, either pass --silence-dev-message,
or set SORBET_SILENCE_DEV_MESSAGE=1 in your shell environment.

test/testdata/parser/crash_case_empty_var.rb:4: key must be valid as local variables https://srb.help/2001
     4 |case T.unsafe(nil); in {"":} then true; end
                                ^^^
Errors: 1
```

### Motivation
Fixes #8903

### Test plan

See included automated tests.

### CODE REVIEW

File: parser/Builder.cc [hunk 1]
```diff
@@ -1206,6 +1206,10 @@ class Builder::Impl {
                 // Label key is a symbol `sym: val`
                 return match_var_hash(label->loc, key->val.show(gs_));
             } else if (auto *key = parser::cast_node<DSymbol>(pair->key.get())) {
+                if (key->nodes.empty()) {
```
Comment (jez) [inline parser/Builder.cc:1209]: For what it's worth, it looks like all string-quoted keys are not allowed in the punned hash key/val pairs

```ruby
❯ ruby -e '{"x":}'
-e:1: syntax error, unexpected '}'
{"x":}
```

not just empty strings.

File: parser/Builder.cc [hunk 2]
```diff
@@ -1206,6 +1206,10 @@ class Builder::Impl {
...
+                    error_without_recovery(ruby_parser::dclass::InvalidKey, key->loc);
```
Comment (jez) [inline parser/Builder.cc:1210]: Can we recover to a tree like this?

```
{:"" => <ErrorNode>}
```

?

It seems like we're already in the semantic actions so recovering with an error node seems like it would be easy enough.

File: parser/parser/codegen/generate_diagnostics.cc [hunk 3]
```diff
@@ -78,6 +78,7 @@ tuple<string, string> MESSAGES[] = {
     {"NoAnonymousBlockArg", "no anonymous block parameter"},
     {"NoAnonymousRestArg", "no anonymous rest parameter"},
     {"NoAnonymousKwrestArg", "no anonymous keyword rest parameter"},
+    {"InvalidKey", "key must be valid as local variables"},
```
Comment (jez) [inline parser/parser/codegen/generate_diagnostics.cc:81]: I don't know how important this is but both the whitequark parser and the ruby parser seem to report an unexpected token error:

```
❯ ruby-parse -e '{"x":}'
warning: parser/current is loading parser/ruby31, which recognizes 3.1.4-compliant syntax, but you are running 3.1.2.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
(fragment:0):1:6: error: unexpected token tRCURLY
(fragment:0):1: {"x":}
(fragment:0):1:      ^

~/sorbet (jez-package-namespaces-with-owner)
❯ ruby -e '{"x":}'
-e:1: syntax error, unexpected '}'
{"x":}
```

all else being equal it's probably better to have our own custom error for this if it means that we can provide better parse error recovery for it, so I'm fine with the new dclass but I'm curious to know what's different about our parser vs those parsers that is going through a different code path.

**Review by jez — CHANGES_REQUESTED** [review]

File: parser/parser/codegen/generate_diagnostics.cc (hunk 3 above)
Comment (jez) [reply parser/parser/codegen/generate_diagnostics.cc:81]: Sorry it seems like this is actually specific to pattern matching, and the error message is the same as upstream.

```
~/sorbet (jez-package-namespaces-with-owner)
❯ ruby -e 'case {}; in {"":} then true; end'
-e:1: key must be valid as local variables
case {}; in {"":} then true; end
-e:1: identifier  is not valid to set

~/sorbet (jez-package-namespaces-with-owner)
❯ ruby -e 'case {}; in {"x":} then true; end'
-e:1:in `<main>': {}: key not found: :x (NoMatchingPatternKeyError)

~/sorbet (jez-package-namespaces-with-owner)
❯ ruby -e 'case {}; in {"x y":} then true; end'
-e:1: key must be valid as local variables
case {}; in {"x y":} then true; end
-e:1: identifier x y is not valid to set
```

but in any case, it's not just empty string that's invalid

Comment (elliottt) [reply parser/parser/codegen/generate_diagnostics.cc:81]: Ah, true. I don't think that we can handle the second case, as it's a dynamic property of the value being examined, but the third case is definitely something we could raise an error for.

File: parser/Builder.cc (hunk 2 above)
Comment (elliottt) [reply parser/Builder.cc:1210]: Yep, we could return an `ErrorNode` instead of an `""` name.

File: parser/parser/codegen/generate_diagnostics.cc (hunk 3 above)
Comment (jez) [reply parser/parser/codegen/generate_diagnostics.cc:81]: yep, the second case I was just trying to show that the logic is not "are there quotes around the name" which I suspected might be the case, like maybe `{x:}` was fine but `{"x":}` was not fine because it had quotes (which would be easier to detect in Builder.cc than trying to check valid variable names)

Comment (jez) [reply parser/parser/codegen/generate_diagnostics.cc:81]: Is the plan to merge this and handle the non-empty "key must be valid as local variable" in a follow up change / an open issue?

Comment (jez) [reply parser/parser/codegen/generate_diagnostics.cc:81]: I don't know whether there's an easy helper for this. Might be best to just over-eagerly allow things—I don't think that having `{"x y":}` causes problems for Sorbet.

Might want to add a test case and defer solving in Prism.

Comment (elliottt) [reply parser/parser/codegen/generate_diagnostics.cc:81]: My timebox ran out, and I agree that this will be easier to handle when we upgrade to prism 👍
