### PR TITLE
Check for private methods in prop overrides

### LINKED ISSUE #9213: Runtime failure when props override private methods
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Module%0A%20%20include%20T%3A%3ASig%0Aend%0A%0Amodule%20A%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20abstract!%0A%0A%20%20sig%20%7B%20abstract.returns%28Integer%29%20%7D%0A%20%20private%20def%20foo%3B%20end%0Aend%0A%0Aclass%20B%20%3C%20T%3A%3AStruct%0A%20%20include%20A%0A%0A%20%20const%20%3Afoo%2C%20Integer%2C%20override%3A%20%3Areader%20%23%20fails%20at%20runtime%0Aend)

```ruby
# typed: true

class Module
  include T::Sig
end

module A
  extend T::Helpers

  abstract!

  sig { abstract.returns(Integer) }
  private def foo; end
end

class B < T::Struct
  include A

  const :foo, Integer, override: :reader # fails at runtime
end
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

We allow regular methods to override private methods, so props should be allowed as well.

- - -

### PR DESCRIPTION
**Pull request by CT075**
### Motivation

Resolves #9213

### Test plan

See included automated tests.

### CODE REVIEW

**Comment by jez** [comment]
It looks like you committed some stray formatting edits in addition to your change. To make it easier to review, I reverted the formatting edits so that I could find the core part of the change.

@CT075 I pushed those reverted formatting changes to your branch.

File: gems/sorbet-runtime/lib/types/props/decorator.rb [hunk 1]
```diff
@@ -318,7 +318,10 @@ def prop_validate_definition!(name, cls, rules, type)
 
   sig(:final) { params(name: Symbol).returns(T::Boolean).checked(:never) }
   private def method_defined_on_ancestor?(name)
-    @class.method_defined?(name) && !@class.method_defined?(name, false)
+    (@class.method_defined?(name) || @class.private_method_defined?(name)) &&
+      # Unfortunately, older versions of ruby don't allow the second parameter on
+      # `private_method_defined?`.
```
Comment (jez) [inline gems/sorbet-runtime/lib/types/props/decorator.rb:323]: Does this not imply that this function simply does the wrong thing on those older Ruby versions? Wouldn't we be able to make a test case that uses `private` methods that still fails even with this change?

And in that case, we should either:

- Commit to dropping support for Ruby 2.7, which was marked end of life over 2.5 years ago
- Conditionally define this method twice:

  ```ruby
  if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('3.0')
    def method_defined_on_ancestor?(name)
      # ... the ideal version ...
    end
  else
    def method_defined_on_ancestor?(name)
      # ... the "best effort" version for before Ruby 3.0
    end
  end
  ```

Comment (CT075) [reply gems/sorbet-runtime/lib/types/props/decorator.rb:323]: Yes, the case that fails is this one:

```ruby
# typed: true

require_relative "../../../gems/sorbet-runtime/lib/sorbet-runtime"

class A < T::Struct
  extend T::Sig
  extend T::Helpers

  abstract!

  sig { abstract.returns(Integer) }
  private def foo; end

  const :foo, Integer, override: true # should fail
end
```

I don't have a strong opinion as to which option is better. I am more loosely leaning towards dropping support for older Ruby versions, but anything is fine with me.

Comment (jez) [reply gems/sorbet-runtime/lib/types/props/decorator.rb:323]: Let's at least make sure to add that as a test case, and we can chat about the compatibility path forward separately.

**Comment by CT075** [comment]
@jez

**Review by jez — APPROVED** [review]
