### PR TITLE
Fix the parsing of `foo.(x)`

### LINKED ISSUE #1029: Too many arguments provided for method BasicObject#!. Expected: 0, got: 1
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%20%0A%0A%20%20sig%20%7B%20params(v%3A%20Integer).void%20%7D%0A%20%20def%20call(v)%20%0A%20%20end%20%20%20%20%0Aend%0A%0Aa%20%3D%20A.new%0Aa.(42)%0A%0A)

```ruby
# typed: true

class A
  extend T::Sig 

  sig { params(v: Integer).void }
  def call(v) 
  end    
end

a = A.new
a.(42)
```

#### Observed output

```
editor.rb:12: Too many arguments provided for method BasicObject#!. Expected: 0, got: 1 https://srb.help/7004
    12 |a.(42)
        ^^^^^^
    https://github.com/sorbet/sorbet/tree/c553e082d9227d7c8112816b804eb150c46cb8ee/rbi/core/basic_object.rbi#L5: ! defined here
     5 |  def !(); end
          ^^^^^^^
Errors: 1
```
#### Expected behavior

The result should be the same as for `T.reveal_type a.call(42)`

```
No errors! Great job.
```

### PR DESCRIPTION
**Pull request by elliottt**
The parsing of `foo.(x)` is not correct.

### Motivation
To resolve #1029 

### Test plan
The tests for the parse of the call method have been updated.

See included automated tests.

### CODE REVIEW

File: parser/Builder.cc [hunk 1]
```diff
@@ -391,7 +391,8 @@ class Builder::Impl {
 
         core::NameRef method;
         if (selector == nullptr) {
-            method = core::Names::bang();
+            // when the selector is missing, this is a use of the `call` method.
+            method = core::Names::call();
```
Comment (jez) [inline parser/Builder.cc]: What the heck lol why was this ever `bang()` 🤔

File: test/testdata/parser/whitequark/parse_send_call_1.rb.parse-tree.exp [hunk 2]
```diff
@@ -12,7 +12,7 @@ Begin {
         args = [
         ]
       }
-      method = <U !>
+      method = <U call>
```
Comment (jez) [inline test/testdata/parser/whitequark/parse_send_call_1.rb.parse-tree.exp]: What do you think about adding the test case from #1029 ?

File: parser/Builder.cc (hunk 1 above)
Comment (elliottt) [reply parser/Builder.cc]: Yeah..

File: test/testdata/parser/whitequark/parse_send_call_1.rb.parse-tree.exp (hunk 2 above)
Comment (elliottt) [reply test/testdata/parser/whitequark/parse_send_call_1.rb.parse-tree.exp]: I had originally added more tests, but then found that there were already two tests in the whitequark suite. Given that they covered that case, I decided to leave it out.
