### PR TITLE
Fix crash in TEnum rewriter pass

### LINKED ISSUE #7190: Sorbet Crashed: T::Enum with enum = new(nil)
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Test%20%3C%20T%3A%3AEnum%0A%20%20enums%20do%0A%20%20%20%20A%20%3D%20new%28'a'%29%0A%20%20%20%20B%20%3D%20new%28nil%29%0A%20%20end%0Aend)

```ruby
# typed: true

class Test < T::Enum
  enums do
    A = new('a')
    B = new(nil)
  end
end
```

#### Observed output
Sorbet crash with backtrace
```
Exception::raise(): TypePtr::underlying called on non-proxy-type `ClassType`

Backtrace:
  #3 0xc3c623 sorbet::core::TypePtr::underlying()
  #4 0xb46a2f sorbet::rewriter::(anonymous namespace)::collectNewStats()
  #5 0xb45bef sorbet::rewriter::TEnum::run()
  #6 0xb3aa61 sorbet::ast::TreeMapper<>::mapIt()
  #7 0xb3a5d3 sorbet::ast::TreeMapper<>::mapIt()
  #8 0xb3a5d3 sorbet::ast::TreeMapper<>::mapIt()
  #9 0xb39e64 sorbet::rewriter::Rewriter::run()
  #10 0x7a8279 sorbet::realmain::pipeline::indexOne()
  #11 0x7b9427 std::__1::__function::__func<>::operator()()
  #12 0xca9977 std::__1::__function::__func<>::operator()()
  #13 0xca927b std::__1::__function::__func<>::operator()()
  #14 0xca9c3b Joinable::trampoline()
  #15 0x7f0f9b30a609 start_thread
  #16 0x7f0f9b229133 __clone
```

#### Expected behavior

Type check run normally.

- - -

### PR DESCRIPTION
**Pull request by neilparikh**
### Motivation

Fixes #7190

### Test plan

See included automated tests.

### CODE REVIEW

File: rewriter/TEnum.cc [hunk 1]
```diff
@@ -134,9 +134,12 @@ std::optional<ProcessStatResult> processStat(core::MutableContext ctx, ast::Clas
...
         if (auto *selfNewArg = ast::cast_tree<ast::Literal>(selfNew->getPosArg(0))) {
-            // If the enum has exactly one variant that as a literal passed (ex. "a"),
-            // then its type will be String("a"), but we want a ClassType as the return type.
-            serializeType = selfNewArg->value.underlying(ctx);
+            serializeType = selfNewArg->value;
+            if (is_proxy_type(serializeType)) {
+                // If the enum has exactly one variant that has a literal passed (ex. "a"),
+                // then its type will be String("a"), but we want a ClassType as the return type.
+                serializeType = serializeType.underlying(ctx);
+            }
```
Comment (jez) [inline rewriter/TEnum.cc:142]:
```suggestion
            // If the enum has exactly one variant that has a literal passed (ex. "a"),
            // then its type will be String("a"), but we want a ClassType as the return type.
            serializeType = core::Types::dropLiteral(ctx, selfNewArg->value);
```

**Review by jez — APPROVED** [review]

**Comment by neilparikh** [comment]
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_OMrFmvmy6lptJC
→ https://go/builds/bui_OMrFvYFcQ9PfC1
→ https://go/builds/bui_OMrFwPo2bxmWLH
