### PR TITLE
Fix infer segfault due to moved TestedKnowledge

### LINKED ISSUE #1558: segfault with conditional variable assignment
#### Input

```ruby
# typed: true
if foo
  bar = 3
end
quz = foo if quz || bar
quz
```

#### Observed output

segfault

#### Expected behavior

no segfault

---

interestingly, the following does not segfault:

```rb
# typed: true
if foo
  bar = 3
end
if quz || bar
  quz = foo
end
quz
```

### PR DESCRIPTION
**Pull request by aisamanra**
### Motivation
Fixes #1558; the segfault was because a specific use of `setTypeAndOrigin` was invalidating a local pointer to a `TestedKnowledge` value; we can fix this by grabbing the information we need (two specific vectors) out of that value earlier.

### Test plan

See included automated tests. Added the fuzzed test case.

### CODE REVIEW

File: infer/environment.cc [hunk 1]
```diff
@@ -538,13 +538,15 @@ void Environment::assumeKnowledge(core::Context ctx, bool isTrue, core::LocalVar
...
-    auto &knowledgeToChoose = isTrue ? thisKnowledge.truthy : thisKnowledge.falsy;
-
     if (isDead) {
         return;
     }
 
-    for (auto &typeTested : knowledgeToChoose->yesTypeTests) {
+    auto &knowledgeToChoose = isTrue ? thisKnowledge.truthy : thisKnowledge.falsy;
+    auto yesTests = knowledgeToChoose->yesTypeTests;
+    auto noTests = knowledgeToChoose->noTypeTests;
```
Comment (DarkDimius) [inline infer/environment.cc]: This copies the vectors. Can this be auto&?
