### PR TITLE
Handle RBS type aliases within an empty Class or Module definition

### LINKED ISSUE #9133: Cannot use an empty class/module for just defining RBS type aliases
#### Input

[→ View on sorbet.run](https://sorbet.run/ace/?arg=--enable-experimental-rbs-comments#class%20A%0A%20%20%23%3A%20type%20b%20%3D%20Integer%0Aend)

```ruby
class A
  #: type b = Integer
end
```

#### Observed output

```
-e:2: Unexpected RBS assertion comment found in class https://srb.help/3554
     2 |  #: type b = Integer
          ^^^^^^^^^^^^^^^^^^^
```

#### Expected behavior

The expected behavior should be for `A::b` to be defined as a type alias.

- - -

The root of the problem seems to be that because the body of `A` is empty (except for the type comments), Sorbet cannot find a node to attach the type alias to and tries to interpret it as a type assertion instead.

### LINKED ISSUE #9344: Unexpected behaviour & error messages with RBS type aliases
#### Input

[→ View on sorbet.run](https://sorbet.run/?arg=--enable-experimental-rbs-comments#%23%20typed%3A%20true%0A%0Amodule%20M1%0A%20%20%23%3A%20type%20a1%20%3D%20nil%0Aend%0A%0Amodule%20M1%20%23%20reopen%0A%20%20%23%3A%20%28%29%20-%3E%20a1%0A%20%20def%20m1%20%3D%20nil%0Aend%0A%0Amodule%20M2%0A%20%20%23%3A%20type%20a2%20%3D%20nil%0A%0A%20%20class%20%3C%3C%20self%0A%20%20end%0Aend%0A%0Amodule%20M3%0A%20%20%23%3A%20type%20A3%20%3D%20nil%0Aend%0A%0Amodule%20M4%0A%20%20%23%3A%20type%20A4%20%3D%20nil%0A%0A%20%20class%20%3C%3C%20self%0A%20%20end%0Aend%0A%0Amodule%20M5%0A%20%20%23%3A%20type%20A5_1%20%3D%20nil%0A%20%20%23%3A%20type%20A5_2%20%3D%20nil%0Aend%0A%0Amodule%20M5%0A%20%20%23%3A%20type%20A6_1%20%3D%20nil%0A%20%20%23%3A%20type%20A6_2%20%3D%20nil%0A%0A%20%20class%20%3C%3C%20self%0A%20%20end%0Aend)

```ruby
# typed: true

module M1
  #: type a1 = nil
end

module M1 # reopen
  #: () -> a1
  def m1 = nil
end

module M2
  #: type a2 = nil

  class << self
  end
end

module M3
  #: type A3 = nil
end

module M4
  #: type A4 = nil

  class << self
  end
end

module M5
  #: type A5_1 = nil
  #: type A5_2 = nil
end

module M5
  #: type A6_1 = nil
  #: type A6_2 = nil

  class << self
  end
end
```

#### Observed output

```
editor.rb:4: Unexpected RBS assertion comment found in module https://srb.help/3554
     4 |  #: type a1 = nil
          ^^^^^^^^^^^^^^^^

editor.rb:20: Unexpected RBS assertion comment found in module https://srb.help/3554
    20 |  #: type A3 = nil
          ^^^^^^^^^^^^^^^^

editor.rb:31: Unexpected RBS assertion comment found in module https://srb.help/3554
    31 |  #: type A5_1 = nil
          ^^^^^^^^^^^^^^^^^^

editor.rb:32: Unexpected RBS assertion comment found in module https://srb.help/3554
    32 |  #: type A5_2 = nil
          ^^^^^^^^^^^^^^^^^^

editor.rb:24: Failed to parse RBS type parameters (expected a token `pLBRACKET`) https://srb.help/3550
    24 |  #: type A4 = nil
             ^^^^

editor.rb:36: Generic classes and modules can only have one RBS generic signature https://srb.help/3557
    36 |  #: type A6_1 = nil
          ^^^^^^^^^^^^^^^^^^

editor.rb:8: Unable to resolve constant type a1 https://srb.help/5002
     8 |  #: () -> a1
                   ^^
Errors: 7
```

#### Expected behavior

- The [docs](https://sorbet.org/docs/rbs-support#type-aliases) do not mention that type alias identifiers need to start with a lowercase letter, not an uppercase letter. When using an uppercase letter, the error messages are confusingly unrelated and change depending on what's around the attempted alias definition.
- The [docs](https://sorbet.org/docs/rbs-support#type-aliases) do mention
    > RBS type aliases are scoped to the class or module where they are declared

    but the example does not make it clear that the scoping is lexical[^1] and does not obey the constant resolution rules one might expect it to.
    ```diff
     class Foo
       #: type int_or_string =
       #|   Integer |
       #|   String

       # ok
       #: (int_or_string) -> void
       def foo(x); end

       class Bar
         # ok
         #: (int_or_string) -> void
         def bar(x); end
       end
     end


     #: (int_or_string) -> void
     #   ^^^^^^^^^^^^^ error: Unable to resolve constant `type int_or_string`
     def baz(x); end
    +
    +class Foo
    +  SOME_CONSTANT = 123 #: int_or_string
    +  #                      ^^^^^^^^^^^^^ error: Unable to resolve constant `type int_or_string`
    ```

[^1]: I believe "lexically scoped" is the correct term here, but I could be wrong. The important thing is that it doesn't behave the normal constant resolution semantics where it would be visible when "reopening" the constant it was "namespaced" within.

- - -

Ideally,

- the docs would explain that type alias identifiers must start with a lowercase letter (presumably the same rules as local variables, as opposed to constants)
- the docs would explain type alias scoping in more detail, including it not behaving like constants
- the error messages for incorrect usage would be more specific

### PR DESCRIPTION
**Pull request by jesse-shopify**
### Motivation

- Closes #9133 
- Closes #9344

### Test plan

See included automated tests.

### CODE REVIEW

File: rbs/CommentsAssociator.cc [hunk 1]
```diff
@@ -269,6 +269,25 @@ int CommentsAssociator::maybeInsertStandalonePlaceholders(parser::NodeVec &nodes
 }
 
 unique_ptr<parser::Node> CommentsAssociator::walkBody(parser::Node *node, unique_ptr<parser::Node> body) {
+    bool allowTypeAlias = false;
+    if (!contextAllowingTypeAlias.empty()) {
+        allowTypeAlias = contextAllowingTypeAlias.back().first;
+    }
```
Comment (Morriar) [inline rbs/CommentsAssociator.cc]: I wonder if we could extract this and the check lines 229-240 into a `typeAliasAllowedInContext` method?

File: test/testdata/rbs/signatures_type_aliases.rb [hunk 2]
```diff
@@ -151,3 +151,23 @@ def bar(x)
...
+
+module EmptyModule
+  #: type fooType = String
+end
+
+#: -> EmptyModule::fooType
+def module_alias_type
+  42
+# ^^ error: Expected `String` but found `Integer(42)` for method result type
+end
```
Comment (Morriar) [inline test/testdata/rbs/signatures_type_aliases.rb:179]: Let's also add a test for singleton methods

**Review by froydnj — CHANGES_REQUESTED** [review]
Requesting changes just so we can get @Morriar 's changes handled.

**Comment by Morriar** [comment]
@jesse-shopify can you add `Closes #9344` to this PR description please? 🙏

File: test/testdata/rbs/signatures_type_aliases.rb (hunk 2 above)
Comment (jesse-shopify) [reply test/testdata/rbs/signatures_type_aliases.rb:179]: Like this?

```ruby
class EmptySingleton
  class << self
    #: type c = Integer
  end
end
```

If so, is it possible to refer to that type using RBS?

Comment (Morriar) [reply test/testdata/rbs/signatures_type_aliases.rb:179]: This:

```rb
#: -> EmptyClass::b
def self.empty_class_alias_type
  42
# ^^ error: Expected `String` but found `Integer(42)` for method result type
end
```

> If so, is it possible to refer to that type using RBS?

Yes but only from inside the singleton itself:

```rb
class EmptySingleton
  class << self
    #: type c = Integer

    #: -> c
    def foo; end
  end
end
```

You should add this test as well.

File: rbs/CommentsAssociator.cc (hunk 1 above)
Comment (jesse-shopify) [reply rbs/CommentsAssociator.cc]: I've extracted `typeAliasAllowedInContext`

File: test/testdata/rbs/signatures_type_aliases.rb (hunk 2 above)
Comment (jesse-shopify) [reply test/testdata/rbs/signatures_type_aliases.rb:179]: I've added these tests.

**Review by froydnj — APPROVED** [review]

File: test/testdata/rbs/signatures_type_aliases.rb [hunk 3]
```diff
@@ -161,3 +161,37 @@ module TrailingTypeAlias
...
+
+#: -> EmptyClass::b
+def self.empty_class_alias_type
+  42
+# ^^ error: Expected `String` but found `Integer(42)` for method result type
+end
+
+class EmptySingleton
+  class << self
+    #: type c = Integer
```
Comment (amomchilov) [inline test/testdata/rbs/signatures_type_aliases.rb:189]: Could you please add a comment to explain this while this type alias can be made, it can only be referenced locally, and not from outside this sclass

Demo (using Sorbet notation, to not conflate with any limitations of RBS):

```rb
class Foo
  class << self
    MyInt = T.type_alias { Integer }
  end
end

# Both error with "Dynamic constant references are unsupported"
T.assert_type!(123, T.class_of(Foo)::MyInt)
T.assert_type!(123, T::Class[Foo]::MyInt)
```
